project:
  type: book

book:
  title: "Econometrics Guide"
  author: "Xiang Ao"
  date: "last-modified"
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - ols.qmd
    - mle.qmd
    - gls.qmd
    - endogeneity.qmd
    - gmm.qmd
    - censored.qmd
    - discrete.qmd
    - count-data.qmd
    - panel-data.qmd
    - survival.qmd
    - dynamic-panel.qmd
    - missing-data.qmd

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple
    code-tools: true
    number-sections: true
    toc-depth: 3

execute:
  freeze: auto
  warning: false
  message: false
