project:
  type: book

book:
  title: "Econometrics Guide"
  author: "Xiang Ao"
  date: "last-modified"
  search: true
  reader-mode: true
  page-navigation: true
  site-url: https://xiangao.github.io/econometrics-guide/
  repo-url: https://github.com/xiangao/econometrics-guide/
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: house-door-fill
        text: Xiang Ao home
        href: https://xiangao.github.io/
      - icon: book
        text: Other books
        href: https://xiangao.github.io/books.html
  chapters:
    - index.qmd
    - ols.qmd
    - mle.qmd
    - gls.qmd
    - endogeneity.qmd
    - gmm.qmd
    - censored.qmd
    - discrete.qmd
    - count-data.qmd
    - panel-data.qmd
    - survival.qmd
    - dynamic-panel.qmd
    - missing-data.qmd
    - references.qmd

format:
  html:
    theme:
      light: cosmo
    css: style.css
    include-in-header: reader-mode-default.html
    code-link: true
    callout-appearance: simple
    code-tools: true
    number-sections: true
    toc-depth: 3

execute:
  freeze: auto
  warning: false
  message: false
