<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>9&nbsp; Panel Data Models – Econometrics Guide</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./survival.html" rel="next">
<link href="./count-data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./panel-data.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Panel Data Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Econometrics Guide</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/econometrics-guide/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">OLS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Method of Maximum Likelihood</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">GLS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./endogeneity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Endogeneity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">General Method of Moments (GMM)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./censored.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Censored, truncated or selected data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Discrete and Limited Dependent Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Count data models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./panel-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Panel Data Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Survival Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dynamic-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Dynamic Panel Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Missing data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background"><span class="header-section-number">9.1</span> Background</a></li>
  <li><a href="#random-effect-methods" id="toc-random-effect-methods" class="nav-link" data-scroll-target="#random-effect-methods"><span class="header-section-number">9.2</span> Random Effect Methods</a></li>
  <li><a href="#fixed-effect-methods" id="toc-fixed-effect-methods" class="nav-link" data-scroll-target="#fixed-effect-methods"><span class="header-section-number">9.3</span> Fixed Effect Methods</a></li>
  <li><a href="#fixed-effects-or-random-effects-the-hausman-test" id="toc-fixed-effects-or-random-effects-the-hausman-test" class="nav-link" data-scroll-target="#fixed-effects-or-random-effects-the-hausman-test"><span class="header-section-number">9.4</span> Fixed effects or random effects: the Hausman test</a></li>
  <li><a href="#collapse-to-unit-means-or-keep-the-long-format" id="toc-collapse-to-unit-means-or-keep-the-long-format" class="nav-link" data-scroll-target="#collapse-to-unit-means-or-keep-the-long-format"><span class="header-section-number">9.5</span> Collapse to unit means, or keep the long format?</a></li>
  <li>
<a href="#what-the-long-format-buys" id="toc-what-the-long-format-buys" class="nav-link" data-scroll-target="#what-the-long-format-buys"><span class="header-section-number">9.6</span> What the long format buys</a>
  <ul class="collapse">
<li><a href="#the-equivalence-and-where-it-fails" id="toc-the-equivalence-and-where-it-fails" class="nav-link" data-scroll-target="#the-equivalence-and-where-it-fails"><span class="header-section-number">9.6.1</span> The equivalence, and where it fails</a></li>
  <li><a href="#what-collapsing-costs" id="toc-what-collapsing-costs" class="nav-link" data-scroll-target="#what-collapsing-costs"><span class="header-section-number">9.6.2</span> What collapsing costs</a></li>
  </ul>
</li>
  <li>
<a href="#how-ols-weights-the-data" id="toc-how-ols-weights-the-data" class="nav-link" data-scroll-target="#how-ols-weights-the-data"><span class="header-section-number">9.7</span> How OLS weights the data</a>
  <ul class="collapse">
<li><a href="#two-ways-to-read-the-coefficient" id="toc-two-ways-to-read-the-coefficient" class="nav-link" data-scroll-target="#two-ways-to-read-the-coefficient"><span class="header-section-number">9.7.1</span> Two ways to read the coefficient</a></li>
  <li><a href="#when-the-weighting-changes-the-answer" id="toc-when-the-weighting-changes-the-answer" class="nav-link" data-scroll-target="#when-the-weighting-changes-the-answer"><span class="header-section-number">9.7.2</span> When the weighting changes the answer</a></li>
  <li><a href="#which-mean-and-why-it-matters" id="toc-which-mean-and-why-it-matters" class="nav-link" data-scroll-target="#which-mean-and-why-it-matters"><span class="header-section-number">9.7.3</span> Which mean, and why it matters</a></li>
  <li><a href="#when-it-does-not-matter" id="toc-when-it-does-not-matter" class="nav-link" data-scroll-target="#when-it-does-not-matter"><span class="header-section-number">9.7.4</span> When it does not matter</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/econometrics-guide/edit/main/panel-data.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/econometrics-guide/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Panel Data Models</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="background" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="background">
<span class="header-section-number">9.1</span> Background</h2>
<p>Panel data are repeated observations on the same “unit” (we call that cross-sectional units) over time. Panel data models are used since it has advantages over cross-sectional models or time-series models. The major advantage it has over cross-sectional models is: <strong>Controlling for individual heterogeneity</strong>.</p>
<p>For example, Baltagi and Levin (1992) studies cigarette demand across 46 states for the years 1963-88. Consumption is modeled as a function of lagged consumption, price and income. These variables vary across states and time. However, there are other variables that may be time-invariant (<span class="math inline">\(z_i\)</span>) or individual-invariant (<span class="math inline">\(w_t\)</span>). Examples of <span class="math inline">\(z_i\)</span> are religion and, in a panel of adults, completed education. For example, Utah, as a Mormon state, has very low cigarette demand due to religious reason. Generally we consider it does not change over time or change very little over time. Examples of <span class="math inline">\(w_t\)</span> include cigarette commercials on national TV or radio. Panel data models are able to control for individual heterogeneity (or cross-sectional heterogeneity) while cross-sectional models are not. In many (or most) social science studies, there is “unobserved effects” which is embedded in the error term. In other words, we have “omitted variable” problem. Without controlling for it, the estimation results are generally biased and inconsistent.</p>
<p>Panel data give more informative data, more variability and less collinearity among variables. Often time series data suffers from multicollinearity, while panel data has more variability from its cross-sectional units.</p>
<p>The basic unobserved effects model can be written as: <span class="math display">\[
y_{it}={\bf {x_{it} \beta}} + c_i + u_{it}
\]</span></p>
<p>where <span class="math inline">\(i\)</span> indexes “units” (can be people, firms, or households, etc.), and <span class="math inline">\(t\)</span> indexes time periods.</p>
<p>Three kinds of regressor appear in this chapter, and it pays to name them once. <span class="math inline">\({\bf x}_{it}\)</span> varies across units <em>and</em> time — price, income, and in most applications the treatment itself. <span class="math inline">\(z_i\)</span> varies across units only, so within a unit it is fixed over time; religion and completed education above are the examples. <span class="math inline">\(w_t\)</span> varies across time only, so in any period it is common to every unit; the national TV campaign is one. Which group a variable falls into is what decides almost everything that follows, including which coefficients fixed effects can estimate and how OLS weights the data.</p>
<p>Instruments do not appear until the panel turns dynamic. When they do, they are written <span class="math inline">\({\bf Z}\)</span>, which is a different object from the time-invariant <span class="math inline">\(z_i\)</span> here — see the <a href="./endogeneity.html">Endogeneity</a>, <a href="./gmm.html">GMM</a> and <a href="./dynamic-panel.html">Dynamic Panel Data</a> chapters.</p>
<p>Comparing to regular cross-sectional models, there is an extra term <span class="math inline">\(c_i\)</span>. <span class="math inline">\(c_i\)</span> can be treated as a random effect or fixed effect. Traditionally it is distinguished by whether it is estimated as a random variable or a parameter. Modern econometrics tends to distinguish by the correlation between <span class="math inline">\(c_i\)</span> and <span class="math inline">\({\bf {x_{it}}}\)</span>. If there is no correlation between <span class="math inline">\(c_i\)</span> and <span class="math inline">\({\bf {x_{it}}}\)</span>, then it’s a random effect; otherwise, it’s a fixed effect.</p>
<p>It is true that in some cases it is hard to justify that there is no correlation between <span class="math inline">\(c_i\)</span> and <span class="math inline">\({\bf {x_{it}}}\)</span>, which is one reason that people in economics tend to use fixed-effect models. However, fixed-effect models have its own limitations. One of them is: It is hard to justify that ALL the cross-sectional units’ characteristics other than those already in the model do not change over time.</p>
</section><section id="random-effect-methods" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="random-effect-methods">
<span class="header-section-number">9.2</span> Random Effect Methods</h2>
<p>A random effect model puts <span class="math inline">\(c_i\)</span> into the error term, then estimate by FGLS (feasible GLS). Random effect model is sometimes called “Error-components model” since the overall error term is divided into an individual level error term (<span class="math inline">\(c_i\)</span>) and individual-time level error term (<span class="math inline">\(u_{it}\)</span>).</p>
<p>Under a random effect model, the variance-covariance matrix of the error term becomes:</p>
<p><span class="math display">\[
\bf \Omega=
\begin{bmatrix} \sigma_{c}^2 + \sigma_u^2 &amp; \sigma_{c}^2 &amp; \cdots &amp; \sigma_{c}^2
  \\ \sigma_{c}^2 &amp; \sigma_{c}^2 + \sigma_u^2 &amp; \cdots &amp; \sigma_{c}^2 \\ \vdots &amp;
  \vdots &amp; \ddots &amp; \vdots \\ \sigma_{c}^2  &amp; \sigma_{c}^2  &amp; \cdots &amp; \sigma_{c}^2 + \sigma_u^2
\end{bmatrix}
\]</span></p>
<p>The random effect estimator is:</p>
<p><span class="math display">\[ \bf \hat \beta_{RE} = (\sum_{i=1}^N X_i' \hat \Omega^{-1} X_i)^{-1} (\sum_{i=1}^N X_i' \hat \Omega^{-1} y_i)\]</span></p>
<p>It is a special case of GLS. Before calculating <span class="math inline">\(\hat \beta_{RE}\)</span>, $ <em>{c}^2$ and $ </em>{u}^2$ need to be estimated. This is generally done by using residuals from within and between regressions (the Swamy-Arora method, the default in most software), or from pooled OLS.</p>
</section><section id="fixed-effect-methods" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="fixed-effect-methods">
<span class="header-section-number">9.3</span> Fixed Effect Methods</h2>
<p>Random effect methods assume that <span class="math inline">\(c_i\)</span> be orthogonal to <span class="math inline">\(\bf x_{it}\)</span>. In many applications, the whole point of using panel data is to allow <span class="math inline">\(c_i\)</span> be correlated with <span class="math inline">\(\bf x_{it}\)</span>. We need fixed-effect models in those cases.</p>
<p>For the same model as in the equation above, the fixed-effect methods try to eliminate <span class="math inline">\(c_i\)</span> using fixed effects transformation, or “within transformation”. The FE transformation is to “de-mean” each observation by subtracting the group mean. Basically subtracting the group-mean equation below from the unit-level equation above:</p>
<p><span class="math display">\[
\bar y_i={\bf \bar x_i \beta} + c_i + \bar u_i
\]</span></p>
<p>where $y_i $, etc., means group means. For example, if we have 50 states with state level data of cigarette consumption across years, then groups means states, and we have 50 group means which are state level average cigarette consumption across years.</p>
<p>The reason for “demeaning” is to remove <span class="math inline">\(c_i\)</span> from final estimation. The “demeaned” regression equation is the final regression used in estimation:</p>
<p><span class="math display">\[
(y_{it}-\bar y_i) = ({\bf x}_{it}-{\bf \bar x}_i)\beta + (u_{it}-\bar u_i).
\]</span></p>
<p>The unit-specific effect <span class="math inline">\(c_i\)</span> cancels because it is constant over <span class="math inline">\(t\)</span> (<span class="math inline">\(c_i - \bar c_i = 0\)</span>). Writing the within-transformed variables as <span class="math inline">\(\ddot y_{it}=y_{it}-\bar y_i\)</span> and <span class="math inline">\(\ddot{\bf x}_{it}={\bf x}_{it}-{\bf \bar x}_i\)</span>, OLS on the demeaned data gives the <strong>fixed-effects (within) estimator</strong> (here <span class="math inline">\({\bf x}_{it}\)</span> is a <span class="math inline">\(1\times k\)</span> <em>row</em> vector, so <span class="math inline">\(\ddot{\bf x}_{it}'\ddot{\bf x}_{it}\)</span> is the <span class="math inline">\(k\times k\)</span> outer product)</p>
<p><span class="math display">\[
\hat\beta_{FE} = \left(\sum_i \sum_t \ddot{\bf x}_{it}'\ddot{\bf x}_{it}\right)^{-1}
\sum_i \sum_t \ddot{\bf x}_{it}'\ddot y_{it}.
\]</span></p>
<p>This is consistent for <span class="math inline">\(\beta\)</span> even when <span class="math inline">\(c_i\)</span> is correlated with <span class="math inline">\({\bf x}_{it}\)</span>, which is the key advantage of FE over random effects. The price is that any time-invariant regressor (the <span class="math inline">\(z_i\)</span> above) is also swept out by the demeaning and cannot be estimated. The usual variance estimator is <span class="math inline">\(\hat V(\hat\beta_{FE})=\hat\sigma_u^2(\sum_i\sum_t \ddot{\bf x}_{it}'\ddot{\bf x}_{it})^{-1}\)</span> with <span class="math inline">\(\hat\sigma_u^2\)</span> using degrees of freedom <span class="math inline">\(NT-N-k\)</span>; in practice one clusters by unit to allow serial correlation within <span class="math inline">\(i\)</span>.</p>
</section><section id="fixed-effects-or-random-effects-the-hausman-test" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="fixed-effects-or-random-effects-the-hausman-test">
<span class="header-section-number">9.4</span> Fixed effects or random effects: the Hausman test</h2>
<p>Random effects is more efficient (it uses both within and between variation) but is consistent only if <span class="math inline">\(c_i\)</span> is uncorrelated with <span class="math inline">\({\bf x}_{it}\)</span>; fixed effects is consistent either way. The Hausman test compares the two estimators:</p>
<p><span class="math display">\[
H = (\hat\beta_{FE}-\hat\beta_{RE})'\,[\hat V(\hat\beta_{FE})-\hat V(\hat\beta_{RE})]^{-1}\,(\hat\beta_{FE}-\hat\beta_{RE}) \;\sim\; \chi^2_k
\]</span></p>
<p>under the null that random effects is consistent. A large <span class="math inline">\(H\)</span> (small <span class="math inline">\(p\)</span>-value) favors fixed effects. In R this is <code>phtest(fe, re)</code> from the <code>plm</code> package; in Stata, <code>hausman fe re</code>.</p>
<p><strong>Caveat: this classic form requires RE to be efficient.</strong> The formula above relies on <span class="math inline">\(\hat V(\hat\beta_{FE})-\hat V(\hat\beta_{RE})\)</span> being positive semi-definite, which in turn requires the RE estimator to actually be the <em>efficient</em> estimator under the null – true only under the RE model’s homoscedasticity and no-serial-correlation assumptions. If you are using robust or cluster-robust covariance matrices (the usual practice when errors are heteroscedastic or serially correlated), RE is generally no longer efficient, the covariance difference can fail to be positive definite, and the classic Hausman test statistic can be negative or otherwise ill-behaved. In that case, use a regression-based Hausman test instead: augment the RE (or pooled) regression with the within-unit means of the time-varying regressors (Mundlak’s approach) or with the demeaned regressors themselves (Wooldridge’s regression-based test), and test the added coefficients jointly with a standard (robust) Wald test – this is valid under heteroscedasticity/clustering and reduces to the same idea as the classic Hausman test under its assumptions.</p>
</section><section id="collapse-to-unit-means-or-keep-the-long-format" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="collapse-to-unit-means-or-keep-the-long-format">
<span class="header-section-number">9.5</span> Collapse to unit means, or keep the long format?</h2>
<p>A practical question comes up whenever we hold a panel. Should we average each unit over time and run one regression on the <span class="math inline">\(N\)</span> resulting rows, or keep all <span class="math inline">\(NT\)</span> rows and cluster the standard errors by unit? Many people treat this as a trade-off and assume the long format must carry more information. It usually does not. The answer turns entirely on where the regressors live.</p>
<p>Take the case where every regressor is time-invariant, so the model is <span class="math inline">\(y_{it}={\bf z}_i \gamma + c_i + u_{it}\)</span>. With a balanced panel, pooled OLS on the <span class="math inline">\(NT\)</span> rows and OLS on the <span class="math inline">\(N\)</span> unit means give the same <span class="math inline">\(\hat\gamma\)</span>. Not close — identical. Random effects returns the same number as well. Wooldridge (2010) states the reason plainly: because <span class="math inline">\(c_i\)</span> is there, new observations within a unit carry no information about <span class="math inline">\(\gamma\)</span> beyond how they move the unit average <span class="math inline">\(\bar y_i\)</span>. In effect we only have <span class="math inline">\(N\)</span> useful pieces of information. Averaging discards nothing, because <span class="math inline">\({\bf z}_i\)</span> was already constant over <span class="math inline">\(t\)</span> and the within variation was never available to <span class="math inline">\(\gamma\)</span> in the first place.</p>
<p>What does differ is the degrees of freedom. The unit-mean regression uses <span class="math inline">\(N-k\)</span>; pooled OLS reports <span class="math inline">\(NT-k\)</span>, and that is the mistake. Moulton (1990) is the classic illustration, and Donald and Lang (2007) show that <span class="math inline">\(t_{N-k}\)</span> is the reference distribution that keeps the size right. Clustering by unit repairs the standard error when <span class="math inline">\(N\)</span> is large, but it does not repair the degrees of freedom when <span class="math inline">\(N\)</span> is small.</p>
<p>Now put a time-varying <span class="math inline">\({\bf x}_{it}\)</span> into the model. The two options stop agreeing, and not only for the coefficient on <span class="math inline">\({\bf x}_{it}\)</span> — every coefficient moves, the one on <span class="math inline">\({\bf z}_i\)</span> included. Averaging to unit means throws away all within variation, so what survives is the between estimator. Pooled OLS keeps both sources and forces a single coefficient on them, so it returns a variance-weighted average of the within and the between relationship. The two agree only when the within and between coefficients are equal, which is precisely the null the Hausman test examines. So this is not a new problem. It is the FE-versus-RE question in different clothes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Situation</th>
<th>Collapsed vs long</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>All regressors time-invariant, balanced panel</td>
<td>Same coefficients; only the degrees of freedom differ</td>
</tr>
<tr class="even">
<td>Any time-varying regressor</td>
<td>All coefficients differ, including those on <span class="math inline">\({\bf z}_i\)</span>
</td>
</tr>
<tr class="odd">
<td>Unbalanced panel</td>
<td>Differ regardless, since pooled OLS weights each unit by <span class="math inline">\(T_i\)</span>
</td>
</tr>
</tbody>
</table>
<p>The reconciliation is Mundlak’s device, the same one used above for the regression-based Hausman test. Add the unit means <span class="math inline">\({\bf \bar x}_i\)</span> to the long regression alongside <span class="math inline">\({\bf x}_{it}\)</span>, and the within and between variation carry separate coefficients: <span class="math inline">\({\bf x}_{it}\)</span> picks up the within estimate, <span class="math inline">\({\bf \bar x}_i\)</span> picks up the <em>difference</em> between the between and within estimates, so the two coefficients sum to what the collapsed regression reports. That second coefficient is the Hausman contrast, and its <span class="math inline">\(t\)</span>-statistic is the Hausman test. We keep the within variation and recover the between answer in one regression.</p>
<p>The useful way to remember it: collapse freely when every regressor is constant within the group, and never when one is not.</p>
</section><section id="what-the-long-format-buys" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="what-the-long-format-buys">
<span class="header-section-number">9.6</span> What the long format buys</h2>
<p>The section above is mostly a warning. The other side is worth seeing directly, so we simulate panels where we know the truth. We use <code>fixest</code> here; in Stata the same regressions are <code>regress</code>, <code>xtreg, be</code> and <code>xtreg, fe</code>.</p>
<section id="the-equivalence-and-where-it-fails" class="level3" data-number="9.6.1"><h3 data-number="9.6.1" class="anchored" data-anchor-id="the-equivalence-and-where-it-fails">
<span class="header-section-number">9.6.1</span> The equivalence, and where it fails</h3>
<p>Take 1000 units over 6 periods, one time-invariant regressor <span class="math inline">\(z_i\)</span>, and a true <span class="math inline">\(\gamma=2\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">1000</span>; <span class="cn">T</span> <span class="op">&lt;-</span> <span class="fl">6</span></span>
<span></span>
<span><span class="va">z</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span></span>
<span><span class="va">bal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">N</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span>, t <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="cn">T</span>, <span class="va">N</span><span class="op">)</span>,</span>
<span>                  z  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">z</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span>, c <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">bal</span><span class="op">$</span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">bal</span><span class="op">$</span><span class="va">z</span> <span class="op">+</span> <span class="va">bal</span><span class="op">$</span><span class="va">c</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span><span class="op">)</span></span>
<span><span class="va">agg</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">z</span><span class="op">)</span> <span class="op">~</span> <span class="va">id</span>, data <span class="op">=</span> <span class="va">bal</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>long      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">z</span>, <span class="va">bal</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"z"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>        collapsed <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">z</span>, <span class="va">agg</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"z"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         long     collapsed 
1.99351677619 1.99351677619 </code></pre>
</div>
</div>
<p>The two agree to every digit printed. Now break the balance by dropping the later periods for units with high <span class="math inline">\(z_i\)</span>, so <span class="math inline">\(T_i\)</span> varies, and varies with the regressor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">unb</span>  <span class="op">&lt;-</span> <span class="va">bal</span><span class="op">[</span><span class="op">!</span><span class="op">(</span><span class="va">bal</span><span class="op">$</span><span class="va">z</span> <span class="op">&gt;</span> <span class="fl">0.5</span> <span class="op">&amp;</span> <span class="va">bal</span><span class="op">$</span><span class="va">t</span> <span class="op">&gt;</span> <span class="fl">2</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="va">agg2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">z</span><span class="op">)</span> <span class="op">~</span> <span class="va">id</span>, data <span class="op">=</span> <span class="va">unb</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>long      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">z</span>, <span class="va">unb</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"z"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>        collapsed <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">z</span>, <span class="va">agg2</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"z"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         long     collapsed 
2.00682070731 2.01481052322 </code></pre>
</div>
</div>
<p>They no longer agree. Pooled OLS weights each unit by <span class="math inline">\(T_i\)</span>; the collapsed regression counts each unit once. Neither is wrong — they answer different questions, and we should know which one we asked. That <span class="math inline">\(T_i\)</span> is a special case of a general rule, set out in the next section.</p>
</section><section id="what-collapsing-costs" class="level3" data-number="9.6.2"><h3 data-number="9.6.2" class="anchored" data-anchor-id="what-collapsing-costs">
<span class="header-section-number">9.6.2</span> What collapsing costs</h3>
<p>Now the case that matters. Let <span class="math inline">\(x_{it}\)</span> vary over time and make <span class="math inline">\(c_i\)</span> correlated with <span class="math inline">\(\bar x_i\)</span>, which is the situation fixed effects exists for. The truth is <span class="math inline">\(\beta=1\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span></span>
<span><span class="va">d</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">N</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span>,</span>
<span>                 x  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">mu</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span><span class="op">)</span>,</span>
<span>                 c  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">mu</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">d</span><span class="op">$</span><span class="va">y</span>    <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">*</span> <span class="va">d</span><span class="op">$</span><span class="va">x</span> <span class="op">+</span> <span class="va">d</span><span class="op">$</span><span class="va">c</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span><span class="op">)</span></span>
<span><span class="va">d</span><span class="op">$</span><span class="va">xbar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/ave.html">ave</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">x</span>, <span class="va">d</span><span class="op">$</span><span class="va">id</span><span class="op">)</span></span>
<span><span class="va">dagg</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">x</span><span class="op">)</span> <span class="op">~</span> <span class="va">id</span>, data <span class="op">=</span> <span class="va">d</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></span>
<span></span>
<span><span class="va">between</span> <span class="op">&lt;-</span> <span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>,        data <span class="op">=</span> <span class="va">dagg</span><span class="op">)</span></span>
<span><span class="va">pooled</span>  <span class="op">&lt;-</span> <span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>,        data <span class="op">=</span> <span class="va">d</span>, cluster <span class="op">=</span> <span class="op">~</span><span class="va">id</span><span class="op">)</span></span>
<span><span class="va">within</span>  <span class="op">&lt;-</span> <span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span> <span class="op">|</span> <span class="va">id</span>,   data <span class="op">=</span> <span class="va">d</span><span class="op">)</span></span>
<span><span class="va">mundlak</span> <span class="op">&lt;-</span> <span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span> <span class="op">+</span> <span class="va">xbar</span>, data <span class="op">=</span> <span class="va">d</span>, cluster <span class="op">=</span> <span class="op">~</span><span class="va">id</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pull</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">m</span>, <span class="va">v</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span><span class="op">[[</span><span class="va">v</span><span class="op">]</span><span class="op">]</span>, <span class="fu">se</span><span class="op">(</span><span class="va">m</span><span class="op">)</span><span class="op">[[</span><span class="va">v</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>`between (collapsed)` <span class="op">=</span> <span class="fu">pull</span><span class="op">(</span><span class="va">between</span>, <span class="st">"x"</span><span class="op">)</span>,</span>
<span>             `pooled OLS`          <span class="op">=</span> <span class="fu">pull</span><span class="op">(</span><span class="va">pooled</span>,  <span class="st">"x"</span><span class="op">)</span>,</span>
<span>             `within / FE`         <span class="op">=</span> <span class="fu">pull</span><span class="op">(</span><span class="va">within</span>,  <span class="st">"x"</span><span class="op">)</span>,</span>
<span>             `Mundlak: x`          <span class="op">=</span> <span class="fu">pull</span><span class="op">(</span><span class="va">mundlak</span>, <span class="st">"x"</span><span class="op">)</span>,</span>
<span>             `Mundlak: xbar`       <span class="op">=</span> <span class="fu">pull</span><span class="op">(</span><span class="va">mundlak</span>, <span class="st">"xbar"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"estimate"</span>, <span class="st">"std. error"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">tab</span>, <span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    estimate std. error
between (collapsed)    1.845      0.035
pooled OLS             1.484      0.022
within / FE            0.995      0.014
Mundlak: x             0.995      0.014
Mundlak: xbar          0.850      0.036</code></pre>
</div>
</div>
<p>Read the table down. The collapsed regression returns about 1.85, badly biased, because it is the between estimator and <span class="math inline">\(\bar x_i\)</span> carries <span class="math inline">\(c_i\)</span> with it. Pooled OLS returns about 1.48 — closer, since some within variation is mixed in, but still inconsistent. The within estimator returns about 0.99, and only the long format can compute it: once we collapse there is nothing left to demean. Mundlak delivers both at once, exactly as described above — 0.99 on <span class="math inline">\(x_{it}\)</span>, 0.85 on <span class="math inline">\(\bar x_i\)</span>, and <span class="math inline">\(0.99+0.85\)</span> recovers the between estimate.</p>
<p>So the argument for the long format is not precision. It is that demeaning, the Hausman comparison, unit-specific slopes, lagged dependent variables and anything else built on within variation stop existing once the panel is collapsed. Dynamic models are the extreme case, and they get their own chapter, <a href="./dynamic-panel.html">Dynamic Panel Data</a>.</p>
</section></section><section id="how-ols-weights-the-data" class="level2" data-number="9.7"><h2 data-number="9.7" class="anchored" data-anchor-id="how-ols-weights-the-data">
<span class="header-section-number">9.7</span> How OLS weights the data</h2>
<p>Twice above we said OLS weights units unequally: by <span class="math inline">\(T_i\)</span> when the panel is unbalanced, and by variance when it mixes within and between variation. Neither is a panel-specific quirk. Both follow from one rule.</p>
<p>Let <span class="math inline">\(V\)</span> be the regressor of interest and <span class="math inline">\(\tilde V\)</span> be <span class="math inline">\(V\)</span> after residualising on every other regressor in the model. By the Frisch–Waugh–Lovell theorem,</p>
<p><span class="math display">\[
\hat\beta = \frac{\sum_i \sum_t \tilde V_{it}\, y_{it}}
                 {\sum_i \sum_t \tilde V_{it}^{2}} .
\]</span></p>
<p>Be careful what <span class="math inline">\(\tilde V_{it}\)</span> is. A single observation has no variation of its own — variation belongs to a collection. What it has is a <strong>deviation</strong>: how far its regressor sits from what the rest of the model predicts for it. With only an intercept that is distance from the grand mean; with unit effects it is distance from the unit’s own mean. Which mean gets subtracted is the single most consequential detail in this section, and we return to it.</p>
<section id="two-ways-to-read-the-coefficient" class="level3" data-number="9.7.1"><h3 data-number="9.7.1" class="anchored" data-anchor-id="two-ways-to-read-the-coefficient">
<span class="header-section-number">9.7.1</span> Two ways to read the coefficient</h3>
<p>The formula supports two readings. They describe one estimator and differ in what is being weighted.</p>
<p><span class="math display">\[
\hat\beta = \sum_i \omega_i\, y_i , \quad
\omega_i = \frac{\tilde V_i}{\sum_j \tilde V_j^2}
\qquad\text{versus}\qquad
\hat\beta = \frac{\sum_i w_i\, \beta_i}{\sum_i w_i} , \quad
w_i = \tilde V_i V_i .
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>Weights on outcomes, <span class="math inline">\(\omega_i\)</span>
</th>
<th>Weights on effects, <span class="math inline">\(w_i\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Weights what</td>
<td>the observed <span class="math inline">\(y_i\)</span>
</td>
<td>that observation’s own effect <span class="math inline">\(\beta_i\)</span>
</td>
</tr>
<tr class="even">
<td>Sign</td>
<td>signed, sums to zero</td>
<td>non-negative</td>
</tr>
<tr class="odd">
<td>Computable</td>
<td>yes, <span class="math inline">\(y\)</span> is observed</td>
<td>no, the <span class="math inline">\(\beta_i\)</span> are never seen</td>
</tr>
<tr class="even">
<td>Holds when</td>
<td>always, it is algebra</td>
<td>after writing effects into <span class="math inline">\(y\)</span>; the per-unit reading also needs saturation</td>
</tr>
<tr class="odd">
<td>Answers</td>
<td>which rows drive this number, and does any enter with the wrong sign</td>
<td>is this the effect I meant, and whose effect is it mostly</td>
</tr>
</tbody>
</table>
<p>Default to the second. Nearly every question that motivates the topic — is my coefficient the average effect, whose effect does it report, why do smaller groups get larger weights — is a question about the estimand. Reach for the first when overlap is in doubt and you need to see whether observations enter negatively, which squares cannot show. Both are developed at length in <a href="https://xiangao.github.io/blog_book/weights-ols.html">Weights in OLS in causal inference</a>.</p>
<p>The square in <span class="math inline">\(w_i\)</span> is derived, not assumed. Substituting <span class="math inline">\(y_{it}=\beta_i V_{it}+\ldots\)</span> into the numerator gives <span class="math inline">\(\sum_i \beta_i \sum_t \tilde V_{it}V_{it}\)</span>, and over the whole sample <span class="math inline">\(\sum \tilde V V=\sum \tilde V^2\)</span> because <span class="math inline">\(\tilde V\)</span> is orthogonal to the fitted part of <span class="math inline">\(V\)</span>. Whether that holds <em>unit by unit</em> — which is what licenses reading <span class="math inline">\(\sum_t \tilde V_{it}^2\)</span> as unit <span class="math inline">\(i\)</span>’s weight — depends on the residualising being done within the unit. Demeaning delivers it by direct expansion, <span class="math inline">\(\sum_t (V_{it}-\bar V_i)V_{it}=\sum_t V_{it}^2 - T\bar V_i^{\,2}
=\sum_t (V_{it}-\bar V_i)^2\)</span>, while a coarser control matches only in total. Hazlett and Shinkre make this the centre of their treatment; the Angrist row below assumes the saturated case.</p>
<p>In general <span class="math inline">\(\sum_t \tilde V_{it}^2\)</span> will not factor into anything tidier, since <span class="math inline">\(\tilde V_{it}\)</span> carries both subscripts even when <span class="math inline">\(V\)</span> does not. What changes from model to model is whether it happens to simplify.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Model</th>
<th>
<span class="math inline">\(\sum_t \tilde V_{it}^2\)</span> simplifies to</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<span class="math inline">\(z_i\)</span> alone, nothing else varying within the unit</td>
<td><span class="math inline">\(T_i\,\tilde z_i^2\)</span></td>
</tr>
<tr class="even">
<td>a time-varying <span class="math inline">\(x_{it}\)</span>, unit effects removed</td>
<td><span class="math inline">\((T-1)\,\widehat{\text{Var}}_i(x)\)</span></td>
</tr>
<tr class="odd">
<td>binary <span class="math inline">\(d\)</span> with saturated controls</td>
<td><span class="math inline">\(n_x\,\hat d(x)\,(1-\hat d(x))\)</span></td>
</tr>
</tbody>
</table>
<p>Add a time-varying <span class="math inline">\(x_{it}\)</span> alongside <span class="math inline">\(z_i\)</span> in the first model and the simplification is gone: residualising <span class="math inline">\(z_i\)</span> on something that moves within the unit makes <span class="math inline">\(\tilde z\)</span> move within the unit too. The rule survives, the shortcut does not, and the <span class="math inline">\(T_i\)</span> form is the one-regressor special case rather than the general one. The last row is Angrist (<a href="https://doi.org/10.2307/2998558">1998</a>), whose strata weights <span class="math inline">\(\hat d(x)(1-\hat d(x))\)</span> are largest where treatment is closest to a coin flip. Same rule, different regressor.</p>
</section><section id="when-the-weighting-changes-the-answer" class="level3" data-number="9.7.2"><h3 data-number="9.7.2" class="anchored" data-anchor-id="when-the-weighting-changes-the-answer">
<span class="header-section-number">9.7.2</span> When the weighting changes the answer</h3>
<p>The weighting always happens. It changes the answer only when the effect is heterogeneous <em>and</em> the heterogeneity lines up with the weight. The claim to check is that a regression does not report <em>the</em> effect but a weighted average of the effects, and that these are different numbers.</p>
<p>The individual effects are never observed, so we plant them: give every unit its own slope <span class="math inline">\(\beta_i\)</span>, generate <span class="math inline">\(y\)</span> from those slopes, and see which average of the planted slopes the estimate lands on. In the next chunk only one estimator is run; anything else reported is not an estimate but the planted slopes averaged some way. Fixed effects is used because in a panel the natural place for heterogeneity is across units, and it is still OLS — OLS with the unit dummies partialled out.</p>
<p>Start with the extreme case. Half the units barely move and have a true slope of zero; the other half move a great deal and have a true slope of two. The average unit’s slope is one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">half</span> <span class="op">&lt;-</span> <span class="va">N</span> <span class="op">/</span> <span class="fl">2</span></span>
<span><span class="va">g</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>id   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">N</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span>,</span>
<span>                move <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0.2</span>, <span class="va">half</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">3</span>, <span class="va">half</span><span class="op">)</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span>,</span>
<span>                b    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,   <span class="va">half</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">2</span>, <span class="va">half</span><span class="op">)</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">g</span><span class="op">$</span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span>, <span class="fl">0</span>, <span class="va">g</span><span class="op">$</span><span class="va">move</span><span class="op">)</span></span>
<span><span class="va">g</span><span class="op">$</span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">g</span><span class="op">$</span><span class="va">b</span> <span class="op">*</span> <span class="va">g</span><span class="op">$</span><span class="va">x</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span><span class="op">)</span></span>
<span></span>
<span><span class="va">wg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/tapply.html">tapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">x</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">id</span>, <span class="va">g</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>, <span class="va">g</span><span class="op">$</span><span class="va">id</span>, <span class="va">sum</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  `average of the two true slopes`      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  `FE estimate`                         <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span> <span class="op">|</span> <span class="va">id</span>, <span class="va">g</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"x"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>  `weight held by the steady half (%)`  <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">wg</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">half</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">wg</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   value
average of the two true slopes     1.000
FE estimate                        1.984
weight held by the steady half (%) 0.473</code></pre>
</div>
</div>
<p>The average slope is one and the regression reports 1.98, because the five hundred steady units hold under half of one percent of the weight. Their six observations sit almost on top of their own unit mean — this regression carries unit effects, so that is the relevant deviation — and squaring puts them nowhere in the sum. Nothing has gone wrong in the arithmetic. The units with a slope of zero were never really in the regression.</p>
</section><section id="which-mean-and-why-it-matters" class="level3" data-number="9.7.3"><h3 data-number="9.7.3" class="anchored" data-anchor-id="which-mean-and-why-it-matters">
<span class="header-section-number">9.7.3</span> Which mean, and why it matters</h3>
<p>That result is about the <em>within-unit</em> deviation. Plain OLS uses distance from the grand mean instead, and the two coincided above only because both halves were built around zero. Separate them and the algebra says exactly what happens.</p>
<p>Take two equally sized groups with means <span class="math inline">\(\mu_g\)</span>, within-group variances <span class="math inline">\(\sigma_g^2\)</span>, slopes <span class="math inline">\(\beta_g\)</span> and group mean outcomes <span class="math inline">\(\bar y_g\)</span>. The law of total covariance splits <span class="math inline">\(\text{Cov}(x,y)\)</span> and <span class="math inline">\(\text{Var}(x)\)</span> into within and between parts, giving</p>
<p><span class="math display">\[
\text{plim}\;\hat\beta_{OLS}
= \frac{\tfrac12\!\left(\beta_1\sigma_1^2+\beta_2\sigma_2^2\right)
        + \tfrac14\,\Delta\mu\,\Delta\bar y}
       {\tfrac12\!\left(\sigma_1^2+\sigma_2^2\right)
        + \tfrac14\,\Delta\mu^{2}} ,
\]</span></p>
<p>with <span class="math inline">\(\Delta\mu=\mu_1-\mu_2\)</span> and <span class="math inline">\(\Delta\bar y=\bar y_1-\bar y_2\)</span>: a variance-weighted average of <span class="math inline">\(\beta_{within}=(\beta_1\sigma_1^2+\beta_2\sigma_2^2)/(\sigma_1^2+\sigma_2^2)\)</span> and <span class="math inline">\(\beta_{between}=\Delta\bar y/\Delta\mu\)</span>, weighted by the within variance <span class="math inline">\(\tfrac12(\sigma_1^2+\sigma_2^2)\)</span> and the between variance <span class="math inline">\(\tfrac14\Delta\mu^2\)</span>.</p>
<p>Everything follows without running anything. Fixed effects estimates <span class="math inline">\(\beta_{within}\)</span>, here <span class="math inline">\((0\cdot 0.04 + 2\cdot 9)/9.04 = 1.991\)</span>, which involves no <span class="math inline">\(\mu_g\)</span> — so parking a group anywhere cannot move it. Plain OLS also carries <span class="math inline">\(\beta_{between}\)</span>, which is zero in this design because the steady slope and both intercepts are zero, leaving the two group means at the same height. As <span class="math inline">\(\Delta\mu\)</span> grows, the between weight <span class="math inline">\(\tfrac14\Delta\mu^2\)</span> swamps the fixed within weight of <span class="math inline">\(4.52\)</span> and the coefficient is dragged from <span class="math inline">\(1.991\)</span> toward zero like <span class="math inline">\(9/(4.52+\Delta\mu^2/4)\)</span>, the numerator being <span class="math inline">\(\tfrac12(\beta_1\sigma_1^2+\beta_2\sigma_2^2)=9\)</span>. The simulation is a check on that, not the source of it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">b_within</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">0</span> <span class="op">*</span> <span class="fl">0.2</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="fl">3</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">0.2</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fl">3</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>   <span class="co"># variance-weighted slope</span></span>
<span><span class="va">V_within</span> <span class="op">&lt;-</span> <span class="fl">0.5</span> <span class="op">*</span> <span class="op">(</span><span class="fl">0.2</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fl">3</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>                     <span class="co"># within variance</span></span>
<span><span class="va">predicted</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">shift</span><span class="op">)</span>                        <span class="co"># beta_between = 0 here</span></span>
<span>  <span class="va">V_within</span> <span class="op">*</span> <span class="va">b_within</span> <span class="op">/</span> <span class="op">(</span><span class="va">V_within</span> <span class="op">+</span> <span class="fl">0.25</span> <span class="op">*</span> <span class="va">shift</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">park</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">shift</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span>, <span class="fl">0</span>, <span class="va">g</span><span class="op">$</span><span class="va">move</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">shift</span>, <span class="va">half</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">half</span><span class="op">)</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span>
<span>  <span class="va">y</span> <span class="op">&lt;-</span> <span class="va">g</span><span class="op">$</span><span class="va">b</span> <span class="op">*</span> <span class="va">x</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span><span class="op">)</span></span>
<span>  <span class="va">d</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>id <span class="op">=</span> <span class="va">g</span><span class="op">$</span><span class="va">id</span>, x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`FE (theory 1.991)` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span> <span class="op">|</span> <span class="va">id</span>, <span class="va">d</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"x"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>    `OLS predicted`     <span class="op">=</span> <span class="fu">predicted</span><span class="op">(</span><span class="va">shift</span><span class="op">)</span>,</span>
<span>    `OLS actual`        <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>, <span class="va">d</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"x"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`shift 0` <span class="op">=</span> <span class="fl">0</span>, `shift 10` <span class="op">=</span> <span class="fl">10</span>, `shift 100` <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>, <span class="va">park</span><span class="op">)</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          FE (theory 1.991) OLS predicted OLS actual
shift 0               1.984         1.991      1.983
shift 10              1.984         0.305      0.311
shift 100             1.984         0.004      0.004</code></pre>
</div>
</div>
<p>Predicted and actual agree in every row. Fixed effects is flat at 1.984 against a theoretical 1.991, the gap being sampling noise. Plain OLS runs from 1.983 to 0.004 on identical true slopes, partly because the steady half gains weight as it leaves the grand mean, and partly because a second channel opens that is not weighting at all: with the halves at different levels of <span class="math inline">\(x\)</span>, part of the fitted line is a comparison <em>between</em> them. So “the weight is how much <span class="math inline">\(x\)</span> moves” describes the demeaned case; it is exact once unit effects are removed and false in general.</p>
</section><section id="when-it-does-not-matter" class="level3" data-number="9.7.4"><h3 data-number="9.7.4" class="anchored" data-anchor-id="when-it-does-not-matter">
<span class="header-section-number">9.7.4</span> When it does not matter</h3>
<p>Weighting only distorts when the effect is related to the weight. Give every unit its own slope, let units differ in how much <span class="math inline">\(x\)</span> moves, and compare two designs: in (A) the slopes are unrelated to that movement, in (B) the slope is larger where <span class="math inline">\(x\)</span> moves more. Both average near one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">7</span><span class="op">)</span></span>
<span><span class="va">sdX</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">0.2</span>, <span class="fl">3</span><span class="op">)</span>          <span class="co"># how much x moves, unit by unit</span></span>
<span></span>
<span><span class="va">panel</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">b</span><span class="op">)</span> <span class="op">{</span>           <span class="co"># build a panel whose unit slopes are b</span></span>
<span>  <span class="va">h</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">N</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span>,</span>
<span>                    x  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span>, <span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">sdX</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">h</span><span class="op">$</span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">b</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">*</span> <span class="va">h</span><span class="op">$</span><span class="va">x</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, each <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span> <span class="op">*</span> <span class="cn">T</span><span class="op">)</span></span>
<span>  <span class="va">h</span></span>
<span><span class="op">}</span></span>
<span><span class="va">compare</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">h</span>, <span class="va">b</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">w</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/tapply.html">tapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">x</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">id</span>, <span class="va">h</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>, <span class="va">h</span><span class="op">$</span><span class="va">id</span>, <span class="va">sum</span><span class="op">)</span>   <span class="co"># the weights</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`FE estimate`            <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="fu">feols</span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span> <span class="op">|</span> <span class="va">id</span>, <span class="va">h</span><span class="op">)</span><span class="op">)</span><span class="op">[[</span><span class="st">"x"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>    `true slopes, plain avg` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">b</span><span class="op">)</span>,</span>
<span>    `true slopes, weighted`  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">w</span> <span class="op">*</span> <span class="va">b</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">w</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">b1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>             <span class="co"># (A) slopes unrelated to movement</span></span>
<span><span class="va">b2</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">+</span> <span class="fl">0.8</span> <span class="op">*</span> <span class="op">(</span><span class="va">sdX</span> <span class="op">-</span> <span class="fl">1.6</span><span class="op">)</span>      <span class="co"># (B) slopes larger where x moves more</span></span>
<span><span class="va">h1</span> <span class="op">&lt;-</span> <span class="fu">panel</span><span class="op">(</span><span class="va">b1</span><span class="op">)</span>; <span class="va">h2</span> <span class="op">&lt;-</span> <span class="fu">panel</span><span class="op">(</span><span class="va">b2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>`(A) unrelated` <span class="op">=</span> <span class="fu">compare</span><span class="op">(</span><span class="va">h1</span>, <span class="va">b1</span><span class="op">)</span>,</span>
<span>            `(B) aligned`   <span class="op">=</span> <span class="fu">compare</span><span class="op">(</span><span class="va">h2</span>, <span class="va">b2</span><span class="op">)</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       (A) unrelated (B) aligned
FE estimate                   0.9813      1.5338
true slopes, plain avg        0.9716      1.0140
true slopes, weighted         0.9816      1.5422</code></pre>
</div>
</div>
<p>In (A) all three numbers agree to within sampling noise: the weighting is there and costs nothing. In (B) the estimate is 1.53 while the plain average of the true slopes is 1.01, and the weighted average, 1.54, is what the estimator was tracking all along. None of this is a defect — a unit whose <span class="math inline">\(x\)</span> barely moves genuinely carries little information about how <span class="math inline">\(y\)</span> responds, and leaning on the units that do move is efficient.</p>
<p>Słoczyński (<a href="https://doi.org/10.1162/rest_a_00953">2022</a>) makes the same point for a binary treatment (<a href="https://xiangao.github.io/blog_book/ols-ate.html">discussed here</a>): writing <span class="math inline">\(\rho\)</span> for the treated share, the coefficient is <span class="math inline">\((1-\rho)\,\text{ATT} + \rho\,\text{ATU}\)</span>, so the <em>smaller</em> group receives the <em>larger</em> weight. In a sample that is 10% treated the weight on the ATT is <span class="math inline">\(0.9\)</span>, so the coefficient mostly reports the effect on the treated tenth, not the untreated majority. The ATE is the same two numbers with the weights reversed, and the two can be far apart: in a simulation with 8.8% treated, an ATT of 2.39 and an ATU of 0.87, the ATE is 1.00 while OLS returns 2.26.</p>
<p>With homogeneous effects the weighting is harmless. With heterogeneous effects the question is never whether OLS is weighting, only whether we know what it weighted.</p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/econometrics-guide\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./count-data.html" class="pagination-link" aria-label="Count data models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Count data models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./survival.html" class="pagination-link" aria-label="Survival Models">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Survival Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Panel Data Models</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>Panel data are repeated observations on the same "unit" (we call that</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>cross-sectional units) over time.  Panel data models are used since it</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>has advantages over cross-sectional models or time-series models.  The</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>major advantage it has over cross-sectional models is: **Controlling for individual heterogeneity**.</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>For example, Baltagi and Levin (1992) studies cigarette demand across</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>46 states for the years 1963-88.  Consumption is modeled as a function</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>of lagged consumption, price and income.  These variables vary across</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>states and time.  However, there are other variables that may be</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>time-invariant ($z_i$) or individual-invariant ($w_t$).  Examples of $z_i$</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>are religion and, in a panel of adults, completed education.  For example, Utah, as a Mormon state, has</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>very low cigarette demand due to religious reason.  Generally we</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>consider it does not change over time or change very little over time.</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>Examples of $w_t$ include cigarette commercials on national TV or</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>radio.  Panel data models are able to control for individual</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>heterogeneity (or cross-sectional heterogeneity) while cross-sectional</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>models are not.  In many (or most) social science studies, there is</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>"unobserved effects" which is embedded in the error term. In other</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>words, we have "omitted variable" problem.  Without controlling for</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>it, the estimation results are generally biased and inconsistent.</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>Panel data give more informative data, more variability and less</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>collinearity among variables.  Often time series data suffers from</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>multicollinearity, while panel data has more variability from its</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>cross-sectional units.</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>The basic unobserved effects model can be written as:</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>y_{it}={\bf {x_{it} \beta}} + c_i + u_{it}</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>where $i$ indexes "units" (can be people, firms, or households,</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a>etc.), and $t$ indexes time periods.</span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a>Three kinds of regressor appear in this chapter, and it pays to name</span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a>them once.  ${\bf x}_{it}$ varies across units *and* time --- price,</span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a>income, and in most applications the treatment itself.  $z_i$ varies</span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a>across units only, so within a unit it is fixed over time; religion and</span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a>completed education above are the examples.  $w_t$ varies across time</span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a>only, so in any period it is common to every unit; the national TV</span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a>campaign is one.  Which group a variable falls into is what decides</span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a>almost everything that follows, including which coefficients fixed</span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a>effects can estimate and how OLS weights the data.</span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-56"><a href="#cb13-56" aria-hidden="true" tabindex="-1"></a>Instruments do not appear until the panel turns dynamic.  When they do,</span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a>they are written ${\bf Z}$, which is a different object from the</span>
<span id="cb13-58"><a href="#cb13-58" aria-hidden="true" tabindex="-1"></a>time-invariant $z_i$ here --- see the</span>
<span id="cb13-59"><a href="#cb13-59" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Endogeneity</span><span class="co">](endogeneity.qmd)</span>, <span class="co">[</span><span class="ot">GMM</span><span class="co">](gmm.qmd)</span> and</span>
<span id="cb13-60"><a href="#cb13-60" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Dynamic Panel Data</span><span class="co">](dynamic-panel.qmd)</span> chapters.</span>
<span id="cb13-61"><a href="#cb13-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-62"><a href="#cb13-62" aria-hidden="true" tabindex="-1"></a>Comparing to regular cross-sectional models, there is an extra term</span>
<span id="cb13-63"><a href="#cb13-63" aria-hidden="true" tabindex="-1"></a>$c_i$.  $c_i$ can be treated as a random effect or fixed effect.</span>
<span id="cb13-64"><a href="#cb13-64" aria-hidden="true" tabindex="-1"></a>Traditionally it is distinguished by whether it is estimated as a</span>
<span id="cb13-65"><a href="#cb13-65" aria-hidden="true" tabindex="-1"></a>random variable or a parameter.  Modern econometrics tends to</span>
<span id="cb13-66"><a href="#cb13-66" aria-hidden="true" tabindex="-1"></a>distinguish by the correlation between $c_i$ and ${\bf {x_{it}}}$.</span>
<span id="cb13-67"><a href="#cb13-67" aria-hidden="true" tabindex="-1"></a>If there is no correlation between $c_i$ and ${\bf {x_{it}}}$,</span>
<span id="cb13-68"><a href="#cb13-68" aria-hidden="true" tabindex="-1"></a>then it's a random effect; otherwise, it's a fixed effect.</span>
<span id="cb13-69"><a href="#cb13-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-70"><a href="#cb13-70" aria-hidden="true" tabindex="-1"></a>It is true that in some cases it is hard to justify that there is</span>
<span id="cb13-71"><a href="#cb13-71" aria-hidden="true" tabindex="-1"></a>no correlation between $c_i$ and ${\bf {x_{it}}}$, which is one reason</span>
<span id="cb13-72"><a href="#cb13-72" aria-hidden="true" tabindex="-1"></a>that people in economics tend to use fixed-effect models.  However,</span>
<span id="cb13-73"><a href="#cb13-73" aria-hidden="true" tabindex="-1"></a>fixed-effect models have its own limitations.  One of them is: It is</span>
<span id="cb13-74"><a href="#cb13-74" aria-hidden="true" tabindex="-1"></a>hard to justify that ALL the cross-sectional units' characteristics</span>
<span id="cb13-75"><a href="#cb13-75" aria-hidden="true" tabindex="-1"></a>other than those already in the model do not change over time.</span>
<span id="cb13-76"><a href="#cb13-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-77"><a href="#cb13-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## Random Effect Methods</span></span>
<span id="cb13-78"><a href="#cb13-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-79"><a href="#cb13-79" aria-hidden="true" tabindex="-1"></a>A random effect model puts $c_i$ into the error term, then estimate by</span>
<span id="cb13-80"><a href="#cb13-80" aria-hidden="true" tabindex="-1"></a>FGLS (feasible GLS).  Random effect model is sometimes called</span>
<span id="cb13-81"><a href="#cb13-81" aria-hidden="true" tabindex="-1"></a>"Error-components model" since the overall error term is divided into</span>
<span id="cb13-82"><a href="#cb13-82" aria-hidden="true" tabindex="-1"></a>an individual level error term ($c_i$) and individual-time level error</span>
<span id="cb13-83"><a href="#cb13-83" aria-hidden="true" tabindex="-1"></a>term ($u_{it}$).</span>
<span id="cb13-84"><a href="#cb13-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-85"><a href="#cb13-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-86"><a href="#cb13-86" aria-hidden="true" tabindex="-1"></a>Under a random effect model, the variance-covariance matrix of the</span>
<span id="cb13-87"><a href="#cb13-87" aria-hidden="true" tabindex="-1"></a>error term becomes:</span>
<span id="cb13-88"><a href="#cb13-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-89"><a href="#cb13-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-90"><a href="#cb13-90" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-91"><a href="#cb13-91" aria-hidden="true" tabindex="-1"></a>\bf \Omega=</span>
<span id="cb13-92"><a href="#cb13-92" aria-hidden="true" tabindex="-1"></a>\begin{bmatrix} \sigma_{c}^2 + \sigma_u^2 &amp; \sigma_{c}^2 &amp; \cdots &amp; \sigma_{c}^2</span>
<span id="cb13-93"><a href="#cb13-93" aria-hidden="true" tabindex="-1"></a>  <span class="sc">\\</span> \sigma_{c}^2 &amp; \sigma_{c}^2 + \sigma_u^2 &amp; \cdots &amp; \sigma_{c}^2 <span class="sc">\\</span> \vdots &amp;</span>
<span id="cb13-94"><a href="#cb13-94" aria-hidden="true" tabindex="-1"></a>  \vdots &amp; \ddots &amp; \vdots <span class="sc">\\</span> \sigma_{c}^2  &amp; \sigma_{c}^2  &amp; \cdots &amp; \sigma_{c}^2 + \sigma_u^2</span>
<span id="cb13-95"><a href="#cb13-95" aria-hidden="true" tabindex="-1"></a>\end{bmatrix}</span>
<span id="cb13-96"><a href="#cb13-96" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-97"><a href="#cb13-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-98"><a href="#cb13-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-99"><a href="#cb13-99" aria-hidden="true" tabindex="-1"></a>The random effect estimator is:</span>
<span id="cb13-100"><a href="#cb13-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-101"><a href="#cb13-101" aria-hidden="true" tabindex="-1"></a>$$ \bf \hat \beta_{RE} = (\sum_{i=1}^N X_i' \hat \Omega^{-1} X_i)^{-1} (\sum_{i=1}^N X_i' \hat \Omega^{-1} y_i)$$</span>
<span id="cb13-102"><a href="#cb13-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-103"><a href="#cb13-103" aria-hidden="true" tabindex="-1"></a>It is a special case of GLS.  Before calculating $\hat \beta_{RE}$, $</span>
<span id="cb13-104"><a href="#cb13-104" aria-hidden="true" tabindex="-1"></a>\sigma_{c}^2$ and $ \sigma_{u}^2$ need to be estimated.  This is</span>
<span id="cb13-105"><a href="#cb13-105" aria-hidden="true" tabindex="-1"></a>generally done by using residuals from within and between regressions</span>
<span id="cb13-106"><a href="#cb13-106" aria-hidden="true" tabindex="-1"></a>(the Swamy-Arora method, the default in most software), or from pooled</span>
<span id="cb13-107"><a href="#cb13-107" aria-hidden="true" tabindex="-1"></a>OLS.</span>
<span id="cb13-108"><a href="#cb13-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-109"><a href="#cb13-109" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fixed Effect Methods</span></span>
<span id="cb13-110"><a href="#cb13-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-111"><a href="#cb13-111" aria-hidden="true" tabindex="-1"></a>Random effect methods assume that $c_i$ be orthogonal to $\bf x_{it}$.</span>
<span id="cb13-112"><a href="#cb13-112" aria-hidden="true" tabindex="-1"></a>In many applications, the whole point of using panel data is to allow</span>
<span id="cb13-113"><a href="#cb13-113" aria-hidden="true" tabindex="-1"></a>$c_i$ be correlated with $\bf x_{it}$.  We need fixed-effect models in</span>
<span id="cb13-114"><a href="#cb13-114" aria-hidden="true" tabindex="-1"></a>those cases.</span>
<span id="cb13-115"><a href="#cb13-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-116"><a href="#cb13-116" aria-hidden="true" tabindex="-1"></a>For the same model as in the equation above, the fixed-effect</span>
<span id="cb13-117"><a href="#cb13-117" aria-hidden="true" tabindex="-1"></a>methods try to eliminate $c_i$ using fixed effects transformation, or</span>
<span id="cb13-118"><a href="#cb13-118" aria-hidden="true" tabindex="-1"></a>"within transformation".  The FE transformation is to "de-mean"</span>
<span id="cb13-119"><a href="#cb13-119" aria-hidden="true" tabindex="-1"></a>each observation by subtracting the group mean.  Basically subtracting</span>
<span id="cb13-120"><a href="#cb13-120" aria-hidden="true" tabindex="-1"></a>the group-mean equation below from the unit-level equation above:</span>
<span id="cb13-121"><a href="#cb13-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-122"><a href="#cb13-122" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-123"><a href="#cb13-123" aria-hidden="true" tabindex="-1"></a>\bar y_i={\bf \bar x_i \beta} + c_i + \bar u_i</span>
<span id="cb13-124"><a href="#cb13-124" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-125"><a href="#cb13-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-126"><a href="#cb13-126" aria-hidden="true" tabindex="-1"></a>where $\bar y_i $, etc., means group means.  For example, if we have 50 states</span>
<span id="cb13-127"><a href="#cb13-127" aria-hidden="true" tabindex="-1"></a>with state level data of cigarette consumption across years, then</span>
<span id="cb13-128"><a href="#cb13-128" aria-hidden="true" tabindex="-1"></a>groups means states, and we have 50 group means which are state level</span>
<span id="cb13-129"><a href="#cb13-129" aria-hidden="true" tabindex="-1"></a>average cigarette consumption across years.</span>
<span id="cb13-130"><a href="#cb13-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-131"><a href="#cb13-131" aria-hidden="true" tabindex="-1"></a>The reason for "demeaning" is to remove $c_i$ from final estimation.</span>
<span id="cb13-132"><a href="#cb13-132" aria-hidden="true" tabindex="-1"></a>The "demeaned" regression equation is the final regression used in</span>
<span id="cb13-133"><a href="#cb13-133" aria-hidden="true" tabindex="-1"></a>estimation:</span>
<span id="cb13-134"><a href="#cb13-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-135"><a href="#cb13-135" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-136"><a href="#cb13-136" aria-hidden="true" tabindex="-1"></a>(y_{it}-\bar y_i) = ({\bf x}_{it}-{\bf \bar x}_i)\beta + (u_{it}-\bar u_i).</span>
<span id="cb13-137"><a href="#cb13-137" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-138"><a href="#cb13-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-139"><a href="#cb13-139" aria-hidden="true" tabindex="-1"></a>The unit-specific effect $c_i$ cancels because it is constant over $t$</span>
<span id="cb13-140"><a href="#cb13-140" aria-hidden="true" tabindex="-1"></a>($c_i - \bar c_i = 0$). Writing the within-transformed variables as</span>
<span id="cb13-141"><a href="#cb13-141" aria-hidden="true" tabindex="-1"></a>$\ddot y_{it}=y_{it}-\bar y_i$ and $\ddot{\bf x}_{it}={\bf x}_{it}-{\bf \bar x}_i$,</span>
<span id="cb13-142"><a href="#cb13-142" aria-hidden="true" tabindex="-1"></a>OLS on the demeaned data gives the **fixed-effects (within) estimator**</span>
<span id="cb13-143"><a href="#cb13-143" aria-hidden="true" tabindex="-1"></a>(here ${\bf x}_{it}$ is a $1\times k$ *row* vector, so</span>
<span id="cb13-144"><a href="#cb13-144" aria-hidden="true" tabindex="-1"></a>$\ddot{\bf x}_{it}'\ddot{\bf x}_{it}$ is the $k\times k$ outer product)</span>
<span id="cb13-145"><a href="#cb13-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-146"><a href="#cb13-146" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-147"><a href="#cb13-147" aria-hidden="true" tabindex="-1"></a>\hat\beta_{FE} = \left(\sum_i \sum_t \ddot{\bf x}_{it}'\ddot{\bf x}_{it}\right)^{-1}</span>
<span id="cb13-148"><a href="#cb13-148" aria-hidden="true" tabindex="-1"></a>\sum_i \sum_t \ddot{\bf x}_{it}'\ddot y_{it}.</span>
<span id="cb13-149"><a href="#cb13-149" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-150"><a href="#cb13-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-151"><a href="#cb13-151" aria-hidden="true" tabindex="-1"></a>This is consistent for $\beta$ even when $c_i$ is correlated with</span>
<span id="cb13-152"><a href="#cb13-152" aria-hidden="true" tabindex="-1"></a>${\bf x}_{it}$, which is the key advantage of FE over random effects.</span>
<span id="cb13-153"><a href="#cb13-153" aria-hidden="true" tabindex="-1"></a>The price is that any time-invariant regressor (the $z_i$ above) is also</span>
<span id="cb13-154"><a href="#cb13-154" aria-hidden="true" tabindex="-1"></a>swept out by the demeaning and cannot be estimated. The usual variance</span>
<span id="cb13-155"><a href="#cb13-155" aria-hidden="true" tabindex="-1"></a>estimator is $\hat V(\hat\beta_{FE})=\hat\sigma_u^2(\sum_i\sum_t \ddot{\bf x}_{it}'\ddot{\bf x}_{it})^{-1}$</span>
<span id="cb13-156"><a href="#cb13-156" aria-hidden="true" tabindex="-1"></a>with $\hat\sigma_u^2$ using degrees of freedom $NT-N-k$; in practice one</span>
<span id="cb13-157"><a href="#cb13-157" aria-hidden="true" tabindex="-1"></a>clusters by unit to allow serial correlation within $i$.</span>
<span id="cb13-158"><a href="#cb13-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-159"><a href="#cb13-159" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fixed effects or random effects: the Hausman test</span></span>
<span id="cb13-160"><a href="#cb13-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-161"><a href="#cb13-161" aria-hidden="true" tabindex="-1"></a>Random effects is more efficient (it uses both within and between</span>
<span id="cb13-162"><a href="#cb13-162" aria-hidden="true" tabindex="-1"></a>variation) but is consistent only if $c_i$ is uncorrelated with</span>
<span id="cb13-163"><a href="#cb13-163" aria-hidden="true" tabindex="-1"></a>${\bf x}_{it}$; fixed effects is consistent either way. The Hausman test</span>
<span id="cb13-164"><a href="#cb13-164" aria-hidden="true" tabindex="-1"></a>compares the two estimators:</span>
<span id="cb13-165"><a href="#cb13-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-166"><a href="#cb13-166" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-167"><a href="#cb13-167" aria-hidden="true" tabindex="-1"></a>H = (\hat\beta_{FE}-\hat\beta_{RE})'\,<span class="co">[</span><span class="ot">\hat V(\hat\beta_{FE})-\hat V(\hat\beta_{RE})</span><span class="co">]</span>^{-1}\,(\hat\beta_{FE}-\hat\beta_{RE}) \;\sim\; \chi^2_k</span>
<span id="cb13-168"><a href="#cb13-168" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-169"><a href="#cb13-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-170"><a href="#cb13-170" aria-hidden="true" tabindex="-1"></a>under the null that random effects is consistent. A large $H$ (small</span>
<span id="cb13-171"><a href="#cb13-171" aria-hidden="true" tabindex="-1"></a>$p$-value) favors fixed effects. In R this is <span class="in">`phtest(fe, re)`</span> from the</span>
<span id="cb13-172"><a href="#cb13-172" aria-hidden="true" tabindex="-1"></a><span class="in">`plm`</span> package; in Stata, <span class="in">`hausman fe re`</span>.</span>
<span id="cb13-173"><a href="#cb13-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-174"><a href="#cb13-174" aria-hidden="true" tabindex="-1"></a>**Caveat: this classic form requires RE to be efficient.** The formula above relies on $\hat V(\hat\beta_{FE})-\hat V(\hat\beta_{RE})$ being positive semi-definite, which in turn requires the RE estimator to actually be the *efficient* estimator under the null -- true only under the RE model's homoscedasticity and no-serial-correlation assumptions. If you are using robust or cluster-robust covariance matrices (the usual practice when errors are heteroscedastic or serially correlated), RE is generally no longer efficient, the covariance difference can fail to be positive definite, and the classic Hausman test statistic can be negative or otherwise ill-behaved. In that case, use a regression-based Hausman test instead: augment the RE (or pooled) regression with the within-unit means of the time-varying regressors (Mundlak's approach) or with the demeaned regressors themselves (Wooldridge's regression-based test), and test the added coefficients jointly with a standard (robust) Wald test -- this is valid under heteroscedasticity/clustering and reduces to the same idea as the classic Hausman test under its assumptions.</span>
<span id="cb13-175"><a href="#cb13-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-176"><a href="#cb13-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Collapse to unit means, or keep the long format?</span></span>
<span id="cb13-177"><a href="#cb13-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-178"><a href="#cb13-178" aria-hidden="true" tabindex="-1"></a>A practical question comes up whenever we hold a panel.  Should we</span>
<span id="cb13-179"><a href="#cb13-179" aria-hidden="true" tabindex="-1"></a>average each unit over time and run one regression on the $N$ resulting</span>
<span id="cb13-180"><a href="#cb13-180" aria-hidden="true" tabindex="-1"></a>rows, or keep all $NT$ rows and cluster the standard errors by unit?</span>
<span id="cb13-181"><a href="#cb13-181" aria-hidden="true" tabindex="-1"></a>Many people treat this as a trade-off and assume the long format must</span>
<span id="cb13-182"><a href="#cb13-182" aria-hidden="true" tabindex="-1"></a>carry more information.  It usually does not.  The answer turns entirely</span>
<span id="cb13-183"><a href="#cb13-183" aria-hidden="true" tabindex="-1"></a>on where the regressors live.</span>
<span id="cb13-184"><a href="#cb13-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-185"><a href="#cb13-185" aria-hidden="true" tabindex="-1"></a>Take the case where every regressor is time-invariant, so the model is</span>
<span id="cb13-186"><a href="#cb13-186" aria-hidden="true" tabindex="-1"></a>$y_{it}={\bf z}_i \gamma + c_i + u_{it}$.  With a balanced panel, pooled</span>
<span id="cb13-187"><a href="#cb13-187" aria-hidden="true" tabindex="-1"></a>OLS on the $NT$ rows and OLS on the $N$ unit means give the same</span>
<span id="cb13-188"><a href="#cb13-188" aria-hidden="true" tabindex="-1"></a>$\hat\gamma$.  Not close --- identical.  Random effects returns the same</span>
<span id="cb13-189"><a href="#cb13-189" aria-hidden="true" tabindex="-1"></a>number as well.  Wooldridge (2010) states the reason plainly: because</span>
<span id="cb13-190"><a href="#cb13-190" aria-hidden="true" tabindex="-1"></a>$c_i$ is there, new observations within a unit carry no information</span>
<span id="cb13-191"><a href="#cb13-191" aria-hidden="true" tabindex="-1"></a>about $\gamma$ beyond how they move the unit average $\bar y_i$.  In</span>
<span id="cb13-192"><a href="#cb13-192" aria-hidden="true" tabindex="-1"></a>effect we only have $N$ useful pieces of information.  Averaging</span>
<span id="cb13-193"><a href="#cb13-193" aria-hidden="true" tabindex="-1"></a>discards nothing, because ${\bf z}_i$ was already constant over $t$ and</span>
<span id="cb13-194"><a href="#cb13-194" aria-hidden="true" tabindex="-1"></a>the within variation was never available to $\gamma$ in the first place.</span>
<span id="cb13-195"><a href="#cb13-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-196"><a href="#cb13-196" aria-hidden="true" tabindex="-1"></a>What does differ is the degrees of freedom.  The unit-mean regression</span>
<span id="cb13-197"><a href="#cb13-197" aria-hidden="true" tabindex="-1"></a>uses $N-k$; pooled OLS reports $NT-k$, and that is the mistake.  Moulton</span>
<span id="cb13-198"><a href="#cb13-198" aria-hidden="true" tabindex="-1"></a>(1990) is the classic illustration, and Donald and Lang (2007) show that</span>
<span id="cb13-199"><a href="#cb13-199" aria-hidden="true" tabindex="-1"></a>$t_{N-k}$ is the reference distribution that keeps the size right.</span>
<span id="cb13-200"><a href="#cb13-200" aria-hidden="true" tabindex="-1"></a>Clustering by unit repairs the standard error when $N$ is large, but it</span>
<span id="cb13-201"><a href="#cb13-201" aria-hidden="true" tabindex="-1"></a>does not repair the degrees of freedom when $N$ is small.</span>
<span id="cb13-202"><a href="#cb13-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-203"><a href="#cb13-203" aria-hidden="true" tabindex="-1"></a>Now put a time-varying ${\bf x}_{it}$ into the model.  The two options</span>
<span id="cb13-204"><a href="#cb13-204" aria-hidden="true" tabindex="-1"></a>stop agreeing, and not only for the coefficient on ${\bf x}_{it}$ ---</span>
<span id="cb13-205"><a href="#cb13-205" aria-hidden="true" tabindex="-1"></a>every coefficient moves, the one on ${\bf z}_i$ included.  Averaging to</span>
<span id="cb13-206"><a href="#cb13-206" aria-hidden="true" tabindex="-1"></a>unit means throws away all within variation, so what survives is the</span>
<span id="cb13-207"><a href="#cb13-207" aria-hidden="true" tabindex="-1"></a>between estimator.  Pooled OLS keeps both sources and forces a single</span>
<span id="cb13-208"><a href="#cb13-208" aria-hidden="true" tabindex="-1"></a>coefficient on them, so it returns a variance-weighted average of the</span>
<span id="cb13-209"><a href="#cb13-209" aria-hidden="true" tabindex="-1"></a>within and the between relationship.  The two agree only when the within</span>
<span id="cb13-210"><a href="#cb13-210" aria-hidden="true" tabindex="-1"></a>and between coefficients are equal, which is precisely the null the</span>
<span id="cb13-211"><a href="#cb13-211" aria-hidden="true" tabindex="-1"></a>Hausman test examines.  So this is not a new problem.  It is the</span>
<span id="cb13-212"><a href="#cb13-212" aria-hidden="true" tabindex="-1"></a>FE-versus-RE question in different clothes.</span>
<span id="cb13-213"><a href="#cb13-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-214"><a href="#cb13-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Situation <span class="pp">|</span> Collapsed vs long <span class="pp">|</span></span>
<span id="cb13-215"><a href="#cb13-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb13-216"><a href="#cb13-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> All regressors time-invariant, balanced panel <span class="pp">|</span> Same coefficients; only the degrees of freedom differ <span class="pp">|</span></span>
<span id="cb13-217"><a href="#cb13-217" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Any time-varying regressor <span class="pp">|</span> All coefficients differ, including those on ${\bf z}_i$ <span class="pp">|</span></span>
<span id="cb13-218"><a href="#cb13-218" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Unbalanced panel <span class="pp">|</span> Differ regardless, since pooled OLS weights each unit by $T_i$ <span class="pp">|</span></span>
<span id="cb13-219"><a href="#cb13-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-220"><a href="#cb13-220" aria-hidden="true" tabindex="-1"></a>The reconciliation is Mundlak's device, the same one used above for the</span>
<span id="cb13-221"><a href="#cb13-221" aria-hidden="true" tabindex="-1"></a>regression-based Hausman test.  Add the unit means ${\bf \bar x}_i$ to</span>
<span id="cb13-222"><a href="#cb13-222" aria-hidden="true" tabindex="-1"></a>the long regression alongside ${\bf x}_{it}$, and the within and between</span>
<span id="cb13-223"><a href="#cb13-223" aria-hidden="true" tabindex="-1"></a>variation carry separate coefficients: ${\bf x}_{it}$ picks up the</span>
<span id="cb13-224"><a href="#cb13-224" aria-hidden="true" tabindex="-1"></a>within estimate, ${\bf \bar x}_i$ picks up the *difference* between the</span>
<span id="cb13-225"><a href="#cb13-225" aria-hidden="true" tabindex="-1"></a>between and within estimates, so the two coefficients sum to what the</span>
<span id="cb13-226"><a href="#cb13-226" aria-hidden="true" tabindex="-1"></a>collapsed regression reports.  That second coefficient is the Hausman</span>
<span id="cb13-227"><a href="#cb13-227" aria-hidden="true" tabindex="-1"></a>contrast, and its $t$-statistic is the Hausman test.  We keep the within</span>
<span id="cb13-228"><a href="#cb13-228" aria-hidden="true" tabindex="-1"></a>variation and recover the between answer in one regression.</span>
<span id="cb13-229"><a href="#cb13-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-230"><a href="#cb13-230" aria-hidden="true" tabindex="-1"></a>The useful way to remember it: collapse freely when every regressor is</span>
<span id="cb13-231"><a href="#cb13-231" aria-hidden="true" tabindex="-1"></a>constant within the group, and never when one is not.</span>
<span id="cb13-232"><a href="#cb13-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-233"><a href="#cb13-233" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the long format buys</span></span>
<span id="cb13-234"><a href="#cb13-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-235"><a href="#cb13-235" aria-hidden="true" tabindex="-1"></a>The section above is mostly a warning.  The other side is worth seeing</span>
<span id="cb13-236"><a href="#cb13-236" aria-hidden="true" tabindex="-1"></a>directly, so we simulate panels where we know the truth.  We use</span>
<span id="cb13-237"><a href="#cb13-237" aria-hidden="true" tabindex="-1"></a><span class="in">`fixest`</span> here; in Stata the same regressions are <span class="in">`regress`</span>, <span class="in">`xtreg, be`</span></span>
<span id="cb13-238"><a href="#cb13-238" aria-hidden="true" tabindex="-1"></a>and <span class="in">`xtreg, fe`</span>.</span>
<span id="cb13-239"><a href="#cb13-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-240"><a href="#cb13-240" aria-hidden="true" tabindex="-1"></a><span class="fu">### The equivalence, and where it fails</span></span>
<span id="cb13-241"><a href="#cb13-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-242"><a href="#cb13-242" aria-hidden="true" tabindex="-1"></a>Take 1000 units over 6 periods, one time-invariant regressor $z_i$, and</span>
<span id="cb13-243"><a href="#cb13-243" aria-hidden="true" tabindex="-1"></a>a true $\gamma=2$.</span>
<span id="cb13-244"><a href="#cb13-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-247"><a href="#cb13-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-248"><a href="#cb13-248" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb13-249"><a href="#cb13-249" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">1000</span>; T <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb13-250"><a href="#cb13-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-251"><a href="#cb13-251" aria-hidden="true" tabindex="-1"></a>z   <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N)</span>
<span id="cb13-252"><a href="#cb13-252" aria-hidden="true" tabindex="-1"></a>bal <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="at">each =</span> T), <span class="at">t =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>T, N),</span>
<span id="cb13-253"><a href="#cb13-253" aria-hidden="true" tabindex="-1"></a>                  <span class="at">z  =</span> <span class="fu">rep</span>(z, <span class="at">each =</span> T), <span class="at">c =</span> <span class="fu">rep</span>(<span class="fu">rnorm</span>(N), <span class="at">each =</span> T))</span>
<span id="cb13-254"><a href="#cb13-254" aria-hidden="true" tabindex="-1"></a>bal<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> bal<span class="sc">$</span>z <span class="sc">+</span> bal<span class="sc">$</span>c <span class="sc">+</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T)</span>
<span id="cb13-255"><a href="#cb13-255" aria-hidden="true" tabindex="-1"></a>agg   <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(y, z) <span class="sc">~</span> id, <span class="at">data =</span> bal, <span class="at">FUN =</span> mean)</span>
<span id="cb13-256"><a href="#cb13-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-257"><a href="#cb13-257" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="at">long      =</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> z, bal))[[<span class="st">"z"</span>]],</span>
<span id="cb13-258"><a href="#cb13-258" aria-hidden="true" tabindex="-1"></a>        <span class="at">collapsed =</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> z, agg))[[<span class="st">"z"</span>]]), <span class="at">digits =</span> <span class="dv">12</span>)</span>
<span id="cb13-259"><a href="#cb13-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-260"><a href="#cb13-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-261"><a href="#cb13-261" aria-hidden="true" tabindex="-1"></a>The two agree to every digit printed.  Now break the balance by dropping</span>
<span id="cb13-262"><a href="#cb13-262" aria-hidden="true" tabindex="-1"></a>the later periods for units with high $z_i$, so $T_i$ varies, and varies</span>
<span id="cb13-263"><a href="#cb13-263" aria-hidden="true" tabindex="-1"></a>with the regressor.</span>
<span id="cb13-264"><a href="#cb13-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-267"><a href="#cb13-267" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-268"><a href="#cb13-268" aria-hidden="true" tabindex="-1"></a>unb  <span class="ot">&lt;-</span> bal[<span class="sc">!</span>(bal<span class="sc">$</span>z <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> bal<span class="sc">$</span>t <span class="sc">&gt;</span> <span class="dv">2</span>), ]</span>
<span id="cb13-269"><a href="#cb13-269" aria-hidden="true" tabindex="-1"></a>agg2 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(y, z) <span class="sc">~</span> id, <span class="at">data =</span> unb, <span class="at">FUN =</span> mean)</span>
<span id="cb13-270"><a href="#cb13-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-271"><a href="#cb13-271" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="at">long      =</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> z, unb))[[<span class="st">"z"</span>]],</span>
<span id="cb13-272"><a href="#cb13-272" aria-hidden="true" tabindex="-1"></a>        <span class="at">collapsed =</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> z, agg2))[[<span class="st">"z"</span>]]), <span class="at">digits =</span> <span class="dv">12</span>)</span>
<span id="cb13-273"><a href="#cb13-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-274"><a href="#cb13-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-275"><a href="#cb13-275" aria-hidden="true" tabindex="-1"></a>They no longer agree.  Pooled OLS weights each unit by $T_i$; the</span>
<span id="cb13-276"><a href="#cb13-276" aria-hidden="true" tabindex="-1"></a>collapsed regression counts each unit once.  Neither is wrong --- they</span>
<span id="cb13-277"><a href="#cb13-277" aria-hidden="true" tabindex="-1"></a>answer different questions, and we should know which one we asked.  That</span>
<span id="cb13-278"><a href="#cb13-278" aria-hidden="true" tabindex="-1"></a>$T_i$ is a special case of a general rule, set out in the next section.</span>
<span id="cb13-279"><a href="#cb13-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-280"><a href="#cb13-280" aria-hidden="true" tabindex="-1"></a><span class="fu">### What collapsing costs</span></span>
<span id="cb13-281"><a href="#cb13-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-282"><a href="#cb13-282" aria-hidden="true" tabindex="-1"></a>Now the case that matters.  Let $x_{it}$ vary over time and make $c_i$</span>
<span id="cb13-283"><a href="#cb13-283" aria-hidden="true" tabindex="-1"></a>correlated with $\bar x_i$, which is the situation fixed effects exists</span>
<span id="cb13-284"><a href="#cb13-284" aria-hidden="true" tabindex="-1"></a>for.  The truth is $\beta=1$.</span>
<span id="cb13-285"><a href="#cb13-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-288"><a href="#cb13-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-289"><a href="#cb13-289" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N)</span>
<span id="cb13-290"><a href="#cb13-290" aria-hidden="true" tabindex="-1"></a>d  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="at">each =</span> T),</span>
<span id="cb13-291"><a href="#cb13-291" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x  =</span> <span class="fu">rep</span>(mu, <span class="at">each =</span> T) <span class="sc">+</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T),</span>
<span id="cb13-292"><a href="#cb13-292" aria-hidden="true" tabindex="-1"></a>                 <span class="at">c  =</span> <span class="fu">rep</span>(mu <span class="sc">+</span> <span class="fu">rnorm</span>(N), <span class="at">each =</span> T))</span>
<span id="cb13-293"><a href="#cb13-293" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>y    <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">*</span> d<span class="sc">$</span>x <span class="sc">+</span> d<span class="sc">$</span>c <span class="sc">+</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T)</span>
<span id="cb13-294"><a href="#cb13-294" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>xbar <span class="ot">&lt;-</span> <span class="fu">ave</span>(d<span class="sc">$</span>x, d<span class="sc">$</span>id)</span>
<span id="cb13-295"><a href="#cb13-295" aria-hidden="true" tabindex="-1"></a>dagg   <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(y, x) <span class="sc">~</span> id, <span class="at">data =</span> d, <span class="at">FUN =</span> mean)</span>
<span id="cb13-296"><a href="#cb13-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-297"><a href="#cb13-297" aria-hidden="true" tabindex="-1"></a>between <span class="ot">&lt;-</span> <span class="fu">feols</span>(y <span class="sc">~</span> x,        <span class="at">data =</span> dagg)</span>
<span id="cb13-298"><a href="#cb13-298" aria-hidden="true" tabindex="-1"></a>pooled  <span class="ot">&lt;-</span> <span class="fu">feols</span>(y <span class="sc">~</span> x,        <span class="at">data =</span> d, <span class="at">cluster =</span> <span class="sc">~</span>id)</span>
<span id="cb13-299"><a href="#cb13-299" aria-hidden="true" tabindex="-1"></a>within  <span class="ot">&lt;-</span> <span class="fu">feols</span>(y <span class="sc">~</span> x <span class="sc">|</span> id,   <span class="at">data =</span> d)</span>
<span id="cb13-300"><a href="#cb13-300" aria-hidden="true" tabindex="-1"></a>mundlak <span class="ot">&lt;-</span> <span class="fu">feols</span>(y <span class="sc">~</span> x <span class="sc">+</span> xbar, <span class="at">data =</span> d, <span class="at">cluster =</span> <span class="sc">~</span>id)</span>
<span id="cb13-301"><a href="#cb13-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-302"><a href="#cb13-302" aria-hidden="true" tabindex="-1"></a>pull <span class="ot">&lt;-</span> <span class="cf">function</span>(m, v) <span class="fu">c</span>(<span class="fu">coef</span>(m)[[v]], <span class="fu">se</span>(m)[[v]])</span>
<span id="cb13-303"><a href="#cb13-303" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">`</span><span class="at">between (collapsed)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">pull</span>(between, <span class="st">"x"</span>),</span>
<span id="cb13-304"><a href="#cb13-304" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">pooled OLS</span><span class="st">`</span>          <span class="ot">=</span> <span class="fu">pull</span>(pooled,  <span class="st">"x"</span>),</span>
<span id="cb13-305"><a href="#cb13-305" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">within / FE</span><span class="st">`</span>         <span class="ot">=</span> <span class="fu">pull</span>(within,  <span class="st">"x"</span>),</span>
<span id="cb13-306"><a href="#cb13-306" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">Mundlak: x</span><span class="st">`</span>          <span class="ot">=</span> <span class="fu">pull</span>(mundlak, <span class="st">"x"</span>),</span>
<span id="cb13-307"><a href="#cb13-307" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">Mundlak: xbar</span><span class="st">`</span>       <span class="ot">=</span> <span class="fu">pull</span>(mundlak, <span class="st">"xbar"</span>))</span>
<span id="cb13-308"><a href="#cb13-308" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tab) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"estimate"</span>, <span class="st">"std. error"</span>)</span>
<span id="cb13-309"><a href="#cb13-309" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tab, <span class="dv">3</span>)</span>
<span id="cb13-310"><a href="#cb13-310" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-311"><a href="#cb13-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-312"><a href="#cb13-312" aria-hidden="true" tabindex="-1"></a>Read the table down.  The collapsed regression returns about 1.85, badly</span>
<span id="cb13-313"><a href="#cb13-313" aria-hidden="true" tabindex="-1"></a>biased, because it is the between estimator and $\bar x_i$ carries $c_i$</span>
<span id="cb13-314"><a href="#cb13-314" aria-hidden="true" tabindex="-1"></a>with it.  Pooled OLS returns about 1.48 --- closer, since some within</span>
<span id="cb13-315"><a href="#cb13-315" aria-hidden="true" tabindex="-1"></a>variation is mixed in, but still inconsistent.  The within estimator</span>
<span id="cb13-316"><a href="#cb13-316" aria-hidden="true" tabindex="-1"></a>returns about 0.99, and only the long format can compute it: once we</span>
<span id="cb13-317"><a href="#cb13-317" aria-hidden="true" tabindex="-1"></a>collapse there is nothing left to demean.  Mundlak delivers both at</span>
<span id="cb13-318"><a href="#cb13-318" aria-hidden="true" tabindex="-1"></a>once, exactly as described above --- 0.99 on $x_{it}$, 0.85 on</span>
<span id="cb13-319"><a href="#cb13-319" aria-hidden="true" tabindex="-1"></a>$\bar x_i$, and $0.99+0.85$ recovers the between estimate.</span>
<span id="cb13-320"><a href="#cb13-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-321"><a href="#cb13-321" aria-hidden="true" tabindex="-1"></a>So the argument for the long format is not precision.  It is that</span>
<span id="cb13-322"><a href="#cb13-322" aria-hidden="true" tabindex="-1"></a>demeaning, the Hausman comparison, unit-specific slopes, lagged</span>
<span id="cb13-323"><a href="#cb13-323" aria-hidden="true" tabindex="-1"></a>dependent variables and anything else built on within variation stop</span>
<span id="cb13-324"><a href="#cb13-324" aria-hidden="true" tabindex="-1"></a>existing once the panel is collapsed.  Dynamic models are the extreme</span>
<span id="cb13-325"><a href="#cb13-325" aria-hidden="true" tabindex="-1"></a>case, and they get their own chapter,</span>
<span id="cb13-326"><a href="#cb13-326" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Dynamic Panel Data</span><span class="co">](dynamic-panel.qmd)</span>.</span>
<span id="cb13-327"><a href="#cb13-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-328"><a href="#cb13-328" aria-hidden="true" tabindex="-1"></a><span class="fu">## How OLS weights the data</span></span>
<span id="cb13-329"><a href="#cb13-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-330"><a href="#cb13-330" aria-hidden="true" tabindex="-1"></a>Twice above we said OLS weights units unequally: by $T_i$ when the panel</span>
<span id="cb13-331"><a href="#cb13-331" aria-hidden="true" tabindex="-1"></a>is unbalanced, and by variance when it mixes within and between</span>
<span id="cb13-332"><a href="#cb13-332" aria-hidden="true" tabindex="-1"></a>variation.  Neither is a panel-specific quirk.  Both follow from one</span>
<span id="cb13-333"><a href="#cb13-333" aria-hidden="true" tabindex="-1"></a>rule.</span>
<span id="cb13-334"><a href="#cb13-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-335"><a href="#cb13-335" aria-hidden="true" tabindex="-1"></a>Let $V$ be the regressor of interest and $\tilde V$ be $V$ after</span>
<span id="cb13-336"><a href="#cb13-336" aria-hidden="true" tabindex="-1"></a>residualising on every other regressor in the model.  By the</span>
<span id="cb13-337"><a href="#cb13-337" aria-hidden="true" tabindex="-1"></a>Frisch--Waugh--Lovell theorem,</span>
<span id="cb13-338"><a href="#cb13-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-339"><a href="#cb13-339" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-340"><a href="#cb13-340" aria-hidden="true" tabindex="-1"></a>\hat\beta = \frac{\sum_i \sum_t \tilde V_{it}\, y_{it}}</span>
<span id="cb13-341"><a href="#cb13-341" aria-hidden="true" tabindex="-1"></a>                 {\sum_i \sum_t \tilde V_{it}^{2}} .</span>
<span id="cb13-342"><a href="#cb13-342" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-343"><a href="#cb13-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-344"><a href="#cb13-344" aria-hidden="true" tabindex="-1"></a>Be careful what $\tilde V_{it}$ is.  A single observation has no</span>
<span id="cb13-345"><a href="#cb13-345" aria-hidden="true" tabindex="-1"></a>variation of its own --- variation belongs to a collection.  What it has</span>
<span id="cb13-346"><a href="#cb13-346" aria-hidden="true" tabindex="-1"></a>is a **deviation**: how far its regressor sits from what the rest of the</span>
<span id="cb13-347"><a href="#cb13-347" aria-hidden="true" tabindex="-1"></a>model predicts for it.  With only an intercept that is distance from the</span>
<span id="cb13-348"><a href="#cb13-348" aria-hidden="true" tabindex="-1"></a>grand mean; with unit effects it is distance from the unit's own mean.</span>
<span id="cb13-349"><a href="#cb13-349" aria-hidden="true" tabindex="-1"></a>Which mean gets subtracted is the single most consequential detail in</span>
<span id="cb13-350"><a href="#cb13-350" aria-hidden="true" tabindex="-1"></a>this section, and we return to it.</span>
<span id="cb13-351"><a href="#cb13-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-352"><a href="#cb13-352" aria-hidden="true" tabindex="-1"></a><span class="fu">### Two ways to read the coefficient</span></span>
<span id="cb13-353"><a href="#cb13-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-354"><a href="#cb13-354" aria-hidden="true" tabindex="-1"></a>The formula supports two readings.  They describe one estimator and</span>
<span id="cb13-355"><a href="#cb13-355" aria-hidden="true" tabindex="-1"></a>differ in what is being weighted.</span>
<span id="cb13-356"><a href="#cb13-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-357"><a href="#cb13-357" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-358"><a href="#cb13-358" aria-hidden="true" tabindex="-1"></a>\hat\beta = \sum_i \omega_i\, y_i , \quad</span>
<span id="cb13-359"><a href="#cb13-359" aria-hidden="true" tabindex="-1"></a>\omega_i = \frac{\tilde V_i}{\sum_j \tilde V_j^2}</span>
<span id="cb13-360"><a href="#cb13-360" aria-hidden="true" tabindex="-1"></a>\qquad\text{versus}\qquad</span>
<span id="cb13-361"><a href="#cb13-361" aria-hidden="true" tabindex="-1"></a>\hat\beta = \frac{\sum_i w_i\, \beta_i}{\sum_i w_i} , \quad</span>
<span id="cb13-362"><a href="#cb13-362" aria-hidden="true" tabindex="-1"></a>w_i = \tilde V_i V_i .</span>
<span id="cb13-363"><a href="#cb13-363" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-364"><a href="#cb13-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-365"><a href="#cb13-365" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> Weights on outcomes, $\omega_i$ <span class="pp">|</span> Weights on effects, $w_i$ <span class="pp">|</span></span>
<span id="cb13-366"><a href="#cb13-366" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb13-367"><a href="#cb13-367" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Weights what <span class="pp">|</span> the observed $y_i$ <span class="pp">|</span> that observation's own effect $\beta_i$ <span class="pp">|</span></span>
<span id="cb13-368"><a href="#cb13-368" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Sign <span class="pp">|</span> signed, sums to zero <span class="pp">|</span> non-negative <span class="pp">|</span></span>
<span id="cb13-369"><a href="#cb13-369" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Computable <span class="pp">|</span> yes, $y$ is observed <span class="pp">|</span> no, the $\beta_i$ are never seen <span class="pp">|</span></span>
<span id="cb13-370"><a href="#cb13-370" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Holds when <span class="pp">|</span> always, it is algebra <span class="pp">|</span> after writing effects into $y$; the per-unit reading also needs saturation <span class="pp">|</span></span>
<span id="cb13-371"><a href="#cb13-371" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Answers <span class="pp">|</span> which rows drive this number, and does any enter with the wrong sign <span class="pp">|</span> is this the effect I meant, and whose effect is it mostly <span class="pp">|</span></span>
<span id="cb13-372"><a href="#cb13-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-373"><a href="#cb13-373" aria-hidden="true" tabindex="-1"></a>Default to the second.  Nearly every question that motivates the topic</span>
<span id="cb13-374"><a href="#cb13-374" aria-hidden="true" tabindex="-1"></a>--- is my coefficient the average effect, whose effect does it report,</span>
<span id="cb13-375"><a href="#cb13-375" aria-hidden="true" tabindex="-1"></a>why do smaller groups get larger weights --- is a question about the</span>
<span id="cb13-376"><a href="#cb13-376" aria-hidden="true" tabindex="-1"></a>estimand.  Reach for the first when overlap is in doubt and you need to</span>
<span id="cb13-377"><a href="#cb13-377" aria-hidden="true" tabindex="-1"></a>see whether observations enter negatively, which squares cannot show.</span>
<span id="cb13-378"><a href="#cb13-378" aria-hidden="true" tabindex="-1"></a>Both are developed at length in</span>
<span id="cb13-379"><a href="#cb13-379" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Weights in OLS in causal inference</span><span class="co">](https://xiangao.github.io/blog_book/weights-ols.html)</span>.</span>
<span id="cb13-380"><a href="#cb13-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-381"><a href="#cb13-381" aria-hidden="true" tabindex="-1"></a>The square in $w_i$ is derived, not assumed.  Substituting</span>
<span id="cb13-382"><a href="#cb13-382" aria-hidden="true" tabindex="-1"></a>$y_{it}=\beta_i V_{it}+\ldots$ into the numerator gives</span>
<span id="cb13-383"><a href="#cb13-383" aria-hidden="true" tabindex="-1"></a>$\sum_i \beta_i \sum_t \tilde V_{it}V_{it}$, and over the whole sample</span>
<span id="cb13-384"><a href="#cb13-384" aria-hidden="true" tabindex="-1"></a>$\sum \tilde V V=\sum \tilde V^2$ because $\tilde V$ is orthogonal to the</span>
<span id="cb13-385"><a href="#cb13-385" aria-hidden="true" tabindex="-1"></a>fitted part of $V$.  Whether that holds *unit by unit* --- which is what</span>
<span id="cb13-386"><a href="#cb13-386" aria-hidden="true" tabindex="-1"></a>licenses reading $\sum_t \tilde V_{it}^2$ as unit $i$'s weight ---</span>
<span id="cb13-387"><a href="#cb13-387" aria-hidden="true" tabindex="-1"></a>depends on the residualising being done within the unit.  Demeaning</span>
<span id="cb13-388"><a href="#cb13-388" aria-hidden="true" tabindex="-1"></a>delivers it by direct expansion,</span>
<span id="cb13-389"><a href="#cb13-389" aria-hidden="true" tabindex="-1"></a>$\sum_t (V_{it}-\bar V_i)V_{it}=\sum_t V_{it}^2 - T\bar V_i^{\,2}</span>
<span id="cb13-390"><a href="#cb13-390" aria-hidden="true" tabindex="-1"></a>=\sum_t (V_{it}-\bar V_i)^2$, while a coarser control matches only in</span>
<span id="cb13-391"><a href="#cb13-391" aria-hidden="true" tabindex="-1"></a>total.  Hazlett and Shinkre make this the centre of their treatment; the</span>
<span id="cb13-392"><a href="#cb13-392" aria-hidden="true" tabindex="-1"></a>Angrist row below assumes the saturated case.</span>
<span id="cb13-393"><a href="#cb13-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-394"><a href="#cb13-394" aria-hidden="true" tabindex="-1"></a>In general $\sum_t \tilde V_{it}^2$ will not factor into anything</span>
<span id="cb13-395"><a href="#cb13-395" aria-hidden="true" tabindex="-1"></a>tidier, since $\tilde V_{it}$ carries both subscripts even when $V$ does</span>
<span id="cb13-396"><a href="#cb13-396" aria-hidden="true" tabindex="-1"></a>not.  What changes from model to model is whether it happens to</span>
<span id="cb13-397"><a href="#cb13-397" aria-hidden="true" tabindex="-1"></a>simplify.</span>
<span id="cb13-398"><a href="#cb13-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-399"><a href="#cb13-399" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model <span class="pp">|</span> $\sum_t \tilde V_{it}^2$ simplifies to <span class="pp">|</span></span>
<span id="cb13-400"><a href="#cb13-400" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb13-401"><a href="#cb13-401" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $z_i$ alone, nothing else varying within the unit <span class="pp">|</span> $T_i\,\tilde z_i^2$ <span class="pp">|</span></span>
<span id="cb13-402"><a href="#cb13-402" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> a time-varying $x_{it}$, unit effects removed <span class="pp">|</span> $(T-1)\,\widehat{\text{Var}}_i(x)$ <span class="pp">|</span></span>
<span id="cb13-403"><a href="#cb13-403" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> binary $d$ with saturated controls <span class="pp">|</span> $n_x\,\hat d(x)\,(1-\hat d(x))$ <span class="pp">|</span></span>
<span id="cb13-404"><a href="#cb13-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-405"><a href="#cb13-405" aria-hidden="true" tabindex="-1"></a>Add a time-varying $x_{it}$ alongside $z_i$ in the first model and the</span>
<span id="cb13-406"><a href="#cb13-406" aria-hidden="true" tabindex="-1"></a>simplification is gone: residualising $z_i$ on something that moves</span>
<span id="cb13-407"><a href="#cb13-407" aria-hidden="true" tabindex="-1"></a>within the unit makes $\tilde z$ move within the unit too.  The rule</span>
<span id="cb13-408"><a href="#cb13-408" aria-hidden="true" tabindex="-1"></a>survives, the shortcut does not, and the $T_i$ form is the one-regressor</span>
<span id="cb13-409"><a href="#cb13-409" aria-hidden="true" tabindex="-1"></a>special case rather than the general one.  The last row is Angrist</span>
<span id="cb13-410"><a href="#cb13-410" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">1998</span><span class="co">](https://doi.org/10.2307/2998558)</span>), whose strata weights</span>
<span id="cb13-411"><a href="#cb13-411" aria-hidden="true" tabindex="-1"></a>$\hat d(x)(1-\hat d(x))$ are largest where treatment is closest to a</span>
<span id="cb13-412"><a href="#cb13-412" aria-hidden="true" tabindex="-1"></a>coin flip.  Same rule, different regressor.</span>
<span id="cb13-413"><a href="#cb13-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-414"><a href="#cb13-414" aria-hidden="true" tabindex="-1"></a><span class="fu">### When the weighting changes the answer</span></span>
<span id="cb13-415"><a href="#cb13-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-416"><a href="#cb13-416" aria-hidden="true" tabindex="-1"></a>The weighting always happens.  It changes the answer only when the</span>
<span id="cb13-417"><a href="#cb13-417" aria-hidden="true" tabindex="-1"></a>effect is heterogeneous *and* the heterogeneity lines up with the</span>
<span id="cb13-418"><a href="#cb13-418" aria-hidden="true" tabindex="-1"></a>weight.  The claim to check is that a regression does not report *the*</span>
<span id="cb13-419"><a href="#cb13-419" aria-hidden="true" tabindex="-1"></a>effect but a weighted average of the effects, and that these are</span>
<span id="cb13-420"><a href="#cb13-420" aria-hidden="true" tabindex="-1"></a>different numbers.</span>
<span id="cb13-421"><a href="#cb13-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-422"><a href="#cb13-422" aria-hidden="true" tabindex="-1"></a>The individual effects are never observed, so we plant them: give every</span>
<span id="cb13-423"><a href="#cb13-423" aria-hidden="true" tabindex="-1"></a>unit its own slope $\beta_i$, generate $y$ from those slopes, and see</span>
<span id="cb13-424"><a href="#cb13-424" aria-hidden="true" tabindex="-1"></a>which average of the planted slopes the estimate lands on.  In the next</span>
<span id="cb13-425"><a href="#cb13-425" aria-hidden="true" tabindex="-1"></a>chunk only one estimator is run; anything else reported is not an</span>
<span id="cb13-426"><a href="#cb13-426" aria-hidden="true" tabindex="-1"></a>estimate but the planted slopes averaged some way.  Fixed effects is</span>
<span id="cb13-427"><a href="#cb13-427" aria-hidden="true" tabindex="-1"></a>used because in a panel the natural place for heterogeneity is across</span>
<span id="cb13-428"><a href="#cb13-428" aria-hidden="true" tabindex="-1"></a>units, and it is still OLS --- OLS with the unit dummies partialled out.</span>
<span id="cb13-429"><a href="#cb13-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-430"><a href="#cb13-430" aria-hidden="true" tabindex="-1"></a>Start with the extreme case.  Half the units barely move and have a true</span>
<span id="cb13-431"><a href="#cb13-431" aria-hidden="true" tabindex="-1"></a>slope of zero; the other half move a great deal and have a true slope of</span>
<span id="cb13-432"><a href="#cb13-432" aria-hidden="true" tabindex="-1"></a>two.  The average unit's slope is one.</span>
<span id="cb13-433"><a href="#cb13-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-436"><a href="#cb13-436" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-437"><a href="#cb13-437" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb13-438"><a href="#cb13-438" aria-hidden="true" tabindex="-1"></a>half <span class="ot">&lt;-</span> N <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb13-439"><a href="#cb13-439" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id   =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="at">each =</span> T),</span>
<span id="cb13-440"><a href="#cb13-440" aria-hidden="true" tabindex="-1"></a>                <span class="at">move =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="fl">0.2</span>, half), <span class="fu">rep</span>(<span class="dv">3</span>, half)), <span class="at">each =</span> T),</span>
<span id="cb13-441"><a href="#cb13-441" aria-hidden="true" tabindex="-1"></a>                <span class="at">b    =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">0</span>,   half), <span class="fu">rep</span>(<span class="dv">2</span>, half)), <span class="at">each =</span> T))</span>
<span id="cb13-442"><a href="#cb13-442" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T, <span class="dv">0</span>, g<span class="sc">$</span>move)</span>
<span id="cb13-443"><a href="#cb13-443" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>y <span class="ot">&lt;-</span> g<span class="sc">$</span>b <span class="sc">*</span> g<span class="sc">$</span>x <span class="sc">+</span> <span class="fu">rep</span>(<span class="fu">rnorm</span>(N), <span class="at">each =</span> T) <span class="sc">+</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T)</span>
<span id="cb13-444"><a href="#cb13-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-445"><a href="#cb13-445" aria-hidden="true" tabindex="-1"></a>wg <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="fu">resid</span>(<span class="fu">feols</span>(x <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> id, g))<span class="sc">^</span><span class="dv">2</span>, g<span class="sc">$</span>id, sum)</span>
<span id="cb13-446"><a href="#cb13-446" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">value =</span> <span class="fu">c</span>(</span>
<span id="cb13-447"><a href="#cb13-447" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">average of the two true slopes</span><span class="st">`</span>      <span class="ot">=</span> <span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>)),</span>
<span id="cb13-448"><a href="#cb13-448" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">FE estimate</span><span class="st">`</span>                         <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> x <span class="sc">|</span> id, g))[[<span class="st">"x"</span>]],</span>
<span id="cb13-449"><a href="#cb13-449" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">weight held by the steady half (%)</span><span class="st">`</span>  <span class="ot">=</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(wg[<span class="dv">1</span><span class="sc">:</span>half]) <span class="sc">/</span> <span class="fu">sum</span>(wg))), <span class="dv">3</span>)</span>
<span id="cb13-450"><a href="#cb13-450" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-451"><a href="#cb13-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-452"><a href="#cb13-452" aria-hidden="true" tabindex="-1"></a>The average slope is one and the regression reports 1.98, because the</span>
<span id="cb13-453"><a href="#cb13-453" aria-hidden="true" tabindex="-1"></a>five hundred steady units hold under half of one percent of the weight.</span>
<span id="cb13-454"><a href="#cb13-454" aria-hidden="true" tabindex="-1"></a>Their six observations sit almost on top of their own unit mean ---</span>
<span id="cb13-455"><a href="#cb13-455" aria-hidden="true" tabindex="-1"></a>this regression carries unit effects, so that is the relevant deviation</span>
<span id="cb13-456"><a href="#cb13-456" aria-hidden="true" tabindex="-1"></a>--- and squaring puts them nowhere in the sum.  Nothing has gone wrong</span>
<span id="cb13-457"><a href="#cb13-457" aria-hidden="true" tabindex="-1"></a>in the arithmetic.  The units with a slope of zero were never really in</span>
<span id="cb13-458"><a href="#cb13-458" aria-hidden="true" tabindex="-1"></a>the regression.</span>
<span id="cb13-459"><a href="#cb13-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-460"><a href="#cb13-460" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which mean, and why it matters</span></span>
<span id="cb13-461"><a href="#cb13-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-462"><a href="#cb13-462" aria-hidden="true" tabindex="-1"></a>That result is about the *within-unit* deviation.  Plain OLS uses</span>
<span id="cb13-463"><a href="#cb13-463" aria-hidden="true" tabindex="-1"></a>distance from the grand mean instead, and the two coincided above only</span>
<span id="cb13-464"><a href="#cb13-464" aria-hidden="true" tabindex="-1"></a>because both halves were built around zero.  Separate them and the</span>
<span id="cb13-465"><a href="#cb13-465" aria-hidden="true" tabindex="-1"></a>algebra says exactly what happens.</span>
<span id="cb13-466"><a href="#cb13-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-467"><a href="#cb13-467" aria-hidden="true" tabindex="-1"></a>Take two equally sized groups with means $\mu_g$, within-group variances</span>
<span id="cb13-468"><a href="#cb13-468" aria-hidden="true" tabindex="-1"></a>$\sigma_g^2$, slopes $\beta_g$ and group mean outcomes $\bar y_g$.  The</span>
<span id="cb13-469"><a href="#cb13-469" aria-hidden="true" tabindex="-1"></a>law of total covariance splits $\text{Cov}(x,y)$ and $\text{Var}(x)$</span>
<span id="cb13-470"><a href="#cb13-470" aria-hidden="true" tabindex="-1"></a>into within and between parts, giving</span>
<span id="cb13-471"><a href="#cb13-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-472"><a href="#cb13-472" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-473"><a href="#cb13-473" aria-hidden="true" tabindex="-1"></a>\text{plim}\;\hat\beta_{OLS}</span>
<span id="cb13-474"><a href="#cb13-474" aria-hidden="true" tabindex="-1"></a>= \frac{\tfrac12<span class="sc">\!</span>\left(\beta_1\sigma_1^2+\beta_2\sigma_2^2\right)</span>
<span id="cb13-475"><a href="#cb13-475" aria-hidden="true" tabindex="-1"></a><span class="ss">        + </span>\tfrac14\,\Delta\mu\,\Delta\bar y}</span>
<span id="cb13-476"><a href="#cb13-476" aria-hidden="true" tabindex="-1"></a>       {\tfrac12<span class="sc">\!</span>\left(\sigma_1^2+\sigma_2^2\right)</span>
<span id="cb13-477"><a href="#cb13-477" aria-hidden="true" tabindex="-1"></a><span class="ss">        + </span>\tfrac14\,\Delta\mu^{2}} ,</span>
<span id="cb13-478"><a href="#cb13-478" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb13-479"><a href="#cb13-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-480"><a href="#cb13-480" aria-hidden="true" tabindex="-1"></a>with $\Delta\mu=\mu_1-\mu_2$ and $\Delta\bar y=\bar y_1-\bar y_2$: a</span>
<span id="cb13-481"><a href="#cb13-481" aria-hidden="true" tabindex="-1"></a>variance-weighted average of</span>
<span id="cb13-482"><a href="#cb13-482" aria-hidden="true" tabindex="-1"></a>$\beta_{within}=(\beta_1\sigma_1^2+\beta_2\sigma_2^2)/(\sigma_1^2+\sigma_2^2)$</span>
<span id="cb13-483"><a href="#cb13-483" aria-hidden="true" tabindex="-1"></a>and $\beta_{between}=\Delta\bar y/\Delta\mu$, weighted by the within</span>
<span id="cb13-484"><a href="#cb13-484" aria-hidden="true" tabindex="-1"></a>variance $\tfrac12(\sigma_1^2+\sigma_2^2)$ and the between variance</span>
<span id="cb13-485"><a href="#cb13-485" aria-hidden="true" tabindex="-1"></a>$\tfrac14\Delta\mu^2$.</span>
<span id="cb13-486"><a href="#cb13-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-487"><a href="#cb13-487" aria-hidden="true" tabindex="-1"></a>Everything follows without running anything.  Fixed effects estimates</span>
<span id="cb13-488"><a href="#cb13-488" aria-hidden="true" tabindex="-1"></a>$\beta_{within}$, here $(0\cdot 0.04 + 2\cdot 9)/9.04 = 1.991$, which</span>
<span id="cb13-489"><a href="#cb13-489" aria-hidden="true" tabindex="-1"></a>involves no $\mu_g$ --- so parking a group anywhere cannot move it.</span>
<span id="cb13-490"><a href="#cb13-490" aria-hidden="true" tabindex="-1"></a>Plain OLS also carries $\beta_{between}$, which is zero in this design</span>
<span id="cb13-491"><a href="#cb13-491" aria-hidden="true" tabindex="-1"></a>because the steady slope and both intercepts are zero, leaving the two</span>
<span id="cb13-492"><a href="#cb13-492" aria-hidden="true" tabindex="-1"></a>group means at the same height.  As $\Delta\mu$ grows, the between</span>
<span id="cb13-493"><a href="#cb13-493" aria-hidden="true" tabindex="-1"></a>weight $\tfrac14\Delta\mu^2$ swamps the fixed within weight of $4.52$</span>
<span id="cb13-494"><a href="#cb13-494" aria-hidden="true" tabindex="-1"></a>and the coefficient is dragged from $1.991$ toward zero like</span>
<span id="cb13-495"><a href="#cb13-495" aria-hidden="true" tabindex="-1"></a>$9/(4.52+\Delta\mu^2/4)$, the numerator being</span>
<span id="cb13-496"><a href="#cb13-496" aria-hidden="true" tabindex="-1"></a>$\tfrac12(\beta_1\sigma_1^2+\beta_2\sigma_2^2)=9$.  The simulation is a</span>
<span id="cb13-497"><a href="#cb13-497" aria-hidden="true" tabindex="-1"></a>check on that, not the source of it.</span>
<span id="cb13-498"><a href="#cb13-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-501"><a href="#cb13-501" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-502"><a href="#cb13-502" aria-hidden="true" tabindex="-1"></a>b_within <span class="ot">&lt;-</span> (<span class="dv">0</span> <span class="sc">*</span> <span class="fl">0.2</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">3</span><span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (<span class="fl">0.2</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span><span class="sc">^</span><span class="dv">2</span>)   <span class="co"># variance-weighted slope</span></span>
<span id="cb13-503"><a href="#cb13-503" aria-hidden="true" tabindex="-1"></a>V_within <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> (<span class="fl">0.2</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span><span class="sc">^</span><span class="dv">2</span>)                     <span class="co"># within variance</span></span>
<span id="cb13-504"><a href="#cb13-504" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="cf">function</span>(shift)                        <span class="co"># beta_between = 0 here</span></span>
<span id="cb13-505"><a href="#cb13-505" aria-hidden="true" tabindex="-1"></a>  V_within <span class="sc">*</span> b_within <span class="sc">/</span> (V_within <span class="sc">+</span> <span class="fl">0.25</span> <span class="sc">*</span> shift<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-506"><a href="#cb13-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-507"><a href="#cb13-507" aria-hidden="true" tabindex="-1"></a>park <span class="ot">&lt;-</span> <span class="cf">function</span>(shift) {</span>
<span id="cb13-508"><a href="#cb13-508" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb13-509"><a href="#cb13-509" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T, <span class="dv">0</span>, g<span class="sc">$</span>move) <span class="sc">+</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="fu">rep</span>(shift, half), <span class="fu">rep</span>(<span class="dv">0</span>, half)), <span class="at">each =</span> T)</span>
<span id="cb13-510"><a href="#cb13-510" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> g<span class="sc">$</span>b <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rep</span>(<span class="fu">rnorm</span>(N), <span class="at">each =</span> T) <span class="sc">+</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T)</span>
<span id="cb13-511"><a href="#cb13-511" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> g<span class="sc">$</span>id, <span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb13-512"><a href="#cb13-512" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">`</span><span class="at">FE (theory 1.991)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> x <span class="sc">|</span> id, d))[[<span class="st">"x"</span>]],</span>
<span id="cb13-513"><a href="#cb13-513" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">OLS predicted</span><span class="st">`</span>     <span class="ot">=</span> <span class="fu">predicted</span>(shift),</span>
<span id="cb13-514"><a href="#cb13-514" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">OLS actual</span><span class="st">`</span>        <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x, d))[[<span class="st">"x"</span>]])</span>
<span id="cb13-515"><a href="#cb13-515" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-516"><a href="#cb13-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-517"><a href="#cb13-517" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">t</span>(<span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">`</span><span class="at">shift 0</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">`</span><span class="at">shift 10</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">10</span>, <span class="st">`</span><span class="at">shift 100</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">100</span>), park)), <span class="dv">3</span>)</span>
<span id="cb13-518"><a href="#cb13-518" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-519"><a href="#cb13-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-520"><a href="#cb13-520" aria-hidden="true" tabindex="-1"></a>Predicted and actual agree in every row.  Fixed effects is flat at 1.984</span>
<span id="cb13-521"><a href="#cb13-521" aria-hidden="true" tabindex="-1"></a>against a theoretical 1.991, the gap being sampling noise.  Plain OLS</span>
<span id="cb13-522"><a href="#cb13-522" aria-hidden="true" tabindex="-1"></a>runs from 1.983 to 0.004 on identical true slopes, partly because the</span>
<span id="cb13-523"><a href="#cb13-523" aria-hidden="true" tabindex="-1"></a>steady half gains weight as it leaves the grand mean, and partly because</span>
<span id="cb13-524"><a href="#cb13-524" aria-hidden="true" tabindex="-1"></a>a second channel opens that is not weighting at all: with the halves at</span>
<span id="cb13-525"><a href="#cb13-525" aria-hidden="true" tabindex="-1"></a>different levels of $x$, part of the fitted line is a comparison</span>
<span id="cb13-526"><a href="#cb13-526" aria-hidden="true" tabindex="-1"></a>*between* them.  So "the weight is how much $x$ moves" describes the</span>
<span id="cb13-527"><a href="#cb13-527" aria-hidden="true" tabindex="-1"></a>demeaned case; it is exact once unit effects are removed and false in</span>
<span id="cb13-528"><a href="#cb13-528" aria-hidden="true" tabindex="-1"></a>general.</span>
<span id="cb13-529"><a href="#cb13-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-530"><a href="#cb13-530" aria-hidden="true" tabindex="-1"></a><span class="fu">### When it does not matter</span></span>
<span id="cb13-531"><a href="#cb13-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-532"><a href="#cb13-532" aria-hidden="true" tabindex="-1"></a>Weighting only distorts when the effect is related to the weight.  Give</span>
<span id="cb13-533"><a href="#cb13-533" aria-hidden="true" tabindex="-1"></a>every unit its own slope, let units differ in how much $x$ moves, and</span>
<span id="cb13-534"><a href="#cb13-534" aria-hidden="true" tabindex="-1"></a>compare two designs: in (A) the slopes are unrelated to that movement,</span>
<span id="cb13-535"><a href="#cb13-535" aria-hidden="true" tabindex="-1"></a>in (B) the slope is larger where $x$ moves more.  Both average near one.</span>
<span id="cb13-536"><a href="#cb13-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-539"><a href="#cb13-539" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-540"><a href="#cb13-540" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb13-541"><a href="#cb13-541" aria-hidden="true" tabindex="-1"></a>sdX <span class="ot">&lt;-</span> <span class="fu">runif</span>(N, <span class="fl">0.2</span>, <span class="dv">3</span>)          <span class="co"># how much x moves, unit by unit</span></span>
<span id="cb13-542"><a href="#cb13-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-543"><a href="#cb13-543" aria-hidden="true" tabindex="-1"></a>panel <span class="ot">&lt;-</span> <span class="cf">function</span>(b) {           <span class="co"># build a panel whose unit slopes are b</span></span>
<span id="cb13-544"><a href="#cb13-544" aria-hidden="true" tabindex="-1"></a>  h   <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="at">each =</span> T),</span>
<span id="cb13-545"><a href="#cb13-545" aria-hidden="true" tabindex="-1"></a>                    <span class="at">x  =</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T, <span class="dv">0</span>, <span class="fu">rep</span>(sdX, <span class="at">each =</span> T)))</span>
<span id="cb13-546"><a href="#cb13-546" aria-hidden="true" tabindex="-1"></a>  h<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">rep</span>(b, <span class="at">each =</span> T) <span class="sc">*</span> h<span class="sc">$</span>x <span class="sc">+</span> <span class="fu">rep</span>(<span class="fu">rnorm</span>(N), <span class="at">each =</span> T) <span class="sc">+</span> <span class="fu">rnorm</span>(N <span class="sc">*</span> T)</span>
<span id="cb13-547"><a href="#cb13-547" aria-hidden="true" tabindex="-1"></a>  h</span>
<span id="cb13-548"><a href="#cb13-548" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-549"><a href="#cb13-549" aria-hidden="true" tabindex="-1"></a>compare <span class="ot">&lt;-</span> <span class="cf">function</span>(h, b) {</span>
<span id="cb13-550"><a href="#cb13-550" aria-hidden="true" tabindex="-1"></a>  w <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="fu">resid</span>(<span class="fu">feols</span>(x <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> id, h))<span class="sc">^</span><span class="dv">2</span>, h<span class="sc">$</span>id, sum)   <span class="co"># the weights</span></span>
<span id="cb13-551"><a href="#cb13-551" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">`</span><span class="at">FE estimate</span><span class="st">`</span>            <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">feols</span>(y <span class="sc">~</span> x <span class="sc">|</span> id, h))[[<span class="st">"x"</span>]],</span>
<span id="cb13-552"><a href="#cb13-552" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">true slopes, plain avg</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(b),</span>
<span id="cb13-553"><a href="#cb13-553" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">true slopes, weighted</span><span class="st">`</span>  <span class="ot">=</span> <span class="fu">sum</span>(w <span class="sc">*</span> b) <span class="sc">/</span> <span class="fu">sum</span>(w))</span>
<span id="cb13-554"><a href="#cb13-554" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-555"><a href="#cb13-555" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-556"><a href="#cb13-556" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="dv">1</span>, <span class="dv">1</span>)             <span class="co"># (A) slopes unrelated to movement</span></span>
<span id="cb13-557"><a href="#cb13-557" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">0.8</span> <span class="sc">*</span> (sdX <span class="sc">-</span> <span class="fl">1.6</span>)      <span class="co"># (B) slopes larger where x moves more</span></span>
<span id="cb13-558"><a href="#cb13-558" aria-hidden="true" tabindex="-1"></a>h1 <span class="ot">&lt;-</span> <span class="fu">panel</span>(b1); h2 <span class="ot">&lt;-</span> <span class="fu">panel</span>(b2)</span>
<span id="cb13-559"><a href="#cb13-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-560"><a href="#cb13-560" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="st">`</span><span class="at">(A) unrelated</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">compare</span>(h1, b1),</span>
<span id="cb13-561"><a href="#cb13-561" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">(B) aligned</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">compare</span>(h2, b2)), <span class="dv">4</span>)</span>
<span id="cb13-562"><a href="#cb13-562" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-563"><a href="#cb13-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-564"><a href="#cb13-564" aria-hidden="true" tabindex="-1"></a>In (A) all three numbers agree to within sampling noise: the weighting</span>
<span id="cb13-565"><a href="#cb13-565" aria-hidden="true" tabindex="-1"></a>is there and costs nothing.  In (B) the estimate is 1.53 while the plain</span>
<span id="cb13-566"><a href="#cb13-566" aria-hidden="true" tabindex="-1"></a>average of the true slopes is 1.01, and the weighted average, 1.54, is</span>
<span id="cb13-567"><a href="#cb13-567" aria-hidden="true" tabindex="-1"></a>what the estimator was tracking all along.  None of this is a defect ---</span>
<span id="cb13-568"><a href="#cb13-568" aria-hidden="true" tabindex="-1"></a>a unit whose $x$ barely moves genuinely carries little information about</span>
<span id="cb13-569"><a href="#cb13-569" aria-hidden="true" tabindex="-1"></a>how $y$ responds, and leaning on the units that do move is efficient.</span>
<span id="cb13-570"><a href="#cb13-570" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-571"><a href="#cb13-571" aria-hidden="true" tabindex="-1"></a>Słoczyński (<span class="co">[</span><span class="ot">2022</span><span class="co">](https://doi.org/10.1162/rest_a_00953)</span>) makes the same</span>
<span id="cb13-572"><a href="#cb13-572" aria-hidden="true" tabindex="-1"></a>point for a binary treatment</span>
<span id="cb13-573"><a href="#cb13-573" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">discussed here</span><span class="co">](https://xiangao.github.io/blog_book/ols-ate.html)</span>):</span>
<span id="cb13-574"><a href="#cb13-574" aria-hidden="true" tabindex="-1"></a>writing $\rho$ for the treated share, the coefficient is</span>
<span id="cb13-575"><a href="#cb13-575" aria-hidden="true" tabindex="-1"></a>$(1-\rho)\,\text{ATT} + \rho\,\text{ATU}$, so the *smaller* group</span>
<span id="cb13-576"><a href="#cb13-576" aria-hidden="true" tabindex="-1"></a>receives the *larger* weight.  In a sample that is 10% treated the</span>
<span id="cb13-577"><a href="#cb13-577" aria-hidden="true" tabindex="-1"></a>weight on the ATT is $0.9$, so the coefficient mostly reports the effect</span>
<span id="cb13-578"><a href="#cb13-578" aria-hidden="true" tabindex="-1"></a>on the treated tenth, not the untreated majority.  The ATE is the same</span>
<span id="cb13-579"><a href="#cb13-579" aria-hidden="true" tabindex="-1"></a>two numbers with the weights reversed, and the two can be far apart: in</span>
<span id="cb13-580"><a href="#cb13-580" aria-hidden="true" tabindex="-1"></a>a simulation with 8.8% treated, an ATT of 2.39 and an ATU of 0.87, the</span>
<span id="cb13-581"><a href="#cb13-581" aria-hidden="true" tabindex="-1"></a>ATE is 1.00 while OLS returns 2.26.</span>
<span id="cb13-582"><a href="#cb13-582" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-583"><a href="#cb13-583" aria-hidden="true" tabindex="-1"></a>With homogeneous effects the weighting is harmless.  With heterogeneous</span>
<span id="cb13-584"><a href="#cb13-584" aria-hidden="true" tabindex="-1"></a>effects the question is never whether OLS is weighting, only whether we</span>
<span id="cb13-585"><a href="#cb13-585" aria-hidden="true" tabindex="-1"></a>know what it weighted.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/xiangao/econometrics-guide/edit/main/panel-data.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/econometrics-guide/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>