{
  "hash": "cdc614b87761c9740fb5a77b90d7eeca",
  "result": {
    "engine": "knitr",
    "markdown": "# Panel Data Models\n\n\n\n## Background\n\nPanel data are repeated observations on the same \"unit\" (we call that\ncross-sectional units) over time.  Panel data models are used since it\nhas advantages over cross-sectional models or time-series models.  The\nmajor advantage it has over cross-sectional models is: **Controlling for individual heterogeneity**.\n\nFor example, Baltagi and Levin (1992) studies cigarette demand across\n46 states for the years 1963-88.  Consumption is modeled as a function\nof lagged consumption, price and income.  These variables vary across\nstates and time.  However, there are other variables that may be\ntime-invariant ($W_i$) or individual-invariant ($W_t$).  Examples of $W_i$\nare religion and, in a panel of adults, completed education.  For example, Utah, as a Mormon state, has\nvery low cigarette demand due to religious reason.  Generally we\nconsider it does not change over time or change very little over time.\nExamples of $W_t$ include cigarette commercials on national TV or\nradio.  Panel data models are able to control for individual\nheterogeneity (or cross-sectional heterogeneity) while cross-sectional\nmodels are not.  In many (or most) social science studies, there is\n\"unobserved effects\" which is embedded in the error term. In other\nwords, we have \"omitted variable\" problem.  Without controlling for\nit, the estimation results are generally biased and inconsistent.\n\nPanel data give more informative data, more variability and less\ncollinearity among variables.  Often time series data suffers from\nmulticollinearity, while panel data has more variability from its\ncross-sectional units.\n\nThe basic unobserved effects model can be written as:\n$$\ny_{it}={\\bf {X_{it} \\beta}} + c_i + u_{it}\n$$\n\nwhere $i$ indexes \"units\" (can be people, firms, or households,\netc.), and $t$ indexes time periods.\n\nNotation in this chapter follows the usual roles.  ${\\bf X}$ collects\nthe regressors we care about, ${\\bf W}$ the other covariates, and\n${\\bf Z}$ the instruments.  Subscripts carry the variation rather than\nthe role: $X_{it}$ moves across both units and time, $X_i$ only across\nunits, $X_t$ only across time.  Instruments play no part until the\npanel turns dynamic --- see the [Endogeneity](endogeneity.qmd),\n[GMM](gmm.qmd) and [Dynamic Panel Data](dynamic-panel.qmd) chapters.\n\nComparing to regular cross-sectional models, there is an extra term\n$c_i$.  $c_i$ can be treated as a random effect or fixed effect.\nTraditionally it is distinguished by whether it is estimated as a\nrandom variable or a parameter.  Modern econometrics tends to\ndistinguish by the correlation between $c_i$ and ${\\bf {X_{it}}}$.\nIf there is no correlation between $c_i$ and ${\\bf {X_{it}}}$,\nthen it's a random effect; otherwise, it's a fixed effect.\n\nIt is true that in some cases it is hard to justify that there is\nno correlation between $c_i$ and ${\\bf {X_{it}}}$, which is one reason\nthat people in economics tend to use fixed-effect models.  However,\nfixed-effect models have its own limitations.  One of them is: It is\nhard to justify that ALL the cross-sectional units' characteristics\nother than those already in the model do not change over time.\n\n## Random Effect Methods\n\nA random effect model puts $c_i$ into the error term, then estimate by\nFGLS (feasible GLS).  Random effect model is sometimes called\n\"Error-components model\" since the overall error term is divided into\nan individual level error term ($c_i$) and individual-time level error\nterm ($u_{it}$).\n\n\nUnder a random effect model, the variance-covariance matrix of the\nerror term becomes:\n\n\n$$\n\\bf \\Omega=\n\\begin{bmatrix} \\sigma_{c}^2 + \\sigma_u^2 & \\sigma_{c}^2 & \\cdots & \\sigma_{c}^2\n  \\\\ \\sigma_{c}^2 & \\sigma_{c}^2 + \\sigma_u^2 & \\cdots & \\sigma_{c}^2 \\\\ \\vdots &\n  \\vdots & \\ddots & \\vdots \\\\ \\sigma_{c}^2  & \\sigma_{c}^2  & \\cdots & \\sigma_{c}^2 + \\sigma_u^2\n\\end{bmatrix}\n$$\n\n\nThe random effect estimator is:\n\n$$ \\bf \\hat \\beta_{RE} = (\\sum_{i=1}^N X_i' \\hat \\Omega^{-1} X_i)^{-1} (\\sum_{i=1}^N X_i' \\hat \\Omega^{-1} y_i)$$\n\nIt is a special case of GLS.  Before calculating $\\hat \\beta_{RE}$, $\n\\sigma_{c}^2$ and $ \\sigma_{u}^2$ need to be estimated.  This is\ngenerally done by using residuals from within and between regressions\n(the Swamy-Arora method, the default in most software), or from pooled\nOLS.\n\n## Fixed Effect Methods\n\nRandom effect methods assume that $c_i$ be orthogonal to $\\bf X_{it}$.\nIn many applications, the whole point of using panel data is to allow\n$c_i$ be correlated with $\\bf X_{it}$.  We need fixed-effect models in\nthose cases.\n\nFor the same model as in the equation above, the fixed-effect\nmethods try to eliminate $c_i$ using fixed effects transformation, or\n\"within transformation\".  The FE transformation is to \"de-mean\"\neach observation by subtracting the group mean.  Basically subtracting\nthe group-mean equation below from the unit-level equation above:\n\n$$\n\\bar y_i={\\bf \\bar X_i \\beta} + c_i + \\bar u_i\n$$\n\nwhere $\\bar y_i $, etc., means group means.  For example, if we have 50 states\nwith state level data of cigarette consumption across years, then\ngroups means states, and we have 50 group means which are state level\naverage cigarette consumption across years.\n\nThe reason for \"demeaning\" is to remove $c_i$ from final estimation.\nThe \"demeaned\" regression equation is the final regression used in\nestimation:\n\n$$\n(y_{it}-\\bar y_i) = ({\\bf X}_{it}-{\\bf \\bar X}_i)\\beta + (u_{it}-\\bar u_i).\n$$\n\nThe unit-specific effect $c_i$ cancels because it is constant over $t$\n($c_i - \\bar c_i = 0$). Writing the within-transformed variables as\n$\\ddot y_{it}=y_{it}-\\bar y_i$ and $\\ddot{\\bf X}_{it}={\\bf X}_{it}-{\\bf \\bar X}_i$,\nOLS on the demeaned data gives the **fixed-effects (within) estimator**\n(here ${\\bf X}_{it}$ is a $1\\times k$ *row* vector, so\n$\\ddot{\\bf X}_{it}'\\ddot{\\bf X}_{it}$ is the $k\\times k$ outer product)\n\n$$\n\\hat\\beta_{FE} = \\left(\\sum_i \\sum_t \\ddot{\\bf X}_{it}'\\ddot{\\bf X}_{it}\\right)^{-1}\n\\sum_i \\sum_t \\ddot{\\bf X}_{it}'\\ddot y_{it}.\n$$\n\nThis is consistent for $\\beta$ even when $c_i$ is correlated with\n${\\bf X}_{it}$, which is the key advantage of FE over random effects.\nThe price is that any time-invariant regressor (the $W_i$ above) is also\nswept out by the demeaning and cannot be estimated. The usual variance\nestimator is $\\hat V(\\hat\\beta_{FE})=\\hat\\sigma_u^2(\\sum_i\\sum_t \\ddot{\\bf X}_{it}'\\ddot{\\bf X}_{it})^{-1}$\nwith $\\hat\\sigma_u^2$ using degrees of freedom $NT-N-k$; in practice one\nclusters by unit to allow serial correlation within $i$.\n\n## Fixed effects or random effects: the Hausman test\n\nRandom effects is more efficient (it uses both within and between\nvariation) but is consistent only if $c_i$ is uncorrelated with\n${\\bf X}_{it}$; fixed effects is consistent either way. The Hausman test\ncompares the two estimators:\n\n$$\nH = (\\hat\\beta_{FE}-\\hat\\beta_{RE})'\\,[\\hat V(\\hat\\beta_{FE})-\\hat V(\\hat\\beta_{RE})]^{-1}\\,(\\hat\\beta_{FE}-\\hat\\beta_{RE}) \\;\\sim\\; \\chi^2_k\n$$\n\nunder the null that random effects is consistent. A large $H$ (small\n$p$-value) favors fixed effects. In R this is `phtest(fe, re)` from the\n`plm` package; in Stata, `hausman fe re`.\n\n**Caveat: this classic form requires RE to be efficient.** The formula above relies on $\\hat V(\\hat\\beta_{FE})-\\hat V(\\hat\\beta_{RE})$ being positive semi-definite, which in turn requires the RE estimator to actually be the *efficient* estimator under the null -- true only under the RE model's homoscedasticity and no-serial-correlation assumptions. If you are using robust or cluster-robust covariance matrices (the usual practice when errors are heteroscedastic or serially correlated), RE is generally no longer efficient, the covariance difference can fail to be positive definite, and the classic Hausman test statistic can be negative or otherwise ill-behaved. In that case, use a regression-based Hausman test instead: augment the RE (or pooled) regression with the within-unit means of the time-varying regressors (Mundlak's approach) or with the demeaned regressors themselves (Wooldridge's regression-based test), and test the added coefficients jointly with a standard (robust) Wald test -- this is valid under heteroscedasticity/clustering and reduces to the same idea as the classic Hausman test under its assumptions.\n\n## Collapse to unit means, or keep the long format?\n\nA practical question comes up whenever we hold a panel.  Should we\naverage each unit over time and run $N$ regressions, or keep all $NT$\nrows and cluster the standard errors by unit?  Many people treat this\nas a trade-off, and assume the long format must carry more\ninformation.  It usually does not.  The answer turns entirely on where\nthe regressors live.\n\nTake the case where every regressor is time-invariant.  The model is\n\n$$\ny_{it}={\\bf X}_i \\gamma + c_i + u_{it}\n$$\n\nand we have two options: pooled OLS on the $NT$ rows, or OLS on the\n$N$ unit means $\\bar y_i$.  With a balanced panel the two give the same\n$\\hat\\gamma$.  Not close -- identical.  Random effects returns the same\nnumber as well.  Wooldridge (2010) states the reason plainly: because\n$c_i$ is there, new observations within a unit carry no information\nabout $\\gamma$ beyond how they move the unit average $\\bar y_i$.  In\neffect we only have $N$ useful pieces of information.\n\nIn other words, averaging discards nothing, because ${\\bf X}_i$ is\nalready constant over $t$ and the within variation was never available\nto $\\gamma$ in the first place.\n\nWhat does differ is the degrees of freedom.  The unit-mean regression\nuses $N-k$.  Pooled OLS reports $NT-k$, and that is the mistake.\nMoulton (1990) is the classic illustration, and Donald and Lang (2007)\nshow that the $t_{N-k}$ reference distribution is the one that keeps\nthe size right.  Clustering by unit repairs the standard error when $N$\nis large, but it does not repair the degrees of freedom when $N$ is\nsmall.\n\nNow put a time-varying ${\\bf X}_{it}$ into the model.  The two options\nstop agreeing, and not only for the coefficient on ${\\bf X}_{it}$.\nEvery coefficient moves, the one on ${\\bf X}_i$ included.\n\nThe reason is the between-within split from the sections above.\nAveraging to unit means throws away all within variation, so what\nsurvives is the between estimator.  Pooled OLS keeps both sources and\nforces a single coefficient on them, so it returns a variance-weighted\naverage of the within and the between relationship.  The two agree only\nwhen the within and between coefficients are equal.  That is precisely\nthe null the Hausman test examines.  So this is not a new problem.  It\nis the FE-versus-RE question in different clothes.\n\n| Situation | Collapsed vs long |\n|---|---|\n| All regressors time-invariant, balanced panel | Same coefficients; only the degrees of freedom differ |\n| Any time-varying regressor | All coefficients differ, including those on ${\\bf X}_i$ |\n| Unbalanced panel | Differ regardless, since pooled OLS weights each unit by $T_i$ |\n\nThe reconciliation is Mundlak's device, the same one used just above\nfor the regression-based Hausman test.  Add the unit means\n${\\bf \\bar X}_i$ to the long regression alongside ${\\bf X}_{it}$.  The\nwithin and between variation then carry separate coefficients, and the\ncoefficient on ${\\bf \\bar X}_i$ reproduces what the collapsed\nregression estimates.  We keep the within variation and we recover the\nbetween answer, in one regression.\n\nThe useful way to remember it: collapse freely when every regressor is\nconstant within the group, and never when one is not.\n\n## What the long format buys\n\nThe section above is mostly a warning.  It says when collapsing is\nharmless and when it is not.  The other side is worth seeing directly,\nso we simulate a panel where we know the truth.  We use `fixest` here;\nin Stata the same three regressions are `regress`, `xtreg, fe` and\n`xtreg, re`.\n\n### First, the equivalence\n\nTake 1000 units over 6 periods, one time-invariant regressor $X_i$, and\na true $\\gamma=2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nN <- 1000; T <- 6\n\nx   <- rnorm(N)\nbal <- data.frame(id = rep(1:N, each = T), t = rep(1:T, N),\n                  x  = rep(x, each = T), c = rep(rnorm(N), each = T))\nbal$y <- 2 * bal$x + bal$c + rnorm(N * T)\nagg   <- aggregate(cbind(y, x) ~ id, data = bal, FUN = mean)\n\nprint(c(long      = coef(feols(y ~ x, bal))[[\"x\"]],\n        collapsed = coef(feols(y ~ x, agg))[[\"x\"]]), digits = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         long     collapsed \n1.99351677619 1.99351677619 \n```\n\n\n:::\n:::\n\n\nThe two agree to every digit printed.  That is the result quoted above,\nnot an accident of the seed.\n\nNow break the balance.  We drop the later periods for units with high\n$X_i$, so $T_i$ varies, and varies with the regressor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunb  <- bal[!(bal$x > 0.5 & bal$t > 2), ]\nagg2 <- aggregate(cbind(y, x) ~ id, data = unb, FUN = mean)\n\nprint(c(long      = coef(feols(y ~ x, unb))[[\"x\"]],\n        collapsed = coef(feols(y ~ x, agg2))[[\"x\"]]), digits = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         long     collapsed \n2.00682070731 2.01481052322 \n```\n\n\n:::\n:::\n\n\nThey no longer agree.  Pooled OLS weights each unit by $T_i$; the\ncollapsed regression counts each unit once.  Neither is wrong.  They\nanswer different questions, and we should know which one we asked.\nThe $T_i$ here is a special case of a general rule, which the last\nsection of this chapter sets out.\n\n### Then, what collapsing costs\n\nNow the case that matters.  We let $X_{it}$ vary over time, and we make\n$c_i$ correlated with $\\bar X_i$.  That is the situation fixed effects\nexists for.  The truth is $\\beta=1$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- rnorm(N)\nd  <- data.frame(id = rep(1:N, each = T),\n                 x  = rep(mu, each = T) + rnorm(N * T),\n                 c  = rep(mu + rnorm(N), each = T))\nd$y    <- 1 * d$x + d$c + rnorm(N * T)\nd$xbar <- ave(d$x, d$id)\ndagg   <- aggregate(cbind(y, x) ~ id, data = d, FUN = mean)\n\nbetween <- feols(y ~ x,        data = dagg)\npooled  <- feols(y ~ x,        data = d, cluster = ~id)\nwithin  <- feols(y ~ x | id,   data = d)\nmundlak <- feols(y ~ x + xbar, data = d, cluster = ~id)\n\npull <- function(m, v) c(coef(m)[[v]], se(m)[[v]])\ntab <- rbind(`between (collapsed)` = pull(between, \"x\"),\n             `pooled OLS`          = pull(pooled,  \"x\"),\n             `within / FE`         = pull(within,  \"x\"),\n             `Mundlak: x`          = pull(mundlak, \"x\"),\n             `Mundlak: xbar`       = pull(mundlak, \"xbar\"))\ncolnames(tab) <- c(\"estimate\", \"std. error\")\nround(tab, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    estimate std. error\nbetween (collapsed)    1.845      0.035\npooled OLS             1.484      0.022\nwithin / FE            0.995      0.014\nMundlak: x             0.995      0.014\nMundlak: xbar          0.850      0.036\n```\n\n\n:::\n:::\n\n\nRead the table down.  The collapsed regression returns about 1.85,\nbadly biased, because it is the between estimator and $\\bar X_i$\ncarries $c_i$ with it.  Pooled OLS returns about 1.48 -- better, since\nsome within variation is mixed in, but still inconsistent.  The within\nestimator returns about 0.99.  Only the long format can compute it.\nOnce we collapse there is nothing left to demean.\n\nMundlak's regression delivers both at once.  The coefficient on\n$X_{it}$ reproduces the within estimate to three decimals.  The\ncoefficient on $\\bar X_i$ is about 0.85, which is the between estimate\nminus the within estimate.  In words, that second coefficient *is* the\nHausman contrast, and its $t$-statistic is the Hausman test.  A\ncollapsed regression cannot produce it, because it never sees the two\nsources of variation separately.\n\nSo the argument for the long format is not precision.  It is that\ndemeaning, the Hausman comparison, unit-specific slopes, lagged\ndependent variables and anything else built on within variation simply\ndo not exist once the panel is collapsed.  Dynamic models are the\nextreme case, and they get their own chapter,\n[Dynamic Panel Data](dynamic-panel.qmd).\n\n## How OLS weights the data\n\nTwice above we said OLS weights units unequally.  By $T_i$ when the\npanel is unbalanced, and by variance when it mixes within and between\nvariation.  Neither is a panel-specific quirk.  Both follow from one\nrule, and the rule is worth stating on its own.\n\nLet $X$ be the regressor we care about, and let $\\tilde X$ be $X$ after\nresidualising on every other regressor in the model.  By the\nFrisch--Waugh--Lovell theorem,\n\n$$\n\\hat\\beta = \\frac{\\sum_i \\sum_t \\tilde X_{it}\\, y_{it}}\n                 {\\sum_i \\sum_t \\tilde X_{it}^{2}} .\n$$\n\nIn words: each observation enters weighted by $\\tilde X_{it}^2$, the\nsquared leftover variation in the regressor, and a unit's total\ninfluence is $\\sum_t \\tilde X_{it}^2$.  An observation that carries no\nleftover variation carries no weight, however many of its kind we\ncollect.\n\nEverything else is that rule read in a particular model.\n\n| Model | Weight on a unit or stratum |\n|---|---|\n| $X_i$ alone, nothing else varying within the unit | $T_i\\,\\tilde X_i^2$ |\n| $X_i$, with a time-varying $W_{it}$ also in the model | $\\sum_t \\tilde X_{it}^2$ |\n| a time-varying $X_{it}$ | $\\sum_t (X_{it}-\\bar X_i)^2 = (T-1)\\widehat{\\text{Var}}_i(X)$ |\n| binary $d$ with saturated controls | $n_x\\,\\hat d(x)\\,(1-\\hat d(x))$ |\n\nThe second row deserves a note, because it is the one that surprises.\nPutting $W_{it}$ in the model destroys the $T_i$ form.  Residualising a\ntime-invariant $X_i$ on something that moves within the unit makes\n$\\tilde X$ move within the unit as well, so the unit's weight no longer\nfactors.  The rule survives; the shortcut does not.\n\nThe last row is Angrist ([1998](https://doi.org/10.2307/2998558)).\nStrata are weighted by $\\hat d(x)(1-\\hat d(x))$, largest where treatment\nis closest to a coin flip.  Same rule, different regressor.\n\n### When the weighting changes the answer\n\nThe weighting is always happening.  It changes the answer only when the\neffect is heterogeneous *and* the heterogeneity lines up with the\nweight.  We can see both cases at once.  Give every unit its own slope,\nlet units differ in how much $x$ moves, and compare the fixed-effects\nestimate to two averages of the true slopes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nsdX <- runif(N, 0.2, 3)\n\ndemo <- function(b) {\n  h   <- data.frame(id = rep(1:N, each = T),\n                    x  = rnorm(N * T, 0, rep(sdX, each = T)))\n  h$y <- rep(b, each = T) * h$x + rep(rnorm(N), each = T) + rnorm(N * T)\n  w   <- tapply(resid(feols(x ~ 1 | id, h))^2, h$id, sum)\n  c(FE = coef(feols(y ~ x | id, h))[[\"x\"]],\n    `plain avg` = mean(b), `weighted avg` = sum(w * b) / sum(w))\n}\n\nround(rbind(`slope unrelated to how much x moves` = demo(rnorm(N, 1, 1)),\n            `slope larger where x moves more`     = demo(1 + 0.8 * (sdX - 1.6))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                        FE plain avg weighted avg\nslope unrelated to how much x moves 1.0019    1.0179       0.9841\nslope larger where x moves more     1.5338    1.0140       1.5422\n```\n\n\n:::\n:::\n\n\nRead the two rows.  In the first the slopes are drawn independently of\nhow much $x$ moves, and all three numbers agree to within sampling\nnoise.  The weighting is there, and it costs nothing.\n\nIn the second the slope is larger exactly where $x$ moves more.  Now\nfixed effects reports 1.53 while the plain average of the true slopes\nis 1.01, and the weighted average, 1.54, is what the estimator was\ntracking all along.  The estimator is not wrong about what it reports.\nIt reports a variance-weighted average, and we were reading it as an\naverage.\n\nSłoczyński ([2022](https://doi.org/10.1162/rest_a_00953)) makes the\nsame point for a binary treatment: the OLS coefficient is a convex\ncombination of the effect on the treated and the effect on the\nuntreated, and the *smaller* group receives the *larger* weight.  So a\ncoefficient from a sample that is 10% treated is mostly telling us\nabout the 90%.\n\nThe practical reading: with homogeneous effects the weighting is\nharmless and we can ignore it.  With heterogeneous effects the question\nis never whether OLS is weighting, only whether we know what it\nweighted.\n",
    "supporting": [
      "panel-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}