{
  "hash": "cfc8cc5920a34b3ca3d27765332de9c8",
  "result": {
    "engine": "knitr",
    "markdown": "# Interpreting OLS: Effect Weights\n\n\n\nAn OLS regression returns one number, $\\hat\\beta$. What that number estimates when effects are heterogeneous, and how each observation contributes to it, depends on the geometry of the sample and on what else is in the model. This chapter derives the implicit weights OLS uses, and follows them across cross-sectional and panel settings.\n\nTwo companion notes work through related applications in causal inference: [Weights in OLS in causal inference](https://xiangao.github.io/blog_book/weights-ols.html) and [OLS cannot be ATE](https://xiangao.github.io/blog_book/ols-ate.html).\n\n## OLS as a weighted average\n\nStart with a simple regression of $y$ on $x$ with an intercept:\n\n$$ y_i = \\alpha + \\beta x_i + e_i $$ {#eq-simple}\n\nThe OLS slope is the familiar ratio of a covariance to a variance:\n\n$$\\hat\\beta = \\frac{\\sum_{i=1}^n (x_i - \\bar x)(y_i - \\bar y)}{\\sum_{i=1}^n (x_i - \\bar x)^2}$$ {#eq-slope}\n\nNow give each observation its own slope through the sample centroid $(\\bar x, \\bar y)$:\n\n$$s_i \\equiv \\frac{y_i - \\bar y}{x_i - \\bar x}$$ {#eq-si}\n\nWrite $d_i \\equiv x_i - \\bar x$ for the horizontal distance from the centroid, and $w_i \\equiv d_i^2$. Multiply and divide each term of @eq-slope by $d_i$ and it rearranges into\n\n$$\\hat\\beta = \\frac{\\sum_{i=1}^n d_i^2 s_i}{\\sum_{i=1}^n d_i^2} = \\frac{\\sum_{i=1}^n w_i s_i}{\\sum_{i=1}^n w_i}$$ {#eq-wavg}\n\nSo $\\hat\\beta$ is an exact weighted average of the deviation slopes $s_i$, and the weight each observation carries is its squared distance from the mean of $x$.\n\n### What the weights look like\n\nThe weights are highly concentrated. Because they grow with the *square* of distance from $\\bar x$, a few points far from the mean can dominate the estimate while most points near the mean contribute almost nothing. The examples below show how adding or moving a single observation redistributes the weights across the entire sample.\n\nThe figures draw the weights $w_i$ of @eq-wavg as the thickness of each ray from the centroid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow <- function(x, y, main = \"\") {\n  xb <- mean(x); yb <- mean(y); d <- x - xb; s <- (y - yb) / d; w <- d^2\n  plot(x, y, pch = 16, cex = 1.5, xlim = c(-0.5, 11.5), ylim = c(0, 9),\n       xlab = \"x\", ylab = \"y\", main = main)\n  abline(v = xb, lty = 3, col = \"grey55\")\n  segments(xb, yb, x, y, lwd = 0.6 + 9 * w / sum(w), col = \"#9E431899\")\n  abline(lm(y ~ x), lwd = 2, col = \"#0E6473\")\n  points(x, y, pch = 16, cex = 1.5)\n  points(xb, yb, pch = 21, bg = \"white\", col = \"#0E6473\", lwd = 2.5, cex = 1.7)\n  text(x, y, labels = sprintf(\"%.1f%%\", 100 * w / sum(w)),\n       pos = ifelse(y >= yb, 3, 1), cex = .85, col = \"#9E4318\")\n}\nshow(c(1, 3), c(2, 8), \"Two Points\")\n```\n\n::: {.cell-output-display}\n![](interpreting-ols_files/figure-html/unnamed-chunk-2-1.png){width=480}\n:::\n:::\n\n\nWith two points the weights are equal, $50\\%$ each, and both $s_i$ are just the line through the pair.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow(c(1, 3, 4), c(2, 8, 5), \"Three Points\")\n```\n\n::: {.cell-output-display}\n![](interpreting-ols_files/figure-html/unnamed-chunk-3-1.png){width=480}\n:::\n:::\n\n\nAdd a third point at $x=4$ and $\\bar x$ moves to $2.67$. The point at $x=3$ now sits almost on top of $\\bar x$, so it takes only $2.4\\%$ of the weight even though its deviation slope is the largest of the three ($s_2 = 9.0$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow(c(1, 3, 4, 9), c(2, 8, 5, 6), \"Four Points\")\n```\n\n::: {.cell-output-display}\n![](interpreting-ols_files/figure-html/unnamed-chunk-4-1.png){width=480}\n:::\n:::\n\n\nAdd an extreme point at $x=9$ and $\\bar x$ moves to $4.25$. That one observation now carries $65\\%$ of the total weight, while $x=4$ falls to $0.18\\%$ because it has landed near the new centroid. The weights are relative to the whole sample: add data anywhere and the weights everywhere change.\n\n**Simulation — a 100-point sample.** The concentration does not wash out in larger samples. We draw $n = 100$ points, $x_i \\sim N(5, 2^2)$ and $y_i = 2 x_i + \\varepsilon_i$ with $\\varepsilon_i \\sim N(0, 3^2)$, and compare the weight held by the ten points nearest $\\bar x$ against the ten furthest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nn <- 100\nx <- rnorm(n, 5, 2)\ny <- 2 * x + rnorm(n, 0, 3)\n\nxb <- mean(x); yb <- mean(y); w <- (x - xb)^2\no <- order(w, decreasing = TRUE)\n\nplot(x, y, pch = 16, cex = 1, col = \"grey40\", xlab = \"x\", ylab = \"y\", main = \"N = 100 Points\")\nabline(v = xb, lty = 3, col = \"grey55\")\nsegments(xb, yb, x, y, lwd = 0.3 + 10 * w / max(w), col = \"#9E431870\")\nabline(lm(y ~ x), lwd = 2.5, col = \"#0E6473\")\npoints(xb, yb, pch = 21, bg = \"white\", col = \"#0E6473\", lwd = 2.5, cex = 1.8)\n```\n\n::: {.cell-output-display}\n![](interpreting-ols_files/figure-html/unnamed-chunk-5-1.png){width=624}\n:::\n\n```{.r .cell-code}\nvtab(c(`Weight 10 Nearest Mean (%)` = 100 * sum(w[o[91:100]]) / sum(w),\n        `Weight 10 Furthest (%)`     = 100 * sum(w[o[1:10]]) / sum(w),\n        `OLS Estimate`                = coef(lm(y ~ x))[[\"x\"]]), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                           |  value|\n|:--------------------------|------:|\n|Weight 10 Nearest Mean (%) |  0.138|\n|Weight 10 Furthest (%)     | 35.360|\n|OLS Estimate               |  1.865|\n\n\n:::\n:::\n\n\nThe $10\\%$ of points furthest from $\\bar x$ hold $35\\%$ of the weight; the $10\\%$ closest hold $0.14\\%$. A point sitting exactly at $\\bar x$ has an undefined $s_i$ and zero weight: the wild value arrives paired with a weight that annihilates it.\n\n## Deviation slopes $s_i$ versus true effects $b_i$\n\nNow let each unit have its own structural slope $b_i$:\n\n$$ y_i = \\alpha + b_i x_i + e_i $$ {#eq-het}\n\n$b_i$ is a parameter we never see. $s_i$ from @eq-si is computed from the data. The two are not the same object, we observe $s_i$, but are interested in $b_i$, or function of $b_i$.\n\n### Decomposing $s_i$\n\nLet $\\bar b = n^{-1}\\sum_i b_i$ and $C = n^{-1}\\sum_i (b_i - \\bar b)(x_i - \\bar x)$, the sample covariance between $b$ and $x$. Substituting $x_i = d_i + \\bar x$ into @eq-het,\n\n$$s_i = b_i + \\frac{\\bar x (b_i - \\bar b) - C}{d_i} + \\frac{e_i - \\bar e}{d_i}$$ {#eq-decomp}\n\nThe middle term is the trouble. When effects are heterogeneous ($b_i \\neq \\bar b$) it does not vanish, and dividing it by $d_i$ makes $s_i$ blow up for points near $\\bar x$ — before any noise enters. Taking expectations over $e_i$,\n\n$$E[s_i \\mid x, b] = b_i + \\frac{\\bar x (b_i - \\bar b) - C}{d_i} \\neq b_i$$ {#eq-esi}\n\nSo $s_i$ is biased for $b_i$, observation by observation.\n\n### Aggregating up to $\\hat\\beta_{OLS}$\n\nTake the $d_i^2$-weighted expectation of $s_i$, combining @eq-wavg and @eq-esi:\n\n$$E[\\hat\\beta_{OLS} \\mid x, b] = \\frac{\\sum_i d_i^2 E[s_i \\mid x, b]}{\\sum_i d_i^2} = \\frac{\\sum_i d_i^2 b_i + \\bar x \\sum_i d_i (b_i - \\bar b) - C \\sum_i d_i}{\\sum_i d_i^2}$$ {#eq-agg}\n\nBecause $\\sum_i d_i = 0$ and $\\sum_i d_i (b_i - \\bar b) = n C$, the numerator collapses:\n\n$$\\sum_i d_i^2 E[s_i \\mid x, b] = \\sum_i d_i^2 b_i + n \\bar x C = \\sum_i b_i d_i (d_i + \\bar x) = \\sum_i b_i d_i x_i$$ {#eq-num}\n\nAnd since $\\sum_i d_i^2 = \\sum_i d_i x_i$, we get the exact expectation:\n\n$$E[\\hat\\beta_{OLS} \\mid x, b] = \\frac{\\sum_{i=1}^n d_i x_i b_i}{\\sum_{i=1}^n d_i x_i} = \\frac{\\sum_{i=1}^n (x_i - \\bar x) x_i b_i}{\\sum_{i=1}^n (x_i - \\bar x)^2}$$ {#eq-exact}\n\nSo the OLS estimator is unbiased for a weighted average of $b_i$'s.\n\n### So what?\n\n@eq-exact has three consequences for practice.\n\n1.  **OLS is not the ATE under heterogeneity.** $\\hat\\beta_{OLS}$ is not the plain average effect $\\bar b = E[b_i]$. It is a variance-weighted parameter, and it equals the ATE only when the $b_i$ are uncorrelated with the leverage $d_i x_i = (x_i - \\bar x)x_i$.\n2.  **Leverage annihilates the individual bias.** @eq-esi shows $s_i$ is a hopeless estimate of $b_i$ precisely where $d_i \\approx 0$. The weight $w_i = d_i^2$ zeroes out exactly those unstable points, turning biased observation-level slopes into the exact parameter of @eq-exact.\n3.  **The same mechanism runs through the causal estimators.** With a binary regressor it puts the most weight where treatment is near a coin flip (Angrist 1998); grouped by treatment status it reverses the propensity weights, favouring the smaller group (Słoczyński 2022). Both are @eq-exact read at different granularities, as the rest of the chapter shows.\n\n**Simulation — deviation slopes versus true effects.** We check the algebra directly, drawing $n = 2000$ with heterogeneous slopes $b_i \\sim N(1, 0.5^2)$, regressor $x_i \\sim N(0, 2^2)$, and $y_i = b_i x_i + \\varepsilon_i$, $\\varepsilon_i \\sim N(0, 2^2)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(6)\nn <- 2000\nb <- rnorm(n, 1, 0.5)\nx <- rnorm(n, 0, 2)\ny <- b * x + rnorm(n, 0, 2)\nxb <- mean(x); d <- x - xb; w <- d^2\ns  <- (y - mean(y)) / d\n\nmtab(cbind(value = c(\n  `cor(s_i, b_i), Pearson`    = cor(s, b),\n  `cor(s_i, b_i), Spearman`   = cor(s, b, method = \"spearman\"),\n  `sd(s_i)`                   = sd(s),\n  `Weighted Avg of s_i`       = sum(w * s) / sum(w),\n  `OLS Estimate`              = unname(coef(lm(y ~ x))[2]),\n  `E[beta | x, b] (eq-exact)` = sum(d * x * b) / sum(d * x))), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                               |   value|\n|:------------------------------|-------:|\n|cor(s_i, b_i), Pearson         |   0.019|\n|cor(s_i, b_i), Spearman        |   0.258|\n|sd(s_i)                        | 117.420|\n|Weighted Avg of s_i            |   0.950|\n|OLS Estimate                   |   0.950|\n|E[beta &#124; x, b] (eq-exact) |   0.991|\n\n\n:::\n:::\n\n\nThe $s_i$ are wildly dispersed ($\\text{sd}(s_i) > 100$) and barely correlated with the true $b_i$ — Pearson $0.02$, though the rank correlation is $0.26$, higher once the explosive tails near $\\bar x$ are set aside. Their leverage-weighted average equals $\\hat\\beta_{OLS}$ exactly; that is @eq-wavg, an identity. The same leverage applied to the true $b_i$ gives $0.99$, the value $\\hat\\beta$ estimates *in expectation* (@eq-exact) — and this sample's $\\hat\\beta = 0.95$ sits about two standard errors below it. The gap between $0.95$ and $0.99$ is ordinary sampling variation, not a failure of the weighting identity. @eq-exact pins down what $\\hat\\beta$ converges to across repeated samples; any single draw fluctuates around that target, and $0.95$ versus $0.99$ is well within the range one would expect. The structural relationship between the weights and the true slopes is exact and permanent; it is the realisation, not the identity, that is noisy.\n\nNoise is not what distorts $s_i$. Turn it off entirely, set $y_i = b_i x_i$, and ask how well each $s_i$ tracks its own $b_i$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny0 <- b * x\ns0 <- (y0 - mean(y0)) / (x - xb)\nvtab(c(`cor(s_i, b_i), no noise` = cor(s0, b),\n        `Weighted Avg of s_i`     = sum(w * s0) / sum(w),\n        `Weighted Avg of b_i`     = sum(w * b) / sum(w),\n        `OLS, noiseless`          = unname(coef(lm(y0 ~ x))[2])), 4)\n```\n\n::: {.cell-output-display}\n\n\n|                        |  value|\n|:-----------------------|------:|\n|cor(s_i, b_i), no noise | 0.1436|\n|Weighted Avg of s_i     | 0.9914|\n|Weighted Avg of b_i     | 0.9919|\n|OLS, noiseless          | 0.9914|\n\n\n:::\n:::\n\n\nThe correlation stays at $0.14$ with no noise in the data at all. The reason is visible in @eq-decomp: even without the error term, $s_i$ contains $\\bar x(b_i - \\bar b)/d_i$, which depends on every unit's slope through $\\bar b$ and on every unit's position through $\\bar x$. A ray from the centroid is anchored at $(\\bar x, \\bar y)$, and $\\bar y$ shifts when any other unit's slope changes. So $s_i$ is a function of the entire sample, not of unit $i$ alone, and heterogeneity in the $b_i$ makes it impossible for any single ray to isolate its own unit's effect. Adding noise inflates the variance of $s_i$ further through the $(e_i - \\bar e)/d_i$ term, but the low correlation is already present without it.\n\n### Under homogeneity, the weights buy precision\n\nIf $b_i = b$ for all $i$, @eq-decomp reduces to $s_i = b + (e_i - \\bar e)/d_i$. With homoskedastic errors $\\text{Var}(e_i) = \\sigma^2$,\n\n$$E[s_i \\mid X] = b, \\qquad \\text{Var}(s_i \\mid X) = \\frac{\\sigma^2 (1 - 1/n)}{d_i^2} \\propto \\frac{1}{d_i^2}$$ {#eq-precision}\n\nNow $w_i = d_i^2$ is exactly the inverse-variance weight. Any weighting of the $s_i$ — equal, $d_i^2$, anything — is unbiased for $b$; what the weights buy is precision, not correctness, and $d_i^2$ is the choice that minimises variance. That is OLS as BLUE. The argument is conditional on $X$, where $d_i$ is a known constant and the weights are functions of $x$ alone.\n\n## The general rule: FWL\n\nThe panel chapter met two weightings — by $T_i$ when a panel is unbalanced, and by variance when a regression mixes within and between variation.\n\nRegress $y$ on a regressor of interest $V$ and a control matrix $X$, and let $\\tilde V$ be the residual from projecting $V$ on $X$. By the Frisch–Waugh–Lovell theorem,\n\n$$\\hat\\beta = \\frac{\\sum_{i=1}^n \\tilde V_i y_i}{\\sum_{i=1}^n \\tilde V_i^2}$$ {#eq-fwl}\n\nBe careful what $\\tilde V_i$ is. A single observation has no variation of its own; variation belongs to a collection. What it has is a *deviation* — how far its regressor sits from what the rest of the model predicts for it. With only an intercept, that is distance from the grand mean. With unit fixed effects, it is distance from the unit's own mean. Which mean gets subtracted is the most consequential detail in this section, and we come back to it.\n\n@eq-fwl reads two ways. This chapter takes the first; the second opens the companion chapter [Interpreting OLS: Outcome Weights](outcome-weights.qmd).\n\n**Weights on effects.** Under a heterogeneous model $y_i = \\beta_i V_i + X_i \\gamma + e_i$,\n\n$$ \\hat\\beta = \\frac{\\sum_{i=1}^n w_i \\beta_i}{\\sum_{i=1}^n w_i}, \\qquad w_i = \\tilde V_i V_i $$ {#eq-weff}\n\nThe denominator $\\sum_i w_i = \\sum_i \\tilde V_i V_i = \\sum_i \\tilde V_i^2 \\ge 0$ always, by OLS orthogonality. Individual weights $w_i = \\tilde V_i V_i$ can be negative — they are whenever $\\tilde V_i$ and $V_i$ have opposite signs.\n\n### Where the square comes from\n\nSubstitute $y_i = \\beta_i V_i + X_i \\gamma + e_i$ into the numerator of @eq-fwl and it becomes $\\sum_i \\beta_i \\tilde V_i V_i$; over the whole sample,\n\n$$\\sum_{i=1}^n \\tilde V_i V_i = \\sum_{i=1}^n \\tilde V_i^2$$ {#eq-square}\n\nbecause $\\tilde V$ is orthogonal to the fitted part of $V$.\n\nIn a panel, several rows share a unit, and it is natural to ask whether the same identity holds *within a single unit* — summed over that unit's own $t$'s — and not only over the whole sample. Write $V_{it}$ for the observation and $\\bar V_i$ for the unit's own mean. With unit fixed effects $\\tilde V_{it} = V_{it} - \\bar V_i$, and expanding the product gives the within-unit version directly,\n\n$$\\sum_{t=1}^{T} (V_{it} - \\bar V_i) V_{it} = \\sum_{t=1}^{T} V_{it}^2 - T \\bar V_i^{\\,2} = \\sum_{t=1}^{T} (V_{it} - \\bar V_i)^2$$ {#eq-within-square}\n\n## Two causal decompositions: Angrist and Słoczyński\n\n@eq-weff says the coefficient is a weighted average of effects with weights $w_i = \\tilde V_i V_i$; everything below only evaluates those weights. Angrist reads them at the stratum level. Słoczyński reads the same weights one level up, grouped by treatment status, where they come out reversed relative to the natural shares of the ATE.\n\nLet $D \\in \\{0, 1\\}$ be a binary treatment and $X$ discrete strata $x \\in \\{1, \\dots, K\\}$, with the controls saturated — one indicator per stratum, so no functional form is imposed within cells. Discreteness is essential: saturated controls require a finite number of cells, so continuous $X$ cannot be saturated. With continuous controls the linear projection $\\hat D(X)$ is not the cell proportion — it is a linear approximation that can fall outside $[0, 1]$ — and the stratum-by-stratum decomposition below does not go through. With continuous $X$ one could bin it, but the result then holds for the chosen bins, not for $X$ itself.\n\n### Angrist (1998): weighting by stratum\n\nResidualising $D_i$ on a full set of stratum indicators gives $\\tilde D_i = D_i - \\hat D(x)$, where $\\hat D(x) = E[D \\mid X = x]$. Saturation is what makes this the true cell proportion: the OLS projection on a complete set of dummies recovers the conditional mean exactly. Sum the effect weights $w_i = \\tilde D_i D_i$ within a stratum:\n\n$$w_x = \\sum_{i \\in x} \\tilde D_i D_i = \\sum_{i \\in x} D_i^2 - \\hat D(x) \\sum_{i \\in x} D_i = n_x \\hat D(x) - n_x \\hat D(x)^2 = n_x \\hat D(x)(1 - \\hat D(x))$$ {#eq-angrist-w}\n\nNothing new has been added: it is $w_i = \\tilde V_i V_i$ from @eq-weff with a binary $V$, where $D_i^2 = D_i$ makes the sum collapse. The maximum at $\\hat D(x) = 1/2$ is just the fact that a binary variable has most variance when it is a coin flip.\n\nNote what plays the role of $s_i$ here. A single observation with a binary regressor has no slope; you need one treated and one control unit to form a difference. The smallest unit carrying an effect is therefore the *stratum*, and $s_i$ becomes the stratum difference in means.\n\nLet $\\hat\\delta_x$ be the stratum difference-in-means. Substituting @eq-angrist-w into @eq-weff,\n\n$$\\hat\\beta_{OLS} = \\frac{\\sum_{x=1}^K n_x \\hat D(x)(1 - \\hat D(x))\\, \\hat\\delta_x}{\\sum_{x=1}^K n_x \\hat D(x)(1 - \\hat D(x))}$$ {#eq-angrist}\n\nso strata with propensity near $\\hat D(x) = 0.5$ get the most weight per observation. A stratum that contains only treated or only control units has $\\hat D(x) = 1$ or $0$, so $w_x = 0$: it drops out entirely, because there is no within-stratum comparison to make. A linear model with continuous controls would extrapolate into those strata instead of dropping them.\n\n### Słoczyński (2022): aggregating to two groups\n\nAngrist sorts by covariate stratum. Słoczyński sorts by treatment status instead, collapsing everything into two numbers — the effect on the treated and the effect on the untreated. Aggregating the stratum effects $\\hat\\delta_x$ of @eq-angrist with each stratum's count of treated or untreated units gives\n\n$$\\text{ATT} = \\frac{\\sum_x n_x \\hat D(x)\\, \\hat\\delta_x}{\\sum_x n_x \\hat D(x)}, \\qquad\n\\text{ATU} = \\frac{\\sum_x n_x (1 - \\hat D(x))\\, \\hat\\delta_x}{\\sum_x n_x (1 - \\hat D(x))}$$ {#eq-attatu}\n\nand the ATE combines them with their natural shares, $\\rho = P(D = 1)$. To see this, write $\\text{ATE} = E[\\tau_i]$ and condition on treatment status:\n\n$$E[\\tau_i] = P(D=1)\\, E[\\tau_i \\mid D=1] + P(D=0)\\, E[\\tau_i \\mid D=0] = \\rho\\, \\text{ATT} + (1 - \\rho)\\, \\text{ATU}.$$\n\nIn the finite-sample, stratum-weighted version the same decomposition holds because $\\sum_x n_x \\hat D(x) = n_1$ and $\\sum_x n_x(1-\\hat D(x)) = n_0$, so\n\n$$\\text{ATE} = \\rho\\, \\text{ATT} + (1 - \\rho)\\, \\text{ATU}$$ {#eq-ate}\n\nThe OLS weights of @eq-angrist go as the propensity *variance* $\\hat D(x)(1 - \\hat D(x))$; the group weights of @eq-attatu go as the propensity itself or its complement. The relation between the two is Słoczyński's result. Write $p = \\hat D(X)$ for the cell propensity. Because the design is saturated — the controls are a full set of stratum dummies — residualising $D$ on the strata leaves exactly $\\tilde D = D - p$, so the coefficient is $E[\\tilde D\\, Y]/E[p(1-p)]$. Since $p$ is constant within a stratum, $Y$ enters only through the group means $m_j(p) = E[Y \\mid p, D = j]$, and, using $\\tilde D = 1 - p$ for treated and $-p$ for untreated units,\n\n$$\\beta_{OLS} = \\frac{\\rho\\, E[(1 - p)\\, m_1(p) \\mid D = 1] - (1 - \\rho)\\, E[p\\, m_0(p) \\mid D = 0]}{E[p(1 - p)]}$$ {#eq-sloc1}\n\nSubstitute the within-group linear projections $m_j(p) = \\alpha_j + \\gamma_j p + \\varepsilon_j(p)$. The residual term $E[p(1-p)(\\varepsilon_1 - \\varepsilon_0)]/E[p(1-p)]$ vanishes when the group means are linear in $p$, leaving\n\n$$\\beta_{OLS} = (\\alpha_1 - \\alpha_0) + (\\gamma_1 - \\gamma_0)\\, \\frac{E[p^2(1 - p)]}{E[p(1 - p)]}$$ {#eq-sloc2}\n\nThe last ratio is moment algebra — an identity in the first three moments of $p$, exact for any distribution. With $\\mu_j = E[p \\mid D = j]$, $V_j = \\text{Var}(p \\mid D = j)$, and $w_1, w_0$ the weights defined in @eq-sloc-main below,\n\n$$\\frac{E[p^2(1 - p)]}{E[p(1 - p)]} = w_1 \\mu_1 + w_0 \\mu_0$$ {#eq-moment}\n\nholds identically in the distribution of $p$. Under linearity $\\text{ATT} = (\\alpha_1 - \\alpha_0) + (\\gamma_1 - \\gamma_0)\\mu_1$ and $\\text{ATU} = (\\alpha_1 - \\alpha_0) + (\\gamma_1 - \\gamma_0)\\mu_0$, so @eq-sloc1 through @eq-moment combine into the main result,\n\n$$\\hat\\beta_{OLS} = w_1\\, \\text{ATT} + w_0\\, \\text{ATU}, \\qquad\nw_1 = \\frac{(1 - \\rho) V_0}{\\rho V_1 + (1 - \\rho) V_0}, \\quad w_0 = 1 - w_1$$ {#eq-sloc-main}\n\nwhere $V_j$ is the variance of the propensity score within group $j$. This is exact for the effects of the within-group linear projections; for ATT and ATU it is exact when the group means are linear in $p$ and an approximation otherwise.\n\nTwo things about @eq-sloc-main matter. First, the weight $w_1$ on ATT falls as the treated share $\\rho$ rises: the larger the treated group, the smaller its say. That is the whole of \"smaller groups get more weight.\" Second, when the propensity has equal variance in the two groups, $V_1 = V_0$, the weights collapse to the reversed shares,\n\n$$\\hat\\beta_{OLS} \\approx (1 - \\rho)\\, \\text{ATT} + \\rho\\, \\text{ATU}$$ {#eq-reversed}\n\nthe same two quantities as the ATE in @eq-ate, with the weights **swapped**. At $\\rho = 0.1$ the coefficient puts $0.9$ on the effect for the treated tenth; the ATE puts $0.1$ there.\n\nOne caveat. @eq-reversed is exact under equal propensity variance across groups — not \"no covariates,\" though no covariates is one trivial way to get there. Słoczyński calls the condition unlikely to hold exactly and offers $\\rho$ as a rule of thumb, cleanest near $\\rho = 0\\%$, $50\\%$, or $100\\%$.\n\n**Simulation — Angrist and Słoczyński weights.** We draw $n = 400{,}000$ units in five covariate strata ($X \\in \\{1,\\dots,5\\}$), each with its own treatment effect $\\tau_x = (0, 1, 2, 3, 4)$, so the plain ATE is $2$. The outcome is $y = \\tau_x D + X + \\varepsilon$. We run the simulation twice with different propensity schedules: once with the treated share near half ($\\rho \\approx 0.5$, propensities ranging from $0.08$ to $0.93$ across strata) and once with few treated ($\\rho \\approx 0.09$, propensities from $0.02$ to $0.20$). The point is to show that the OLS coefficient moves with the treated share even though the stratum effects do not change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(21)\nn <- 400000\nX <- sample(1:5, n, TRUE)\n\ncompare <- function(px) {\n  d  <- rbinom(n, 1, px[X]); ta <- c(0, 1, 2, 3, 4)[X]\n  yy <- ta * d + X + rnorm(n)\n  dt <- resid(lm(d ~ factor(X)))\n  nx <- as.vector(table(X)); dh <- as.vector(tapply(d, X, mean))\n  DIM <- as.vector(tapply(yy[d == 1], X[d == 1], mean) - tapply(yy[d == 0], X[d == 0], mean))\n  rho <- mean(d); ATT <- weighted.mean(ta, d); ATU <- weighted.mean(ta, 1 - d)\n  c(`rho`                      = rho,\n    `Max |Weight Diff|`         = max(abs(as.vector(tapply(dt * d, X, sum)) - nx*dh*(1-dh))),\n    `OLS Saturated`            = unname(coef(lm(yy ~ d + factor(X)))[[\"d\"]]),\n    `Angrist Weighted`         = sum(nx*dh*(1-dh) * DIM) / sum(nx*dh*(1-dh)),\n    `Sloczynski Approx`        = (1 - rho) * ATT + rho * ATU,\n    `ATE`                      = mean(ta))\n}\nres <- cbind(`rho ~ 0.5`  = compare(c(.08, .20, .50, .75, .93)),\n             `rho ~ 0.09` = compare(c(.02, .04, .08, .12, .20)),\n             `rho ~ 0.91` = compare(c(.80, .88, .92, .96, .98)))\nmtab(res, 4)\n```\n\n::: {.cell-output-display}\n\n\n|                            | rho ~ 0.5| rho ~ 0.09| rho ~ 0.91|\n|:---------------------------|---------:|----------:|----------:|\n|rho                         |    0.4913|     0.0909|     0.9069|\n|Max &#124;Weight Diff&#124; |    0.0000|     0.0000|     0.0000|\n|OLS Saturated               |    2.0121|     2.8740|     1.1262|\n|Angrist Weighted            |    2.0121|     2.8740|     1.1262|\n|Sloczynski Approx           |    2.0293|     2.8577|     1.1403|\n|ATE                         |    1.9978|     1.9978|     1.9978|\n\n\n:::\n:::\n\n\nThe two weight vectors — the stratum sums $\\sum \\tilde D_i D_i$ and Angrist's $n_x \\hat D(x)(1 - \\hat D(x))$ — are the same, below $10^{-9}$ (the `Max |Weight Diff|` row, $0$ to four decimals), and the Angrist-weighted average reproduces the OLS coefficient exactly. With $\\rho \\approx 0.5$ the coefficient is $2.012$ against an ATE of $1.998$: close, because near-equal treated and control shares are where the weighting does least. Push the treated share to $\\rho \\approx 0.09$ and the coefficient jumps to $2.874$; push it the other way to $\\rho \\approx 0.91$ and it falls. The two extremes are symmetric: at $\\rho = 0.09$ OLS overweights ATT, at $\\rho = 0.91$ it overweights ATU. Nothing about the effects changed. Only the treated share did.\n\nWhy does OLS overweight the treated when they are few? The FWL residual is $\\tilde D_i = D_i - \\hat D(x)$. When $\\rho$ is small, $\\hat D(x)$ is small in most strata: a treated unit has $\\tilde D_i = 1 - \\hat D(x) \\approx 1$, a control unit has $\\tilde D_i = -\\hat D(x) \\approx 0$. Treated units are the unusual ones — they sit far from the stratum mean of $D$ — so they carry most of the leverage, the same way a point far from $\\bar x$ dominates the simple regression. At $\\rho = 0.09$ the reversed-share approximation puts weight $1 - \\rho = 0.91$ on ATT and only $0.09$ on ATU, while the ATE puts $0.09$ on ATT and $0.91$ on ATU. In observational data where the treated group is small — a common setting — the OLS coefficient can be far from the population average effect even under unconfoundedness, purely because of the weighting.\n\nThe reversed-share Słoczyński approximation $(1-\\rho)\\,\\text{ATT} + \\rho\\,\\text{ATU}$ gives $2.029$ against the exact $2.012$, and $2.858$ against $2.874$ — within about a percent, but the exact weights of @eq-sloc-main are what to report.\n\n### The three, side by side\n\n| Decomposition | Sorted by | Smallest effect unit | Exact when | Reference |\n|---------------|---------------|---------------|---------------|---------------|\n| Observation rule | nothing | $s_i$ | always (identity) | @eq-wavg |\n| Angrist (1998) | covariate stratum $x$ | stratum difference $\\hat\\delta_x$ | saturated controls | @eq-angrist |\n| Słoczyński (2022) | treatment status $D$ | group averages ATT, ATU | equal propensity variance | @eq-reversed |\n\nRead down the last column. The observation identity always holds and says little. Angrist's needs saturation and gives an interpretable weight. Słoczyński's needs more and gives the sharpest statement of the three: the coefficient and the ATE are the same two numbers with the weights reversed. Underneath all of them, Hazlett and Shinkre (2024) show these weights are exactly the bias from fitting a constant effect when effects vary, and argue for estimators that tolerate heterogeneity rather than for diagnosing the weights after the fact.\n\n## Within versus between, in panels\n\nPooled OLS mixes two sources of variation: within-unit, the deviations from a unit's own mean, and between-unit, the differences across unit means. Which one dominates is not chosen; it follows from the same rule. Take the within side first.\n\nNothing new happens here — it is the opening leverage rule with a different mean subtracted. @eq-fwl weights every observation by its squared deviation $\\tilde V_i^2$ from whatever the controls predict for it; @eq-weff weights each effect by $w_i = \\tilde V_i V_i$. Simple OLS residualises against an intercept alone, so the deviation is from the grand mean and $w_i = (x_i - \\bar x)^2$, the leverage of @eq-wavg. Panel fixed effects residualises against unit dummies, so the deviation is from the unit's *own* mean and $w_i = \\sum_t (x_{it} - \\bar x_i)^2$ by @eq-within-square. Pooled OLS drops the dummies and is back to distance from the grand mean — which is exactly why the between comparison creeps back in. So the whole section is @eq-wavg read with the unit mean in place of the grand mean.\n\n### Within-unit weighting: an extreme case\n\nA fixed-effects estimate is identified by units whose $x$ changes over time. Units whose $x$ barely moves get near-zero weight regardless of their true effect. So the FE coefficient estimates the effect for the movers, not the population average. When the movers and the stayers have different effects, the two diverge.\n\nThe simulation below constructs the extreme version. Half the units barely move and have a true slope of zero; the other half move a lot and have a true slope of two. The average slope across all units is one. The DGP draws $N = 1000$ units for $T = 6$ periods, with $y_{it} = b_i x_{it} + \\alpha_i + \\varepsilon_{it}$, $\\alpha_i \\sim N(0,1)$, $\\varepsilon_{it} \\sim N(0,1)$. Both groups have $E[x_{it}] = 0$, so they differ only in how much $x$ moves within a unit, not in its level.\n\n| Group | Units | $\\text{sd}(x_{it})$ | True slope $b_i$ |\n|-------|-------|---------------------|-------------------|\n| Steady | 1–500 | 0.2 | 0 |\n| Movers | 501–1000 | 3 | 2 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nhalf <- N / 2\ng <- data.frame(id   = rep(1:N, each = T),\n                move = rep(c(rep(0.2, half), rep(3, half)), each = T),\n                b    = rep(c(rep(0,   half), rep(2, half)), each = T))\ng$x <- rnorm(N * T, 0, g$move)\ng$y <- g$b * g$x + rep(rnorm(N), each = T) + rnorm(N * T)\n\nwg <- tapply(resid(feols(x ~ 1 | id, g))^2, g$id, sum)\nmtab(cbind(value = c(\n  `average of the two true slopes`      = mean(c(0, 2)),\n  `FE estimate`                         = coef(feols(y ~ x | id, g))[[\"x\"]],\n  `Pooled OLS`                          = unname(coef(lm(y ~ x, g))[[\"x\"]]),\n  `weight held by the steady half (%)`  = 100 * sum(wg[1:half]) / sum(wg))), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                   | value|\n|:----------------------------------|-----:|\n|average of the two true slopes     | 1.000|\n|FE estimate                        | 1.984|\n|Pooled OLS                         | 1.983|\n|weight held by the steady half (%) | 0.473|\n\n\n:::\n:::\n\n\nBoth estimates are near $2$, not the simple average of $1$. The steady units hold under half of one percent of the FE weight: their six observations sit almost on top of their own unit mean, and squaring those tiny deviations puts them nowhere in the sum. Pooled OLS agrees because both groups have $E[x_{it}] = 0$ — there is no between-group difference in $x$ levels, so $V_{between} = 0$ and pooled OLS collapses to $\\beta_{within}$. Both estimators weight by variance, and the movers contribute $\\sigma^2 = 9$ against the steady group's $0.04$, so neither comes close to the simple average. The two estimators diverge only when the group means of $x$ differ, creating a between channel with its own slope. The next subsection shifts the steady group's mean $x$ away from zero and shows FE holding steady while pooled OLS collapses toward the between-slope.\n\n### Splitting the two channels\n\nThat result was about the *within-unit* deviation. Plain pooled OLS uses distance from the grand mean instead, and the two coincided above only because both halves were built around zero. Separate them and the algebra says exactly what happens.\n\nLet $G$ index groups — any number of them, any sizes — with shares $p_g$, group means $\\mu_g = E[x \\mid G=g]$ and $\\bar y_g = E[y \\mid G=g]$, within-group variances $\\sigma_g^2$, and true slopes $\\beta_g$. The pooled slope is $\\text{plim}\\;\\hat\\beta_{OLS} = \\text{Cov}(x, y)/\\text{Var}(x)$, and the whole derivation is one move: condition on $G$ and split numerator and denominator each into a within piece and a between piece. The laws of total covariance and total variance do this exactly,\n\n$$\\text{Cov}(x, y) = \\underbrace{E[\\text{Cov}(x, y \\mid G)]}_{\\text{within}} + \\underbrace{\\text{Cov}(E[x \\mid G],\\, E[y \\mid G])}_{\\text{between}}$$ {#eq-totcov}\n\n$$\\text{Var}(x) = \\underbrace{E[\\text{Var}(x \\mid G)]}_{\\text{within}} + \\underbrace{\\text{Var}(E[x \\mid G])}_{\\text{between}}$$ {#eq-totvar}\n\nName each variance, and define each slope as its own covariance over its own variance:\n\n$$V_{within} = E[\\text{Var}(x \\mid G)], \\qquad \\beta_{within} = \\frac{E[\\text{Cov}(x, y \\mid G)]}{E[\\text{Var}(x \\mid G)]}$$ {#eq-within-comp}\n\n$$V_{between} = \\text{Var}(E[x \\mid G]), \\qquad \\beta_{between} = \\frac{\\text{Cov}(E[x \\mid G],\\, E[y \\mid G])}{\\text{Var}(E[x \\mid G])}$$ {#eq-between-comp}\n\nWith those definitions the within numerator of @eq-totcov *is* $V_{within}\\beta_{within}$ and the between numerator *is* $V_{between}\\beta_{between}$ — no algebra, just the definitions. Dividing @eq-totcov by @eq-totvar therefore gives the pooled slope as a convex combination,\n\n$$\\text{plim}\\;\\hat\\beta_{OLS} = \\frac{V_{within}\\, \\beta_{within} + V_{between}\\, \\beta_{between}}{V_{within} + V_{between}}$$ {#eq-pooled}\n\nNothing here used how many groups there are or that they are balanced; @eq-pooled holds for any grouping — including $G$ = the panel unit, with $N$ groups of sizes $T_i$. The only modelling input is $\\text{Cov}(x, y \\mid G=g) = \\beta_g \\sigma_g^2$, that within a group the error is uncorrelated with $x$. It makes $\\beta_{within}$ an explicit share- and variance-weighted average of the group slopes, and leaves $\\beta_{between}$ as the across-group regression of the group $y$-means on the group $x$-means:\n\n$$\\beta_{within} = \\frac{\\sum_g p_g \\beta_g \\sigma_g^2}{\\sum_g p_g \\sigma_g^2}, \\qquad\n\\beta_{between} = \\frac{\\sum_g p_g (\\mu_g - \\bar\\mu)(\\bar y_g - \\bar\\mu_y)}{\\sum_g p_g (\\mu_g - \\bar\\mu)^2}$$ {#eq-slopes}\n\nwith grand means $\\bar\\mu = \\sum_g p_g \\mu_g$ and $\\bar\\mu_y = \\sum_g p_g \\bar y_g$.\n\nThe two-equal-group case in the simulation below is where these collapse to closed forms. Equal shares turn the averages into $\\tfrac12$'s. The two group means then form a fair two-point variable, and such a variable taking values $a_1, a_2$ has variance $\\tfrac14(a_1 - a_2)^2$ — that is where the $\\tfrac14$ comes from — so\n\n$$V_{within} = \\tfrac{1}{2}(\\sigma_1^2 + \\sigma_2^2), \\quad\n\\beta_{within} = \\frac{\\beta_1 \\sigma_1^2 + \\beta_2 \\sigma_2^2}{\\sigma_1^2 + \\sigma_2^2}, \\quad\nV_{between} = \\tfrac{1}{4}\\Delta\\mu^2, \\quad\n\\beta_{between} = \\frac{\\Delta\\bar y}{\\Delta\\mu}$$ {#eq-two-group}\n\nwhere $\\Delta\\mu = \\mu_1 - \\mu_2$ and $\\Delta\\bar y = \\bar y_1 - \\bar y_2$: with only two groups $\\beta_{between}$ is a single rise over run between the centroids.\n\n$\\beta_{within}$ is a variance-weighted average of the group slopes — the same $\\sigma^2$ weighting as everywhere else in this chapter, one level up. And $\\beta_{between}$ depends only on where the group centroids sit, so it can take any value at all, regardless of the within-group slopes.\n\nThe closed forms are special to two equal groups. With two *unequal* groups every $\\tfrac12$ becomes a share $p_g$ and the $\\tfrac14$ becomes $p(1-p)$ — Angrist's weight again; with *more than two* groups $\\beta_{between}$ is the genuine across-group regression slope of @eq-slopes, not a two-point ratio.\n\nFixed effects removes $V_{between}$ by demeaning and isolates $\\beta_{within}$. As the groups pull apart, $\\Delta\\mu \\to \\infty$, $V_{between}$ swamps $V_{within}$ and drags $\\hat\\beta_{OLS}$ toward $\\beta_{between}$.\n\n**Simulation — pulling the groups apart.** The DGP is the same as the within-unit weighting simulation: 500 steady units ($b_i = 0$, $\\text{sd}(x) = 0.2$) and 500 movers ($b_i = 2$, $\\text{sd}(x) = 3$). The one change is that the steady group's mean $x$ is shifted from $0$ to $10$ or $100$, while the movers stay centred at zero. This opens a gap $\\Delta\\mu$ between the two group centroids without changing any within-unit slope. The between-slope $\\beta_{between} = \\Delta\\bar y / \\Delta\\mu$ is near zero, because the steady group's slope is zero and the movers' mean $y$ is also near zero. So as $\\Delta\\mu$ grows, pooled OLS is dragged toward zero while FE, which removes the between channel by demeaning, stays at $\\beta_{within} \\approx 2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_within <- (0 * 0.2^2 + 2 * 3^2) / (0.2^2 + 3^2)\nV_within <- 0.5 * (0.2^2 + 3^2)\npredicted <- function(shift) V_within * b_within / (V_within + 0.25 * shift^2)\n\npark <- function(shift) {\n  set.seed(1)\n  half <- N / 2\n  move <- c(rep(0.2, half), rep(3, half))\n  b    <- c(rep(0,   half), rep(2, half))\n  x    <- rnorm(N * T, 0, rep(move, each = T)) + rep(c(rep(shift, half), rep(0, half)), each = T)\n  y    <- rep(b, each = T) * x + rep(rnorm(N), each = T) + rnorm(N * T)\n  d    <- data.frame(id = rep(1:N, each = T), x = x, y = y)\n  c(`FE estimate`       = coef(feols(y ~ x | id, d))[[\"x\"]],\n    `OLS Predicted`     = predicted(shift),\n    `OLS Actual`        = coef(lm(y ~ x, d))[[\"x\"]])\n}\n\nmtab(t(sapply(c(`shift 0` = 0, `shift 10` = 10, `shift 100` = 100), park)), 3)\n```\n\n::: {.cell-output-display}\n\n\n|          | FE estimate| OLS Predicted| OLS Actual|\n|:---------|-----------:|-------------:|----------:|\n|shift 0   |       1.984|         1.991|      1.983|\n|shift 10  |       1.984|         0.305|      0.311|\n|shift 100 |       1.984|         0.004|      0.004|\n\n\n:::\n:::\n\n\nFixed effects stays flat near the theoretical $\\beta_{within} = 1.991$ wherever the steady group sits. Plain OLS falls from $1.983$ to $0.004$ on identical true slopes: as $\\Delta\\mu$ grows, the between weight $\\tfrac{1}{4}\\Delta\\mu^2$ swamps the fixed within weight $4.52$, and the coefficient is dragged toward $\\beta_{between} = 0$ like $9/(4.52 + \\Delta\\mu^2/4)$, the numerator $\\tfrac{1}{2}(\\beta_1 \\sigma_1^2 + \\beta_2 \\sigma_2^2) = 9$.\n\nThe figure below draws this directly. Two groups of 200 points each share the same within-group slopes: movers have $y = 2x + \\varepsilon$ with $x \\sim N(0, 3^2)$, the steady group has $y = \\varepsilon$ with $x \\sim N(\\text{shift}, 0.2^2)$. Across the three panels the shift increases from $0$ to $10$ to $100$, opening a gap $\\Delta\\mu$ between the group centroids without changing any within-group slope. The dashed line connects the two centroids (the between-slope), and the solid line is the pooled OLS fit. As the centroids separate, the between channel dominates and the pooled fit rotates from $\\beta_{within} \\approx 2$ toward $\\beta_{between} \\approx 0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5)\nm <- 200\ndraw <- function(shift, main) {\n  xw <- rnorm(m, 0, 3);       yw <- 2 * xw + rnorm(m)\n  xs <- rnorm(m, shift, 0.2); ys <- rnorm(m)\n  x <- c(xw, xs); y <- c(yw, ys)\n  plot(x, y, pch = 16, cex = .5, col = c(rep(\"#9E431855\", m), rep(\"#0E6473\", m)),\n       xlab = \"x\", ylab = \"y\", main = main)\n  abline(v = mean(x), lty = 3, col = \"grey50\")\n  segments(mean(xw), mean(yw), mean(xs), mean(ys), lty = 2, lwd = 2, col = \"grey30\")\n  points(c(mean(xw), mean(xs)), c(mean(yw), mean(ys)), pch = 21, bg = \"white\", cex = 1.4)\n  abline(lm(y ~ x), lwd = 2, col = \"#0E6473\")\n  dmu <- mean(xs) - mean(xw)\n  Vb  <- 0.25 * dmu^2\n  Vw  <- 0.5 * (var(xs) + var(xw))\n  c(`Within Slope (movers)` = unname(coef(lm(yw ~ xw))[2]),\n    `Within Slope (steady)` = unname(coef(lm(ys ~ xs))[2]),\n    `Between Slope`      = unname((mean(ys) - mean(yw)) / dmu),\n    `Between Weight (%)` = 100 * Vb / (Vb + Vw),\n    `OLS Estimate`       = unname(coef(lm(y ~ x))[2]))\n}\nop <- par(mfrow = c(1, 3), mar = c(4, 3.5, 2.5, 0.5))\na <- draw(0,   expression(Delta*mu == 0))\nb <- draw(10,  expression(Delta*mu == 10))\nc_ <- draw(100, expression(Delta*mu == 100))\n```\n\n::: {.cell-output-display}\n![Pooled OLS as a within/between blend (@eq-pooled). Points are the two groups, open circles their centroids. The dashed line is the between-slope $\\beta_{between} = \\Delta\\bar y/\\Delta\\mu$ through the centroids; the solid line is the pooled fit $\\hat\\beta_{OLS}$. The within slopes are identical across panels; widening $\\Delta\\mu$ (left to right) inflates $V_{between}$ and rotates $\\hat\\beta_{OLS}$ toward $\\beta_{between}$.](interpreting-ols_files/figure-html/unnamed-chunk-11-1.png){width=1152}\n:::\n\n```{.r .cell-code}\npar(op)\nmtab(cbind(`$\\\\Delta\\\\mu = 0$` = a, `$\\\\Delta\\\\mu = 10$` = b, `$\\\\Delta\\\\mu = 100$` = c_), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                      | $\\Delta\\mu = 0$| $\\Delta\\mu = 10$| $\\Delta\\mu = 100$|\n|:---------------------|---------------:|----------------:|-----------------:|\n|Within Slope (movers) |           2.019|            2.009|             2.002|\n|Within Slope (steady) |           0.007|           -0.288|            -0.136|\n|Between Slope         |           0.882|           -0.007|            -0.006|\n|Between Weight (%)    |           0.026|           85.113|            99.833|\n|OLS Estimate          |           2.010|            0.291|            -0.002|\n\n\n\nPooled OLS as a within/between blend (@eq-pooled). Points are the two groups, open circles their centroids. The dashed line is the between-slope $\\beta_{between} = \\Delta\\bar y/\\Delta\\mu$ through the centroids; the solid line is the pooled fit $\\hat\\beta_{OLS}$. The within slopes are identical across panels; widening $\\Delta\\mu$ (left to right) inflates $V_{between}$ and rotates $\\hat\\beta_{OLS}$ toward $\\beta_{between}$.\n:::\n:::\n\n\nRead across the three columns. The within slopes barely change — about $2$ for the movers, indistinguishable from zero for the steady strip. What changes is the between weight: $0.03\\%$ when the centres coincide, $85\\%$ at $\\Delta\\mu = 10$, and $99.6\\%$ at $\\Delta\\mu = 100$. So the OLS fit falls from $2.01$ to $0.29$ to $0.02$ on identical true slopes.\n\nThe between slope reported in the first column is meaningless — and harmlessly so: with the centres nearly on top of each other $\\Delta\\mu \\approx 0$, an unstable ratio is multiplied by a vanishing weight and contributes nothing.\n\nThe strip has influence in the second and third panels despite barely moving. Influence is distance from the mean of $x$, and the strip sits $\\Delta\\mu$ units from it; what it contributes is not its slope but its position — it anchors one end of the dashed line.\n\nA group dummy removes that channel. Demeaning subtracts each cloud's *own* mean, sliding the shifted strip back to the centre, so every panel collapses onto the first — centroids coinciding. Run OLS on that and the solid fit swings back up to the within slope. That is all fixed effects is, and why its slope matches the leftmost panel's regardless of how far the strip had been pushed.\n\nSo \"the weight is how much $x$ moves\" is the demeaned case only. It is exact once unit effects are removed, and false in general, because with the halves at different levels of $x$ part of the fitted line is a comparison *between* them rather than a weighting of within-unit slopes.\n\n### When the weighting changes nothing\n\nThe previous two subsections showed variance weighting at its most consequential: FE estimated the movers' effect rather than the population average, and pooled OLS was dragged toward a between-slope of zero. The reader might conclude that unequal weighting is always a problem. It is not. The variance-weighted average equals the plain average whenever effects are unrelated to the weights. The weighting tilts the estimate only when units whose $x$ moves more have systematically different slopes — that is, when $b_i$ covaries with $w_i$.\n\nThe following two designs illustrate the distinction. Both draw $N = 1000$ units, $T = 6$ periods, with $\\text{sd}_i(x) \\sim U(0.2, 3)$ and $y_{it} = b_i x_{it} + \\alpha_i + \\varepsilon_{it}$. Both share the same $x$. What differs is how the true slopes $b_i$ relate to regressor volatility:\n\n- **(A) Unrelated:** $b_i \\sim N(1, 1)$, independent of $\\text{sd}_i(x)$.\n- **(B) Aligned:** $b_i = 1 + 0.8(\\text{sd}_i - 1.6)$, so the slope rises with volatility.\n\nBoth designs average to $\\bar b \\approx 1$. The question is whether the FE estimate — a variance-weighted average of the $b_i$ — differs from that plain average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nsdX <- runif(N, 0.2, 3)\n\npanel <- function(b) {\n  h   <- data.frame(id = rep(1:N, each = T),\n                    x  = rnorm(N * T, 0, rep(sdX, each = T)))\n  h$y <- rep(b, each = T) * h$x + rep(rnorm(N), each = T) + rnorm(N * T)\n  h\n}\ncompareAB <- function(h, b) {\n  w <- tapply(resid(feols(x ~ 1 | id, h))^2, h$id, sum)\n  c(`FE estimate`            = coef(feols(y ~ x | id, h))[[\"x\"]],\n    `true slopes, plain avg` = mean(b),\n    `true slopes, weighted`  = sum(w * b) / sum(w))\n}\n\nb1 <- rnorm(N, 1, 1)\nb2 <- 1 + 0.8 * (sdX - 1.6)\nh1 <- panel(b1); h2 <- panel(b2)\n\nmtab(cbind(`(A) unrelated` = compareAB(h1, b1),\n            `(B) aligned`   = compareAB(h2, b2)), 4)\n```\n\n::: {.cell-output-display}\n\n\n|                       | (A) unrelated| (B) aligned|\n|:----------------------|-------------:|-----------:|\n|FE estimate            |        0.9813|      1.5338|\n|true slopes, plain avg |        0.9716|      1.0140|\n|true slopes, weighted  |        0.9816|      1.5422|\n\n\n:::\n:::\n\n\nIn (A) all three numbers agree to within sampling noise: the weighting is there but costs nothing, because the slopes are independent of the weights. In (B) the FE estimate is $1.53$ while the plain average of the true slopes is $1.01$, and the weighted average, $1.54$, confirms what the estimator was tracking all along — it overweights the high-slope units precisely because they are the high-variance units.\n\nFE still removes confounding from the unit effects $\\alpha_i$ — that is its job, and it does it in both designs. What FE does not do is change the within-variance weighting. Even after demeaning, OLS leans on units whose $x$ moves more, and in design (B) those units happen to have higher slopes. The gap between the FE estimate and the plain average is not a failure of FE; it is what OLS does by construction, and it matters only when $b_i$ covaries with $\\text{Var}_i(x)$. Without knowing the true slopes, the problem is undetectable from the data alone — the FE estimate looks well-behaved, standard errors are fine, it is just consistently estimating a different parameter than the simple average.\n\n**Reweighting to recover the simple average.** The fix is weighted least squares. The FE weight on unit $i$ is proportional to its within-variance $\\hat\\sigma_i^2 = \\sum_t (x_{it} - \\bar x_i)^2$. Running WLS-FE with weight $1/\\hat\\sigma_i^2$ gives each unit equal influence, so the estimate converges to the simple average of slopes rather than the variance-weighted average. This is the logic behind Gibbons, Suárez Serrato, and Urbancic (2018), who formalize the reweighting to recover what they call the \"unit-average treatment effect,\" and it is the continuous analog of Słoczyński's reweighting in the binary case.\n\nThe trade-off is efficiency. The high-variance units are the ones whose slope is best estimated — their $x$ moves a lot, so there is real information there. Downweighting them inflates the standard error. We are giving up precision to change which parameter we estimate.\n\nThe table below adds the reweighted FE estimate to both designs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompareAB2 <- function(h, b) {\n  wvar <- tapply(resid(feols(x ~ 1 | id, h))^2, h$id, sum)\n  inv_w <- 1 / tapply(resid(feols(x ~ 1 | id, h))^2, h$id, mean)\n  h$rw <- rep(inv_w, each = T)\n  c(`FE estimate`            = coef(feols(y ~ x | id, h))[[\"x\"]],\n    `Reweighted FE`          = coef(feols(y ~ x | id, h, weights = ~rw))[[\"x\"]],\n    `true slopes, plain avg` = mean(b),\n    `true slopes, weighted`  = sum(wvar * b) / sum(wvar))\n}\n\nmtab(cbind(`(A) unrelated` = compareAB2(h1, b1),\n            `(B) aligned`   = compareAB2(h2, b2)), 4)\n```\n\n::: {.cell-output-display}\n\n\n|                       | (A) unrelated| (B) aligned|\n|:----------------------|-------------:|-----------:|\n|FE estimate            |        0.9813|      1.5338|\n|Reweighted FE          |        0.9781|      1.0240|\n|true slopes, plain avg |        0.9716|      1.0140|\n|true slopes, weighted  |        0.9816|      1.5422|\n\n\n:::\n:::\n\n\nIn (A) the reweighted estimate agrees with the standard FE estimate — reweighting changes nothing when effects are independent of variance. In (B) the reweighted estimate falls from $1.53$ back to near $1.01$, recovering the simple average. The price is a larger standard error, because we have deliberately downweighted the most informative units.\n\n## Summary\n\n1.  **Leverage weighting.** OLS weights each observation by regressor variance $\\tilde V_i^2 = (x_i - \\bar x)^2$ (@eq-wavg); units that vary more dominate the slope.\n2.  **What is being estimated.** Under heterogeneous slopes $b_i$, OLS estimates the variance-weighted parameter $\\sum_i w_i b_i / \\sum_i w_i$ (@eq-exact); it equals the ATE only when the $b_i$ are uncorrelated with the weights.\n3.  **Between-group bias in pooled OLS.** Without fixed effects, group-mean differences $\\Delta\\mu$ enter through $V_{between}\\,\\beta_{between}$ (@eq-pooled) and distort the within-unit parameter; demeaning removes them.\n4.  **When it matters.** The weighting always happens. It changes the answer only when effects are heterogeneous and the heterogeneity lines up with the weight. With homogeneous effects it does no harm; with heterogeneous effects the question is not whether OLS is weighting but whether we know what it weighted.\n\nEverything here is the *effect* reading — weights on the unobservable $\\beta_i$, answering what $\\hat\\beta$ estimates. The same FWL identity also weights the *observed* outcomes, a signed and fully computable combination that answers which rows drive the number and reaches, unchanged, into estimators far beyond OLS. That is the companion chapter, [Interpreting OLS: Outcome Weights](outcome-weights.qmd).\n",
    "supporting": [
      "interpreting-ols_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}