{
  "hash": "ddda633b58d5123a370f3b118189587e",
  "result": {
    "engine": "knitr",
    "markdown": "# Interpreting OLS: Outcome Weights\n\n\n\nThe companion chapter [Interpreting OLS: Effect Weights](interpreting-ols.qmd) read the OLS coefficient as a weighting of unobservable effects — it answered *whose* effect $\\hat\\beta$ estimates. The same Frisch–Waugh–Lovell identity reads a second way, as a weighting of the *observed* outcomes. This reading answers a different question — which rows drive $\\hat\\beta$, and in which direction — and, unlike the first, it is computable and generalises past OLS. This chapter follows it.\n\n## The other reading of FWL\n\nResidualise the regressor of interest $V$ on the controls $X$, write $\\tilde V_i$ for the residual, and recall the residual-on-residual form of the coefficient, @eq-fwl:\n\n$$ \\hat\\beta = \\frac{\\sum_{i=1}^n \\tilde V_i y_i}{\\sum_{i=1}^n \\tilde V_i^2}. $$ {#eq-outcome-weights-1}\n\nThe previous chapter grouped each $\\tilde V_i$ with $V_i$ and read $\\hat\\beta$ as a weighting $w_i = \\tilde V_i V_i$ of effects (@eq-weff). Group $\\tilde V_i$ with $y_i$ instead — pairing each residual with its own outcome in the numerator — and the *same* expression is a linear combination of the observed outcomes:\n\n$$ \\hat\\beta = \\sum_{i=1}^n \\omega_i y_i, \\qquad \\omega_i = \\frac{\\tilde V_i}{\\sum_{j=1}^n \\tilde V_j^2}. $$ {#eq-omega}\n\n@eq-omega is the same algebra rearranged, but a different object from the effect weights.\n\n| | Weights on outcomes $\\omega_i$ | Weights on effects $w_i$ |\n|---|---|---|\n| Weights what | the observed $y_i$ | that observation's own effect $\\beta_i$ |\n| Sign | signed, sums to zero | non-negative (under saturation) |\n| Computable | yes, $y$ is observed | no, the $\\beta_i$ are never seen |\n| Holds when | always, it is algebra | in expectation; per-unit needs saturation |\n| Answers | which rows drive $\\hat\\beta$, any wrong sign | is this the effect I meant, whose effect |\n\nTwo constraints pin $\\omega_i$ down, both from @eq-omega. An intercept among the controls makes $\\sum_i \\tilde V_i = 0$, so the weights **sum to zero**. And $\\sum_i \\tilde V_i V_i = \\sum_i \\tilde V_i^2$ makes the weighted regressor **sum to one**, $\\sum_i \\omega_i V_i = 1$.\n\nUse this reading when overlap is in doubt and a row may enter with the wrong sign — which the non-negative $w_i$ cannot show. Keep the effect reading for questions about the estimand.\n\n## What the outcome weights look like\n\nTake the simple regression of $y$ on $x$ with an intercept, so $\\tilde V_i = x_i - \\bar x = d_i$ and\n\n$$ \\omega_i = \\frac{d_i}{\\sum_j d_j^2}. $$ {#eq-outcome-weights-2}\n\nUnlike the effect weights $w_i = d_i^2$ — non-negative, growing with the *square* of distance — this is **linear in $d_i$, and so signed**: a point left of $\\bar x$ enters $\\hat\\beta$ with a negative coefficient on its outcome, a point right of it positive. It is not a slope and does not involve $\\bar y$; it is simply a signed weight on the observed $y_i$.\n\n**Simulation — simple regression.** To see it, we simulate $n = 100$ points — regressor $x_i \\sim N(5, 2^2)$ and outcome $y_i = 2 x_i + \\varepsilon_i$ with $\\varepsilon_i \\sim N(0, 3^2)$ — then size each point by $|\\omega_i|$ and colour it by sign.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nn <- 100; x <- rnorm(n, 5, 2); y <- 2 * x + rnorm(n, 0, 3)\nxb <- mean(x); d <- x - xb; om <- d / sum(d^2); col <- ifelse(om >= 0, teal, rust)\nR <- d > 0; L <- d < 0\nxR <- sum(abs(d[R]) * x[R]) / sum(abs(d[R])); yR <- sum(abs(d[R]) * y[R]) / sum(abs(d[R]))\nxL <- sum(abs(d[L]) * x[L]) / sum(abs(d[L])); yL <- sum(abs(d[L]) * y[L]) / sum(abs(d[L]))\nplot(x, y, pch = 16, cex = 0.35 + 2 * abs(om) / max(abs(om)),\n     col = paste0(col, \"99\"), xlab = \"x\", ylab = \"y\", main = \"N = 100 Points\")\nabline(v = xb, lty = 3, col = \"grey55\")\nabline(lm(y ~ x), lwd = 1.3, lty = 2, col = \"grey55\")\nsegments(xL, yL, xR, yR, lwd = 2.6, col = \"grey15\")\npoints(c(xL, xR), c(yL, yR), pch = 21, bg = c(rust, teal), col = \"white\", cex = 2.3, lwd = 2)\n```\n\n::: {.cell-output-display}\n![Outcome weights in a 100-point sample. Each small point's **size scales with its weight** $|\\omega_i|$, coloured by sign — teal ($\\omega_i > 0$) pushes $\\hat\\beta$ up, rust ($\\omega_i < 0$) pulls it down; the dotted line is the fulcrum $x = \\bar x$. The two large dots are the $|d|$-weighted centroids of the points left and right of $\\bar x$; the solid segment joining them has slope $\\hat\\beta$, and the dashed line is the OLS fit (same slope, shifted through the grand mean).](outcome-weights_files/figure-html/unnamed-chunk-2-1.png){width=624}\n:::\n\n```{.r .cell-code}\nvtab(c(`sum(omega)`   = sum(om),      `sum(omega*x)` = sum(om * x),\n        `positive mass` = sum(om[om > 0]), `negative mass` = sum(om[om < 0]),\n        `OLS`          = coef(lm(y ~ x))[[2]], `sum(omega*y)` = sum(om * y)), 4)\n```\n\n::: {.cell-output-display}\n\n\n|              |   value|\n|:-------------|-------:|\n|sum(omega)    |  0.0000|\n|sum(omega*x)  |  1.0000|\n|positive mass |  0.2486|\n|negative mass | -0.2486|\n|OLS           |  1.8648|\n|sum(omega*y)  |  1.8648|\n\n\n\nOutcome weights in a 100-point sample. Each small point's **size scales with its weight** $|\\omega_i|$, coloured by sign — teal ($\\omega_i > 0$) pushes $\\hat\\beta$ up, rust ($\\omega_i < 0$) pulls it down; the dotted line is the fulcrum $x = \\bar x$. The two large dots are the $|d|$-weighted centroids of the points left and right of $\\bar x$; the solid segment joining them has slope $\\hat\\beta$, and the dashed line is the OLS fit (same slope, shifted through the grand mean).\n:::\n:::\n\n\nThe printed sums confirm @eq-omega: the weights split at $\\bar x$ into a positive mass ($\\approx +0.25$) and an equal negative one ($\\approx -0.25$), and $\\sum_i \\omega_i x_i = 1$.\n\nBut the figure shows more. Split the points at $\\bar x$, weight each side by $|d_i|$, and take its centroid — the two large dots. **The segment joining them has slope $\\hat\\beta$:** the OLS slope is the rise over run between the low-$x$ and high-$x$ weighted centres.\n\nThe dashed fit shares that slope, shifted through the grand mean, so the two coincide only when the sides balance. This collapse to two points falls out of the slope formula.\n\n### Why it collapses to two points\n\nWrite $d_i = x_i - \\bar x$. Because $\\sum_i d_i = 0$, the positive and negative sides carry equal total weight $W = \\sum_{i: d_i > 0} d_i$. An inner product with $d$ is therefore a between-group contrast: for any variable $v$,\n\n$$ d \\cdot v = W(\\bar v_R - \\bar v_L), $$ {#eq-outcome-weights-4}\n\nwhere $\\bar v_R$ and $\\bar v_L$ are the $|d_i|$-weighted means on each side of $\\bar x$. The slope $\\hat\\beta = d \\cdot y\\, /\\, d \\cdot x$ is the ratio of two such contrasts; $W$ cancels:\n\n$$ \\hat\\beta = \\frac{\\bar y_R - \\bar y_L}{\\bar x_R - \\bar x_L}. $$ {#eq-outcome-weights-5}\n\nThat is the rise over run between the two $|d|$-weighted centroids — the two dots in the figure.\n\n## When the sign flips\n\nIn simple regression the sign of $\\omega_i$ is just the side of the mean: half the weights are negative, structurally, and a low-$x$ point *should* count against a high-$x$ one. With controls $\\tilde V_i$ becomes a *residual*, and a row can flip to the sign its raw position denies — a hidden extrapolation the non-negative $w_i$ can never show.\n\nWith a binary treatment $D$ and covariate $x$, the weight $\\omega_i \\propto \\tilde V_i = D_i - \\hat D_i$, with $\\hat D$ the linear projection of $D$ on $(1, x)$. Regressed on $D$ alone, every treated unit is positive and every control negative — the *structural* pattern, producing $\\hat\\beta = \\bar y_1 - \\bar y_0$. Add $x$ and the fitted $\\hat D_i$ can leave $[0, 1]$ where treatment and control barely overlap: a treated unit with $\\hat D_i > 1$ gets $\\tilde V_i < 0$, so its outcome is subtracted from $\\hat\\beta$ — a *wrong-sign* weight that the non-negative $\\tilde V_i^2$ hides. The test is one line: **fit the treatment on the controls; any $\\hat D_i \\notin [0, 1]$ is an extrapolated, wrong-sign unit** — a point where the groups fail to overlap. (With a continuous regressor there is no bounded range to leave; overlap is read from leverage, not sign.)\n\nA wrong-sign weight is extrapolation: the model reaches outside common support, and $\\hat\\beta$ can leave the convex hull of the observed outcomes. Whether it matters depends on the data — a sensitivity check is one trim away.\n\n**Simulation — thin overlap on a curved baseline.** The DGP: 150 controls near $x = 2.5$ and 150 treated near $x = 4.5$ (both sd $1.1$), with $y_i = D_i + 0.8\\,(x_i - 3.5)^2 + 0.3\\,x_i + \\varepsilon_i$, $\\varepsilon_i \\sim N(0, 0.5^2)$ — a constant true effect of $1$ sitting on a convex baseline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nn <- 150\nx <- c(rnorm(n, 2.5, 1.1), rnorm(n, 4.5, 1.1))\nd <- c(rep(0, n), rep(1, n))\ny <- 1.0 * d + 0.8 * (x - 3.5)^2 + 0.3 * x + rnorm(2 * n, 0, 0.5)\ndf <- data.frame(y, d, x)\nX <- cbind(1, x); dh <- as.vector(X %*% solve(crossprod(X)) %*% t(X) %*% d)\nflag <- (d == 1 & dh > 1) | (d == 0 & dh < 0)\npch <- ifelse(d == 1, 17, 16); col <- ifelse(d == 1, teal, rust)\nplot(x, y, type = \"n\", xlab = \"x\", ylab = \"y\")\nxs <- seq(min(x), max(x), length = 200)\nmc <- function(z) 0.8 * (z - 3.5)^2 + 0.3 * z              # true control mean E[y | x, D = 0]\nlines(xs, mc(xs),     col = rust, lwd = 2.4)               # control mean\nlines(xs, mc(xs) + 1, col = teal, lwd = 2.4, lty = 3)      # treated mean = control + true effect (1)\npoints(x, y, pch = pch, col = paste0(col, \"88\"), cex = 0.85)               # all points, by group\npoints(x[flag], y[flag], pch = 1, col = \"grey15\", cex = 1.7, lwd = 1.4)    # ring the flagged units\narrows(3.5, mc(3.5), 3.5, mc(3.5) + 1, code = 3, length = 0.05, angle = 90, lwd = 2.4, col = \"grey10\")\nsegments(3.5, mc(3.5) + 0.5, 2.05, 13.3, col = \"grey55\", lwd = 1)\ntext(2.0, 14, \"gap = true effect = 1\", pos = 4, cex = 0.82, col = \"grey10\")\nlegend(\"bottomright\", bty = \"n\", cex = 0.82,\n       legend = c(\"control\", \"treated\", \"flagged (trimmed)\", \"control mean\", \"treated mean\"),\n       pch = c(16, 17, 1, NA, NA), lty = c(NA, NA, NA, 1, 3),\n       col = c(rust, teal, \"grey15\", rust, teal))\n```\n\n::: {.cell-output-display}\n![Thin overlap on a convex baseline. The two curves are the true means — control (rust, solid) and treated (teal, dotted), a constant $1$ apart (arrow). Controls sit low on the curve and treated high; the groups share only the middle. Ringed points are wrong-sign units — $\\hat D_i \\notin [0, 1]$ — where the groups fail to overlap. The straight $y \\sim D + x$ reports $\\hat\\beta = 0.69$; dropping the flagged units, or reweighting to the overlap, restores $\\approx 1$.](outcome-weights_files/figure-html/unnamed-chunk-3-1.png){width=595.2}\n:::\n\n```{.r .cell-code}\nw_ato <- WeightIt::weightit(d ~ x, data = df, method = \"glm\", estimand = \"ATO\")\nvtab(c(`flagged units`      = sum(flag),\n        `beta (full)`        = coef(lm(y ~ d + x))[[\"d\"]],\n        `beta (trimmed)`     = coef(lm(y ~ d + x, data = df[!flag, ]))[[\"d\"]],\n        `beta (overlap-wtd)` = coef(lm(y ~ d + x, weights = w_ato$weights))[[\"d\"]]), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                   |  value|\n|:------------------|------:|\n|flagged units      | 37.000|\n|beta (full)        |  0.688|\n|beta (trimmed)     |  0.991|\n|beta (overlap-wtd) |  0.979|\n\n\n\nThin overlap on a convex baseline. The two curves are the true means — control (rust, solid) and treated (teal, dotted), a constant $1$ apart (arrow). Controls sit low on the curve and treated high; the groups share only the middle. Ringed points are wrong-sign units — $\\hat D_i \\notin [0, 1]$ — where the groups fail to overlap. The straight $y \\sim D + x$ reports $\\hat\\beta = 0.69$; dropping the flagged units, or reweighting to the overlap, restores $\\approx 1$.\n:::\n:::\n\n\nThirty-seven units carry the wrong sign, all in the non-overlapping tails. Trim them and $\\hat\\beta$ jumps from $0.69$ to $0.99$; the overlap weights (`\"ATO\"`, Li, Morgan, and Zaslavsky 2018) give $0.98$. Either fix confirms the estimate leaned on the extrapolation, read off the regression itself with no separate model. Had the outcome been linear, the same trim would barely move $\\hat\\beta$: the wrong-sign weights are still there, but they are harmless. The check tells you which case you are in.\n\nThis is the implied-weights diagnostic of Chattopadhyay and Zubizarreta (2023); their `lmw` package computes the weights and the balance, extrapolation, and influence diagnostics built on them, and `OutcomeWeights` (Knaus 2024) carries it to machine-learning estimators. The mainstream overlap check takes the other route, through the propensity score (`WeightIt` for estimation, `cobalt` for balance, and Crump et al. 2009 for trimming); both routes reach the same conclusion.\n\n## Out of OLS: the same weights beyond the linear model\n\nThe outcome reading has one advantage the effect reading lacks: it survives leaving OLS. Any estimator that can be written $\\hat\\tau = \\sum_i \\omega_i Y_i = \\boldsymbol\\omega' \\boldsymbol Y$ — a linear combination of the observed outcomes — *has* outcome weights, whatever machinery produced them.\n\nKnaus (2024) makes this the organising idea, and his `OutcomeWeights` package computes $\\boldsymbol\\omega$ for AIPW, double machine learning, and the causal forest.\n\n### The weights, derived\n\nThe OLS outcome weights (@eq-omega) followed from one fact: in the FWL numerator $\\sum_i \\tilde V_i y_i$, the outcome $y_i$ appears once, linearly, so $\\hat\\beta = \\sum_i \\omega_i y_i$ with $\\omega_i = \\tilde V_i / \\sum_j \\tilde V_j^2$. The same fact holds whenever the outcome model is a *smoother* — a map $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$ that is linear in the training outcomes. Substituting $\\boldsymbol S \\boldsymbol Y$ for $\\hat{\\boldsymbol m}$ keeps $\\boldsymbol Y$ linear in the numerator, and reading off its coefficient gives $\\boldsymbol\\omega$. We carry this out for PLR and AIPW.\n\n*PLR.* Take the partially-linear estimator (the R-learner behind the causal forest). It is FWL with the projections done by a flexible learner: residualise treatment and outcome on the covariates, then regress one residual on the other,\n\n$$ \\hat\\tau = \\frac{\\sum_i (D_i - \\hat e_i)(Y_i - \\hat m_i)}{\\sum_i (D_i - \\hat e_i)^2}, $$ {#eq-outcome-weights-6}\n\nwith $\\hat e = \\hat E[D \\mid X]$ and $\\hat m = \\hat E[Y \\mid X]$ the fitted nuisances.\n\nThe outcome nuisance is a *smoother*: its fitted values are a linear map of the training outcomes, $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$ — true for OLS, ridge, kernels, and honest forests alike. So the outcome residual is $\\boldsymbol Y - \\hat{\\boldsymbol m} = (\\mathbf I - \\boldsymbol S)\\boldsymbol Y$. Writing $\\tilde{\\boldsymbol D} = \\boldsymbol D - \\hat{\\boldsymbol e}$ for the treatment residual and substituting,\n\n$$ \\hat\\tau = \\frac{\\tilde{\\boldsymbol D}'(\\mathbf I - \\boldsymbol S)\\,\\boldsymbol Y}{\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}}. $$ {#eq-outcome-weights-7}\n\nNow $\\boldsymbol Y$ appears once, linearly, in the numerator. Read off its coefficient and the weights are done:\n\n$$ \\hat\\tau = \\boldsymbol\\omega'\\boldsymbol Y, \\qquad \\boldsymbol\\omega' = \\frac{\\tilde{\\boldsymbol D}'(\\mathbf I - \\boldsymbol S)}{\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}}. $$ {#eq-omega-ml}\n\nThat is @eq-omega — the OLS weights — with the projection annihilator $\\boldsymbol M_X$ replaced by the smoother annihilator $\\mathbf I - \\boldsymbol S$. OLS is the case of a linear learner, $\\boldsymbol S = \\boldsymbol P_X$: there $\\boldsymbol S$ is a projection, $\\mathbf I - \\boldsymbol S = \\boldsymbol M_X$, and @eq-omega-ml is @eq-omega exactly. Component by component, the weight on observation $i$ is\n\n$$ \\omega_i = \\frac{\\tilde D_i - \\sum_j S_{ji}\\,\\tilde D_j}{\\sum_k \\tilde D_k^2}: $$ {#eq-omega-plr-i}\n\nthe treatment residual of unit $i$, minus how much other units' treatment residuals leak to $i$ through the outcome smoother, normalised by the total treatment-residual variance.\n\nThe outcome weights tell which rows drive the estimate; the *effect* weights tell whose effect it estimates. Substitute $Y_i = \\tau_i D_i + m(X_i) + \\varepsilon_i$ into the PLR numerator. With consistent nuisances $\\hat m \\approx m$, the noise vanishes in expectation and the numerator reduces to $\\sum_i \\tilde D_i D_i \\tau_i$, so the effect weight on $\\tau_i$ is $\\tilde D_i D_i = (D_i - e_i) D_i$. Since $D$ is binary ($D_i^2 = D_i$),\n\n$$ E[\\tilde D_i D_i \\mid X_i] = E[D_i \\mid X_i] - e_i\\, E[D_i \\mid X_i] = e_i - e_i^2 = e_i(1 - e_i). $$ {#eq-outcome-weights-8}\n\nThe denominator $\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D} = \\sum_i \\tilde D_i^2$ has the same expectation, $\\sum_i e_i(1 - e_i)$, since $\\text{Var}(D_i \\mid X_i) = e_i(1 - e_i)$. Both numerator and denominator weight by propensity variance, and the ratio is the variance-weighted average treatment effect,\n\n$$ \\tau_{\\text{VWATE}} = \\frac{\\sum_i e(X_i)(1 - e(X_i))\\,\\tau(X_i)}{\\sum_i e(X_i)(1 - e(X_i))}, $$ {#eq-vwate}\n\nnot the plain ATE $\\bar\\tau = n^{-1}\\sum_i \\tau_i$. The two coincide only when effects are constant or treatment is randomly assigned. The weighting is the same $e(1-e)$ that appeared in the previous chapter's @eq-angrist, where Angrist (1998) showed OLS with saturated strata weights each stratum by $n_x \\hat D(x)(1 - \\hat D(x))$. That result required discrete strata and saturated controls; @eq-vwate is the same propensity-variance weighting with continuous covariates and a flexible learner. The individual $\\tau(X_i)$ are never observed or estimated — they are the structural unit-level effects in $Y_i = \\tau(X_i) D_i + m(X_i) + \\varepsilon_i$. PLR returns one number, $\\hat\\tau$, that converges to their $e(1-e)$-weighted average; to estimate $\\tau(X_i)$ itself one needs a CATE estimator (a causal forest, say).\n\nThree moves did it: write the estimator, substitute the smoother $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$, read off the coefficient on $\\boldsymbol Y$. They work for any estimator built from smoothers; only the operator on $\\boldsymbol Y$ changes. AIPW is worth carrying through, because its operator is more than $\\mathbf I - \\boldsymbol S$.\n\n*AIPW.* With outcome smoothers $\\hat{\\boldsymbol\\mu}_1 = \\boldsymbol S_1 \\boldsymbol Y$, $\\hat{\\boldsymbol\\mu}_0 = \\boldsymbol S_0 \\boldsymbol Y$ and propensity $\\hat{\\boldsymbol e}$, the score of unit $i$ is\n\n$$ \\psi_i = \\hat\\mu_{1i} - \\hat\\mu_{0i} + \\frac{D_i}{\\hat e_i}\\,(Y_i - \\hat\\mu_{1i}) - \\frac{1 - D_i}{1 - \\hat e_i}\\,(Y_i - \\hat\\mu_{0i}), \\qquad \\hat\\tau = \\frac1n \\sum_i \\psi_i. $$ {#eq-outcome-weights-9}\n\nEach $\\hat\\mu_{ji}$ is $(\\boldsymbol S_j \\boldsymbol Y)_i$, so $\\boldsymbol Y$ again enters only linearly; collecting its coefficient gives $\\hat\\tau = \\boldsymbol\\omega' \\boldsymbol Y$ with\n\n$$ \\boldsymbol T = \\boldsymbol S_1 - \\boldsymbol S_0 + \\operatorname{diag}\\!\\Big(\\tfrac{\\boldsymbol D}{\\hat{\\boldsymbol e}}\\Big)(\\mathbf I - \\boldsymbol S_1) - \\operatorname{diag}\\!\\Big(\\tfrac{1 - \\boldsymbol D}{1 - \\hat{\\boldsymbol e}}\\Big)(\\mathbf I - \\boldsymbol S_0), \\qquad \\boldsymbol\\omega' = \\frac{\\mathbf 1' \\boldsymbol T}{n}. $$ {#eq-outcome-weights-10}\n\nThat is, $\\omega_j$ is the $j$-th column-sum of $\\boldsymbol T$ divided by $n$: observation $j$'s outcome enters the ATE through its direct IPW term and through its indirect contribution via the two outcome smoothers $\\boldsymbol S_1$, $\\boldsymbol S_0$ to every other unit's augmentation correction.\n\nComparing the two:\n\n| | PLR (@eq-omega-ml) | AIPW |\n|---|---|---|\n| Matrix form | $\\boldsymbol\\omega' = \\tilde{\\boldsymbol D}'(\\mathbf I - \\boldsymbol S)\\,/\\,\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}$ | $\\boldsymbol\\omega' = \\mathbf 1'\\boldsymbol T\\,/\\,n$ |\n| Per unit | $\\omega_i = \\bigl(\\tilde D_i - \\sum_j S_{ji}\\tilde D_j\\bigr)\\,/\\,\\sum_k \\tilde D_k^2$ | $\\omega_j = \\frac{1}{n}\\sum_i T_{ij}$ |\n| Smoother | one $\\boldsymbol S$ (outcome on $X$) | two: $\\boldsymbol S_1$ (treated), $\\boldsymbol S_0$ (control) |\n| Normalisation | treatment-residual variance | sample size $n$ |\n\nBoth follow the same recipe — substitute the smoother $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$, read off $\\boldsymbol Y$'s coefficient — and differ only in the operator acting on $\\boldsymbol Y$.\n\n**Simulation — heterogeneous effects (DML).** Under a heterogeneous effect the two estimators diverge, and the weights show why. We simulate $n = 2000$ units: five standard-normal covariates $X$, selection $W_i \\sim \\text{Bernoulli}(\\Lambda(-1 + 1.2\\,X_{i1}))$ with $\\Lambda$ the logistic function (treatment is scarce and tied to $X_1$), and outcome $Y_i = \\tau_i W_i + X_{i1} + 0.5\\,X_{i2} + \\varepsilon_i$ with an effect $\\tau_i = 1 + X_{i1}$ that varies across units — a $W \\times X_1$ interaction. The average effect is $E[\\tau] = 1$, but units with larger $X_1$ have larger effects. `dml_with_smoother` returns a partially-linear (PLR) and an AIPW estimator; `get_outcome_weights` extracts the weight matrix $\\boldsymbol\\omega$, one row per estimator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(OutcomeWeights)\nset.seed(1)\nn <- 2000; p <- 5\nX <- matrix(rnorm(n * p), n, p)\netrue <- plogis(-1 + 1.2 * X[, 1])                       # asymmetric selection on X1\nW <- rbinom(n, 1, etrue)\ntau <- 1 + X[, 1]                                        # heterogeneous effect: W x X1\nY <- tau * W + X[, 1] + 0.5 * X[, 2] + rnorm(n)\ndml <- dml_with_smoother(Y, W, X, estimators = c(\"PLR\", \"AIPW_ATE\"))\nom  <- get_outcome_weights(dml)                          # om$omega: 2 x n, om$treat = W\ninvisible(capture.output(s <- summary(dml)))\nW1 <- om$treat == 1\ntab <- t(sapply(rownames(om$omega), function(nm) {\n  w <- om$omega[nm, ]\n  c(estimate = s[nm, 1], `omega %*% Y` = sum(w * Y),\n    treated = sum(w[W1]), control = sum(w[!W1]))\n}))\nov <- etrue * (1 - etrue)                                # e(1-e): PLR's per-unit weight\n# ATE = plain mean of tau; overlap-ATE = e(1-e)-weighted mean of tau (PLR's target)\ncat(sprintf(\"true ATE = %.2f   true overlap-ATE = %.2f\\n\", mean(tau), sum(ov * tau) / sum(ov)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntrue ATE = 0.99   true overlap-ATE = 1.31\n```\n\n\n:::\n\n```{.r .cell-code}\nmtab(tab, 3)\n```\n\n::: {.cell-output-display}\n\n\n|         | estimate| omega %*% Y| treated| control|\n|:--------|--------:|-----------:|-------:|-------:|\n|PLR      |    1.287|       1.287|   0.997|  -0.997|\n|AIPW-ATE |    1.074|       1.074|   1.000|  -1.000|\n\n\n:::\n:::\n\n\nTwo things stand out. First, the estimators now *disagree* — PLR reports $1.29$, AIPW $1.07$ — and neither is wrong; they target different populations. PLR targets the VWATE (@eq-vwate), not the ATE. Here treatment selection loads on $X_1$ through $e = \\Lambda(-1 + 1.2\\,X_1)$, and $\\tau = 1 + X_1$ also rises in $X_1$, so the units PLR overweights — those with $e$ near $\\tfrac12$, around $X_1 \\approx 0.8$ — carry above-average effects, pushing PLR's estimate above the true ATE. AIPW instead reweights by $1/e$ and $1/(1-e)$ to undo selection, returning the plain average, the ATE ($\\approx 1$). Same outcomes $\\boldsymbol Y$, weighted two ways, two population-averages of $\\tau$ — and the weights are what make the difference visible.\n\nSecond, the weights still reproduce each estimate exactly and sum to zero overall. They part on the other constraint from §1, $\\sum_i \\omega_i V_i = 1$: for a binary treatment that constraint is the treated weights summing to $+1$ (and, with the zero total, controls to $-1$). AIPW keeps it exactly; the partially-linear estimator sums to $\\pm 0.99$, quietly breaking the within-group budget that OLS and AIPW hold.\n\nThat divergence shows what the representation is for. In Knaus's (2024) framing $\\boldsymbol\\omega$ does three things: it puts OLS, IPW, AIPW, DML, and the causal forest on **one footing** ($\\boldsymbol\\omega' \\boldsymbol Y$); it **characterises the target population** each reports — the PLR-versus-AIPW gap above; and it **checks covariate balance** via `cobalt`, flagging when weights break a property usually assumed — the sum-to-$\\pm 1$ within treated and control groups that PLR violates here.\n\nThe formulas take a few lines to check against the package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn  <- length(Y)\nS  <- dml$NuPa.hat$smoothers$S[1, , ]\nS1 <- dml$NuPa.hat$smoothers$S.d1[1, , ]\nS0 <- dml$NuPa.hat$smoothers$S.d0[1, , ]\ne  <- dml$NuPa.hat$predictions$D.hat[, 1]\nWtil   <- W - e\nom_plr <- as.numeric((Wtil - crossprod(S, Wtil)) / sum(Wtil^2))\nImat    <- diag(n)\nTm      <- S1 - S0 + (W / e) * (Imat - S1) - ((1 - W) / (1 - e)) * (Imat - S0)\nom_aipw <- colSums(Tm) / n\nvtab(c(`PLR:  max |by hand - package|` = max(abs(om_plr  - om$omega[\"PLR\", ])),\n       `AIPW: max |by hand - package|` = max(abs(om_aipw - om$omega[\"AIPW-ATE\", ])),\n       `PLR:  omega' Y`                = sum(om_plr  * Y),\n       `AIPW: omega' Y`                = sum(om_aipw * Y)), 4)\n```\n\n::: {.cell-output-display}\n\n\n|                                        |  value|\n|:---------------------------------------|------:|\n|PLR:  max &#124;by hand - package&#124; | 0.0000|\n|AIPW: max &#124;by hand - package&#124; | 0.0000|\n|PLR:  omega' Y                          | 1.2873|\n|AIPW: omega' Y                          | 1.0738|\n\n\n:::\n:::\n\n\n### Two uses: balance and extrapolation\n\nHaving $\\boldsymbol\\omega$, two checks run directly on it. Does the estimator's implied weighting balance the covariates? Hand $\\boldsymbol\\omega$ to `cobalt` and read the largest standardised mean difference. And is it extrapolating? Count the wrong-sign weights — a control with $\\omega_i > 0$ or a treated unit with $\\omega_i < 0$, the §3 signature of a comparison reaching off common support.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cobalt)\nuses <- t(sapply(rownames(om$omega), function(nm) {\n  w <- om$omega[nm, ]\n  c(`max |SMD|`        = max(abs(bal.tab(as.data.frame(X), treat = W, weights = w)$Balance$Diff.Adj)),\n    `wrong-sign units` = sum((om$treat == 1 & w < 0) | (om$treat == 0 & w > 0)))\n}))\nmtab(uses, 3)\n```\n\n::: {.cell-output-display}\n\n\n|         | max &#124;SMD&#124;| wrong-sign units|\n|:--------|-------------------:|----------------:|\n|PLR      |               0.025|               21|\n|AIPW-ATE |               0.091|                0|\n\n\n:::\n:::\n\n\nRaw, the groups are badly imbalanced — the largest covariate SMD is $1.11$, since treatment was tied to $X_1$. Both weightings pull it down to near zero ($0.03$ for PLR, $0.09$ for AIPW): each balances the covariates, which for a causal forest you could not otherwise check.\n\nThey differ on extrapolation. PLR carries 21 wrong-sign controls — it leans slightly off common support — while AIPW carries none. Neither is disqualifying here; the point is that balance and extrapolation are now *checkable*, on estimators that never exposed a weighting.\n\n## The DiD setting\n\nWhen the regressor is a treatment indicator, every unit in a group gets the same weight, so $\\hat\\beta$ reduces to a contrast of group means. Regressed on the treatment alone it is the difference in means between treated and control. Add a time period and its interaction with treatment and it becomes a difference-in-differences across four group-by-period cells. We take these in turn, then bring in covariates.\n\n**Simulation — treatment alone.** Regress $y$ on the treatment $D$ alone — here 30 treated drawn $y \\sim N(5, 1)$ and 50 controls $y \\sim N(2, 1)$. The residual $\\tilde V_i = D_i - \\bar D$ is constant within each group, so the weight is uniform within a group and $\\hat\\beta$ reduces to the two group means: $\\hat\\beta = \\bar y_1 - \\bar y_0$, the difference in means. Every treated unit then carries positive weight, every control negative — the structural pattern of the previous section, with the wrong-sign off-diagonal empty until covariates enter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nn1 <- 30; n0 <- 50\nd <- c(rep(1, n1), rep(0, n0)); y <- c(rnorm(n1, 5), rnorm(n0, 2))\ndev <- d - mean(d); om <- dev / sum(dev^2); col <- ifelse(om >= 0, teal, rust)\ny1 <- mean(y[d == 1]); y0 <- mean(y[d == 0])\nplot(jitter(d, 0.4), y, pch = 16, col = paste0(col, \"55\"), cex = 0.9,\n     xlim = c(-0.3, 1.3), xaxt = \"n\", xlab = \"\", ylab = \"y\", main = \"Regression on treatment\")\naxis(1, at = c(0, 1), labels = c(\"control\", \"treated\"))\nsegments(0, y0, 1, y1, lwd = 2.6, col = \"grey15\")\npoints(c(0, 1), c(y0, y1), pch = 21, bg = c(rust, teal), col = \"white\", cex = 2.5, lwd = 2)\n```\n\n::: {.cell-output-display}\n![Regression on the treatment alone. Points are the two groups (rust control, teal treated); the large dots are the group means, and the segment joining them has slope $\\hat\\beta = \\bar y_1 - \\bar y_0$, the difference in means.](outcome-weights_files/figure-html/unnamed-chunk-7-1.png){width=480}\n:::\n\n```{.r .cell-code}\nvtab(c(`beta (lm)` = coef(lm(y ~ d))[[\"d\"]], `y1 - y0` = y1 - y0,\n        `off-diagonal weights` = sum((d == 1 & om < 0) | (d == 0 & om > 0))), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                     | value|\n|:--------------------|-----:|\n|beta (lm)            | 3.318|\n|y1 - y0              | 3.318|\n|off-diagonal weights | 0.000|\n\n\n\nRegression on the treatment alone. Points are the two groups (rust control, teal treated); the large dots are the group means, and the segment joining them has slope $\\hat\\beta = \\bar y_1 - \\bar y_0$, the difference in means.\n:::\n:::\n\n\nThe estimate equals $\\bar y_1 - \\bar y_0$, and no weight carries the wrong sign — the off-diagonal count is zero.\n\n**Simulation — 2×2 difference-in-differences.** Add a period and interact it with the group, and the design has four cells. Each collapses to its mean, and the interaction coefficient is their double contrast,\n\n$$ \\widehat{\\text{DiD}} = (\\bar y_{T,\\text{post}} - \\bar y_{T,\\text{pre}}) - (\\bar y_{C,\\text{post}} - \\bar y_{C,\\text{pre}}). $$ {#eq-outcome-weights-11}\n\nNow there are four cell means, and with them four slopes — the two group trends over time and the two cross-sectional gaps. The DiD is the difference between either parallel pair, trend minus trend or gap minus gap. We simulate 200 units in each group×period cell from $y = 3 + 2g + p + 2\\,(g \\cdot p) + \\varepsilon$, so the true DiD (the interaction) is $2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\ng <- rep(c(1, 1, 0, 0), each = 200); p <- rep(c(0, 1, 0, 1), each = 200)\ny <- 3 + 2 * g + 1 * p + 2 * (g * p) + rnorm(800)\nm <- tapply(y, list(g, p), mean)\nTpre <- m[\"1\", \"0\"]; Tpost <- m[\"1\", \"1\"]; Cpre <- m[\"0\", \"0\"]; Cpost <- m[\"0\", \"1\"]\ncf <- Tpre + (Cpost - Cpre)\nplot(NA, xlim = c(-0.15, 1.25), ylim = range(y), xaxt = \"n\", xlab = \"\", ylab = \"y\",\n     main = \"Difference-in-differences\")\naxis(1, at = c(0, 1), labels = c(\"pre\", \"post\"))\nsegments(0, Tpre, 1, Tpost, lwd = 2.4, col = teal)\nsegments(0, Cpre, 1, Cpost, lwd = 2.4, col = rust)\nsegments(0, Tpre, 1, cf, lty = 2, lwd = 1.6, col = \"grey55\")\nsegments(1, cf, 1, Tpost, lwd = 4, col = \"grey15\")\npoints(c(0, 1, 0, 1), c(Tpre, Tpost, Cpre, Cpost),\n       pch = 21, bg = c(teal, teal, rust, rust), col = \"white\", cex = 2.3, lwd = 2)\ntext(1.02, (cf + Tpost) / 2, \"DiD\", pos = 4, cex = 0.9, col = \"grey15\")\n```\n\n::: {.cell-output-display}\n![The 2×2 difference-in-differences: four cell means (dots), the treated (teal) and control (rust) trends, the parallel-trends counterfactual (dashed), and the DiD (black bar) as the gap between the treated post-mean and that counterfactual.](outcome-weights_files/figure-html/unnamed-chunk-8-1.png){width=480}\n:::\n\n```{.r .cell-code}\nvtab(c(`treated trend` = Tpost - Tpre, `control trend` = Cpost - Cpre,\n        `pre gap` = Tpre - Cpre, `post gap` = Tpost - Cpost,\n        `DiD (interaction)` = coef(lm(y ~ g * p))[[\"g:p\"]]), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                  | value|\n|:-----------------|-----:|\n|treated trend     | 3.029|\n|control trend     | 0.897|\n|pre gap           | 2.019|\n|post gap          | 4.151|\n|DiD (interaction) | 2.132|\n\n\n\nThe 2×2 difference-in-differences: four cell means (dots), the treated (teal) and control (rust) trends, the parallel-trends counterfactual (dashed), and the DiD (black bar) as the gap between the treated post-mean and that counterfactual.\n:::\n:::\n\n\nThe estimated interaction recovers the true DiD of $2$, and the four cell-mean weights carry the structural signs $(+, -, -, +)$ as long as every cell is populated.\n\nThe clean $2 \\times 2$ has trivial weights — four cell means, each $\\pm 1$. Real difference-in-differences carries covariates: parallel trends holds only *conditional* on $X$, and the comparison has to be modelled. That model is a weighting of outcomes too.\n\nThe doubly-robust DiD of Sant'Anna and Zhao (2020) is AIPW read on the outcome *change* $\\Delta Y = Y_1 - Y_0$: a propensity for treatment, a control-group regression of $\\Delta Y$ on $X$, combined. By the recipe of the last section its estimate is $\\widehat{\\text{ATT}} = \\boldsymbol\\omega' \\Delta Y$, with $\\boldsymbol\\omega' = \\boldsymbol a'(\\mathbf I - \\boldsymbol S)$ — the control-trend smoother $\\boldsymbol S$ and the group weights $\\boldsymbol a = \\boldsymbol w_{\\text{treat}} - \\boldsymbol w_{\\text{cont}}$.\n\n**Simulation — doubly-robust DiD.** Two periods and $n = 2000$: treatment is selected on $x_1$ with thin overlap, $\\Pr(D = 1) = \\Lambda(-0.5 + 2 x_1)$; the control trend depends on $x_1$, so trends are parallel only given $X$; the true ATT is $1$. We fit DR-DiD with `DRDID`, rebuild its weights by hand, and check.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DRDID)\nset.seed(2)\nn  <- 2000\nx1 <- rnorm(n); x2 <- rnorm(n); Xcov <- cbind(1, x1, x2)\nD  <- rbinom(n, 1, plogis(-0.5 + 2 * x1))        # selection into treatment on x1 (thin overlap)\ny0 <- 1 + x1 + 0.5 * x2 + rnorm(n)               # pre-period outcome\ny1 <- y0 + (0.5 + 0.4 * x1) + 1 * D + rnorm(n)   # control trend depends on x1; true ATT = 1\ndY <- y1 - y0\natt <- drdid_panel(y1 = y1, y0 = y0, D = D, covariates = Xcov, boot = FALSE)$ATT\n\n# rebuild the DR-DiD weights: omega = (I - S)' a, acting on the outcome change dY\ne    <- pmin(as.vector(glm(D ~ x1 + x2, family = binomial)$fitted), 1 - 1e-6)\nkeep <- rep(TRUE, n); keep[D == 0] <- e[D == 0] < 0.995     # DRDID's control trimming\nXc   <- Xcov[D == 0, ]\nS    <- matrix(0, n, n); S[, D == 0] <- Xcov %*% solve(crossprod(Xc)) %*% t(Xc)\nw.t  <- keep * D\nw.c  <- keep * e * (1 - D) / (1 - e)\na    <- w.t / sum(w.t) - w.c / sum(w.c)          # group weights, treated minus reweighted control\nomega <- as.vector(a - crossprod(S, a))\n\nXk <- cbind(x1, x2); sds <- apply(Xk, 2, sd)\nvtab(c(`DRDID ATT`                = att,\n       `omega' dY`                = sum(omega * dY),\n       `wrong-sign weights`       = sum((D == 1 & omega < 0) | (D == 0 & omega > 0)),\n       `covariate imbalance, raw` = max(abs((colMeans(Xk[D == 1, ]) - colMeans(Xk[D == 0, ])) / sds)),\n       `covariate imbalance, wtd` = max(abs(as.vector(a %*% Xk) / sds))), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                         |   value|\n|:------------------------|-------:|\n|DRDID ATT                |   0.980|\n|omega' dY                |   0.980|\n|wrong-sign weights       | 151.000|\n|covariate imbalance, raw |   1.198|\n|covariate imbalance, wtd |   0.086|\n\n\n:::\n:::\n\n\n$\\boldsymbol\\omega' \\Delta Y$ reproduces the `DRDID` estimate exactly — the difference-in-differences is a signed weighting of observed outcome *changes*, and the diagnostics of this chapter apply to it. The weighting balances the covariate that drove selection (its standardised imbalance falls from $1.20$ to $0.09$). And $151$ units carry a wrong-sign weight — a treated unit subtracted, or a control added — the §3 signature of a comparison reaching past common support.\n\n### Staggered designs: TWFE at the observation level\n\nNegative weights in staggered designs are usually described at the level of two-by-two comparisons: TWFE averages many such comparisons, and some enter with a negative weight — the forbidden comparisons that use already-treated units as controls (de Chaisemartin and D'Haultfœuille 2020; Goodman-Bacon 2021). That is the effect-weight reading. The outcome-weight reading goes one level down, to the individual $y_{it}$.\n\nTWFE is still FWL: residualise $D_{it}$ on unit and time fixed effects to get $\\tilde D_{it}$, and $\\hat\\beta = \\sum_{it} \\omega_{it} y_{it}$ with $\\omega_{it} = \\tilde D_{it} / \\sum_{jt} \\tilde D_{jt}^2$. A treated observation with $\\omega_{it} < 0$ is a cell whose outcome is subtracted from the estimated effect — used as a control even though it is treated. An untreated observation with $\\omega_{it} > 0$ enters as though it were treated. Both are the §3 sign-flip, caused by the unit-and-time residualisation pushing $\\tilde D_{it}$ past zero: treated cells in late periods of early cohorts, where the fixed-effect prediction of $D_{it}$ exceeds $1$, and untreated cells in early periods of never-treated units, where it falls below $0$.\n\n**Simulation — staggered panel.** Three cohorts: never-treated ($20\\%$), early-treated at period $3$ with effect $\\tau = 3$ ($40\\%$), and late-treated at period $6$ with effect $\\tau = 1$ ($40\\%$), observed across $T = 8$ periods; $y_{it} = \\alpha_i + \\gamma_t + \\tau_g D_{it} + \\varepsilon_{it}$. The high treated share makes the forbidden comparison visible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fixest)\nset.seed(5)\nN <- 300; TT <- 8\ng <- sample(c(0, 3, 6), N, TRUE, prob = c(.2, .4, .4))\npanel <- data.frame(id = rep(1:N, each = TT), t = rep(1:TT, N))\npanel$g <- g[panel$id]\npanel$D <- as.integer(panel$g > 0 & panel$t >= panel$g)\ntau <- ifelse(panel$g == 3, 3, ifelse(panel$g == 6, 1, 0))\nalpha <- rnorm(N); gamma <- seq(0, 1.4, length.out = TT)\npanel$y <- alpha[panel$id] + gamma[panel$t] + tau * panel$D + rnorm(nrow(panel), 0, 0.5)\n\nDtil <- resid(feols(D ~ 1 | id + t, data = panel))\nomega_tw <- Dtil / sum(Dtil^2)\nn1 <- sum(panel$D)\nvtab(c(`true ATT`              = mean(tau[panel$D == 1]),\n       `TWFE`                  = coef(feols(y ~ D | id + t, panel))[[\"D\"]],\n       `omega' y`              = sum(omega_tw * panel$y),\n       `treated, omega < 0`    = sum(panel$D == 1 & omega_tw < 0),\n       `untreated, omega > 0`  = sum(panel$D == 0 & omega_tw > 0)), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                     |   value|\n|:--------------------|-------:|\n|true ATT             |   2.426|\n|TWFE                 |   1.915|\n|omega' y             |   1.915|\n|treated, omega < 0   | 384.000|\n|untreated, omega > 0 | 551.000|\n\n\n:::\n:::\n\n\nThe TWFE coefficient sits well below the true ATT, and $\\sum \\omega_{it} y_{it}$ reproduces it exactly. Hundreds of treated cells carry a negative weight: these are the early cohort's cells in periods $6$–$8$, the ones where the unit-and-time prediction of $D$ exceeds $1$ and the residual $\\tilde D_{it}$ flips sign. Their outcomes are subtracted from $\\hat\\beta$ — the observation-level signature of the Bacon forbidden comparison.\n\nThe wrong-sign diagnostic in a panel is by observation $(i, t)$, not by unit. In the cross-sectional case of §3, the fix was to trim wrong-sign observations and refit. In a panel, trimming specific $(i, t)$ cells removes observations that anchor that unit's fixed effect and distorts the estimates for its remaining cells. The response in the staggered setting is to switch estimators — imputation (Borusyak, Jaravel, and Spiess 2024), Callaway and Sant'Anna, or Sun and Abraham — that avoid the forbidden comparison by construction. The imputation estimator, for example, fits unit and time fixed effects on untreated observations alone and imputes each treated cell's counterfactual; because its smoother draws only on untreated outcomes, the weight on every treated cell reduces to $1/n_1$ and no treated observation can count as a control.\n\n### Implied versus chosen\n\nOne distinction cuts across everything above. OLS, AIPW, DML, TWFE, and the imputation estimator all *imply* weights — they fall out of the estimation and are diagnosed afterward. Synthetic controls and synthetic difference-in-differences *choose* weights as part of the design, selecting $\\boldsymbol\\omega$ to balance pre-treatment outcomes or covariates. For those estimators $\\hat\\tau = \\boldsymbol\\omega'\\boldsymbol Y$ is the definition, not a decomposition; the balance and extrapolation checks of this chapter still apply, but what they diagnose is the designer's choice rather than a side effect of the estimator.\n\nA closing caution. These weights diagnose *estimation* — which comparisons a difference-in-differences rests on, and whether it leans on non-overlapping or forbidden ones — not *identification*. Parallel trends is an assumption about the treated group's unobserved untreated path, and no weighting of observed outcomes can test it: a negative weight and a failure of parallel trends are independent, either able to occur without the other. Pre-trends are probed separately, by the event-study leads.\n\n## Summary\n\n1. **A signed weighting of the outcomes.** FWL writes $\\hat\\beta = \\sum_i \\omega_i y_i$ with $\\omega_i = \\tilde V_i / \\sum_j \\tilde V_j^2$ (@eq-omega): a signed, computable weighting of the observed outcomes, different from the effect weights $w_i = \\tilde V_i V_i$.\n2. **Two constraints.** The weights sum to zero and the weighted regressor sums to one: $\\sum_i \\omega_i = 0$ and $\\sum_i \\omega_i V_i = 1$.\n3. **The sign shows direction.** Because $\\omega_i$ is proportional to $\\tilde V_i$, not to $\\tilde V_i^2$, it carries a sign: it shows which rows push $\\hat\\beta$ up and which pull it down, and, under controls with thin overlap, which enter with the sign their raw position would not predict.\n4. **The same weights beyond OLS.** Any estimator that can be written $\\hat\\tau = \\boldsymbol\\omega' \\boldsymbol Y$ has outcome weights, so the same object and its checks reach AIPW, double machine learning, and causal forests (Knaus 2024). PLR's denominator $\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}$ reveals its estimand as the VWATE (@eq-vwate), not the ATE; and the sum-to-zero of OLS need not become a sum to $\\pm 1$ within the treated and control groups.\n5. **From difference in means to difference-in-differences.** Regressed on the treatment alone, $\\hat\\beta$ is the difference in group means; a $2 \\times 2$ difference-in-differences is a signed contrast of four cell means. With covariates, a doubly-robust DiD weights the outcome changes, $\\widehat{\\text{ATT}} = \\boldsymbol\\omega' \\Delta Y$ (Sant'Anna and Zhao 2020), open to the same checks.\n6. **Staggered designs.** In staggered TWFE the outcome weights flag both treated cells used as controls and untreated cells used as treated — the observation-level version of the Bacon (2021) forbidden comparisons. Estimators that fit counterfactuals on untreated observations alone (Borusyak, Jaravel, and Spiess 2024; Callaway and Sant'Anna 2021) cannot assign negative weight to any treated cell, so the forbidden-comparison diagnostic is clean by construction.\n",
    "supporting": [
      "outcome-weights_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}