{
  "hash": "1772f07fc8daca3aed9262324d0a5832",
  "result": {
    "engine": "knitr",
    "markdown": "# Interpreting OLS: Outcome Weights\n\n\n\nThe companion chapter [Interpreting OLS: Effect Weights](interpreting-ols.qmd) read the OLS coefficient as a weighting of unobservable effects — it answered *whose* effect $\\hat\\beta$ estimates. The same Frisch–Waugh–Lovell identity reads a second way, as a weighting of the *observed* outcomes. This reading answers a different question — which rows drive $\\hat\\beta$, and in which direction — and, unlike the first, it is computable and generalises past OLS. This chapter follows it.\n\n## The other reading of FWL\n\nResidualise the regressor of interest $V$ on the controls $X$, write $\\tilde V_i$ for the residual, and recall the residual-on-residual form of the coefficient, @eq-fwl:\n\n$$ \\hat\\beta = \\frac{\\sum_{i=1}^n \\tilde V_i y_i}{\\sum_{i=1}^n \\tilde V_i^2}. $$ {#eq-outcome-weights-1}\n\nThe previous chapter grouped each $\\tilde V_i$ with $V_i$ and read $\\hat\\beta$ as a weighting $w_i = \\tilde V_i V_i$ of effects (@eq-weff). Group $\\tilde V_i$ with $y_i$ instead — pairing each residual with its own outcome in the numerator — and the *same* expression is a linear combination of the observed outcomes:\n\n$$ \\hat\\beta = \\sum_{i=1}^n \\omega_i y_i, \\qquad \\omega_i = \\frac{\\tilde V_i}{\\sum_{j=1}^n \\tilde V_j^2}. $$ {#eq-omega}\n\n@eq-omega is the same algebra rearranged, but a different object from the effect weights.\n\n| | Weights on outcomes $\\omega_i$ | Weights on effects $w_i$ |\n|---|---|---|\n| Weights what | the observed $y_i$ | that observation's own effect $\\beta_i$ |\n| Sign | signed, sums to zero | non-negative (under saturation) |\n| Computable | yes, $y$ is observed | no, the $\\beta_i$ are never seen |\n| Holds when | always, it is algebra | in expectation; per-unit needs saturation |\n| Answers | which rows drive $\\hat\\beta$, any wrong sign | is this the effect I meant, whose effect |\n\nTwo constraints pin $\\omega_i$ down, both from @eq-omega. An intercept among the controls makes $\\sum_i \\tilde V_i = 0$, so the weights **sum to zero**. And $\\sum_i \\tilde V_i V_i = \\sum_i \\tilde V_i^2$ makes the weighted regressor **sum to one**, $\\sum_i \\omega_i V_i = 1$.\n\nUse this reading when overlap is in doubt and a row may enter with the wrong sign — which the non-negative $w_i$ cannot show. Keep the effect reading for questions about the estimand.\n\n## What the outcome weights look like\n\nTake the simple regression of $y$ on $x$ with an intercept, so $\\tilde V_i = x_i - \\bar x = d_i$ and\n\n$$ \\omega_i = \\frac{d_i}{\\sum_j d_j^2}. $$ {#eq-outcome-weights-2}\n\nUnlike the effect weights $w_i = d_i^2$ — non-negative, growing with the *square* of distance — this is **linear in $d_i$, and so signed**: a point left of $\\bar x$ enters $\\hat\\beta$ with a negative coefficient on its outcome, a point right of it positive. It is not a slope and does not involve $\\bar y$; it is simply a signed weight on the observed $y_i$.\n\n**Simulation — simple regression.** To see it, we simulate $n = 100$ points — regressor $x_i \\sim N(5, 2^2)$ and outcome $y_i = 2 x_i + \\varepsilon_i$ with $\\varepsilon_i \\sim N(0, 3^2)$ — then size each point by $|\\omega_i|$ and colour it by sign.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nn <- 100; x <- rnorm(n, 5, 2); y <- 2 * x + rnorm(n, 0, 3)\nxb <- mean(x); d <- x - xb; om <- d / sum(d^2); col <- ifelse(om >= 0, teal, rust)\nR <- d > 0; L <- d < 0\nxR <- sum(abs(d[R]) * x[R]) / sum(abs(d[R])); yR <- sum(abs(d[R]) * y[R]) / sum(abs(d[R]))\nxL <- sum(abs(d[L]) * x[L]) / sum(abs(d[L])); yL <- sum(abs(d[L]) * y[L]) / sum(abs(d[L]))\nplot(x, y, pch = 16, cex = 0.35 + 2 * abs(om) / max(abs(om)),\n     col = paste0(col, \"99\"), xlab = \"x\", ylab = \"y\", main = \"N = 100 Points\")\nabline(v = xb, lty = 3, col = \"grey55\")\nabline(lm(y ~ x), lwd = 1.3, lty = 2, col = \"grey55\")\nsegments(xL, yL, xR, yR, lwd = 2.6, col = \"grey15\")\npoints(c(xL, xR), c(yL, yR), pch = 21, bg = c(rust, teal), col = \"white\", cex = 2.3, lwd = 2)\n```\n\n::: {.cell-output-display}\n![Outcome weights in a 100-point sample. Each small point's **size scales with its weight** $|\\omega_i|$, coloured by sign — teal ($\\omega_i > 0$) pushes $\\hat\\beta$ up, rust ($\\omega_i < 0$) pulls it down; the dotted line is the fulcrum $x = \\bar x$. The two large dots are the $|d|$-weighted centroids of the points left and right of $\\bar x$; the solid segment joining them has slope $\\hat\\beta$, and the dashed line is the OLS fit (same slope, shifted through the grand mean).](outcome-weights_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nvtab(c(`sum(omega)`   = sum(om),      `sum(omega*x)` = sum(om * x),\n        `positive mass` = sum(om[om > 0]), `negative mass` = sum(om[om < 0]),\n        `OLS`          = coef(lm(y ~ x))[[2]], `sum(omega*y)` = sum(om * y)), 4)\n```\n\n::: {.cell-output-display}\n\n\n|              |   value|\n|:-------------|-------:|\n|sum(omega)    |  0.0000|\n|sum(omega*x)  |  1.0000|\n|positive mass |  0.2486|\n|negative mass | -0.2486|\n|OLS           |  1.8648|\n|sum(omega*y)  |  1.8648|\n\n\n\nOutcome weights in a 100-point sample. Each small point's **size scales with its weight** $|\\omega_i|$, coloured by sign — teal ($\\omega_i > 0$) pushes $\\hat\\beta$ up, rust ($\\omega_i < 0$) pulls it down; the dotted line is the fulcrum $x = \\bar x$. The two large dots are the $|d|$-weighted centroids of the points left and right of $\\bar x$; the solid segment joining them has slope $\\hat\\beta$, and the dashed line is the OLS fit (same slope, shifted through the grand mean).\n:::\n:::\n\n\nThe printed sums confirm @eq-omega: the weights split at $\\bar x$ into a positive mass ($\\approx +0.25$) and an equal negative one ($\\approx -0.25$), and $\\sum_i \\omega_i x_i = 1$.\n\nBut the figure shows more. Split the points at $\\bar x$, weight each side by $|d_i|$, and take its centroid — the two large dots. **The segment joining them has slope $\\hat\\beta$:** the OLS slope is the rise over run between the low-$x$ and high-$x$ weighted centres.\n\nThe dashed fit shares that slope, shifted through the grand mean, so the two coincide only when the sides balance. This collapse to two points falls out of the slope formula.\n\n### Why it collapses to two points\n\nWrite $d_i = x_i - \\bar x$. Because $\\sum_i d_i = 0$, the positive and negative sides carry equal total weight $W = \\sum_{i: d_i > 0} d_i$. An inner product with $d$ is therefore a between-group contrast: for any variable $v$,\n\n$$ d \\cdot v = W(\\bar v_R - \\bar v_L), $$ {#eq-outcome-weights-4}\n\nwhere $\\bar v_R$ and $\\bar v_L$ are the $|d_i|$-weighted means on each side of $\\bar x$. The slope $\\hat\\beta = d \\cdot y\\, /\\, d \\cdot x$ is the ratio of two such contrasts; $W$ cancels:\n\n$$ \\hat\\beta = \\frac{\\bar y_R - \\bar y_L}{\\bar x_R - \\bar x_L}. $$ {#eq-outcome-weights-5}\n\nThat is the rise over run between the two $|d|$-weighted centroids — the two dots in the figure.\n\n## When the sign flips\n\nIn simple regression the sign of $\\omega_i$ is just the side of the mean: half the weights are negative, structurally, and a low-$x$ point *should* count against a high-$x$ one. With controls $\\tilde V_i$ becomes a *residual*, and a row can flip to the sign its raw position denies — a hidden extrapolation the non-negative $w_i$ can never show.\n\nWith a binary treatment $D$ and covariate $x$, the weight $\\omega_i \\propto \\tilde V_i = D_i - \\hat D_i$, with $\\hat D$ the linear projection of $D$ on $(1, x)$. Regressed on $D$ alone, every treated unit is positive and every control negative — the *structural* pattern, producing $\\hat\\beta = \\bar y_1 - \\bar y_0$. Add $x$ and the fitted $\\hat D_i$ can leave $[0, 1]$ where treatment and control barely overlap: a treated unit with $\\hat D_i > 1$ gets $\\tilde V_i < 0$, so its outcome is subtracted from $\\hat\\beta$ — a *wrong-sign* weight that the non-negative $\\tilde V_i^2$ hides. The test is one line: **fit the treatment on the controls; any $\\hat D_i \\notin [0, 1]$ is an extrapolated, wrong-sign unit** — a point where the groups fail to overlap. (With a continuous regressor there is no bounded range to leave; overlap is read from leverage, not sign.)\n\nA wrong-sign weight is extrapolation: the model reaches outside common support, and $\\hat\\beta$ can leave the convex hull of the observed outcomes. Whether it matters depends on the data — a sensitivity check is one trim away.\n\n**Simulation — thin overlap on a curved baseline.** The DGP: 150 controls near $x = 2.5$ and 150 treated near $x = 4.5$ (both sd $1.1$), with $y_i = D_i + 0.8\\,(x_i - 3.5)^2 + 0.3\\,x_i + \\varepsilon_i$, $\\varepsilon_i \\sim N(0, 0.5^2)$ — a constant true effect of $1$ sitting on a convex baseline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nn <- 150\nx <- c(rnorm(n, 2.5, 1.1), rnorm(n, 4.5, 1.1))\nd <- c(rep(0, n), rep(1, n))\ny <- 1.0 * d + 0.8 * (x - 3.5)^2 + 0.3 * x + rnorm(2 * n, 0, 0.5)\ndf <- data.frame(y, d, x)\nX <- cbind(1, x); dh <- as.vector(X %*% solve(crossprod(X)) %*% t(X) %*% d)\nflag <- (d == 1 & dh > 1) | (d == 0 & dh < 0)\npch <- ifelse(d == 1, 17, 16); col <- ifelse(d == 1, teal, rust)\nplot(x, y, type = \"n\", xlab = \"x\", ylab = \"y\")\nxs <- seq(min(x), max(x), length = 200)\nmc <- function(z) 0.8 * (z - 3.5)^2 + 0.3 * z              # true control mean E[y | x, D = 0]\nlines(xs, mc(xs),     col = rust, lwd = 2.4)               # control mean\nlines(xs, mc(xs) + 1, col = teal, lwd = 2.4, lty = 3)      # treated mean = control + true effect (1)\npoints(x, y, pch = pch, col = paste0(col, \"88\"), cex = 0.85)               # all points, by group\npoints(x[flag], y[flag], pch = 1, col = \"grey15\", cex = 1.7, lwd = 1.4)    # ring the flagged units\narrows(3.5, mc(3.5), 3.5, mc(3.5) + 1, code = 3, length = 0.05, angle = 90, lwd = 2.4, col = \"grey10\")\nsegments(3.5, mc(3.5) + 0.5, 2.05, 13.3, col = \"grey55\", lwd = 1)\ntext(2.0, 14, \"gap = true effect = 1\", pos = 4, cex = 0.82, col = \"grey10\")\nlegend(\"bottomright\", bty = \"n\", cex = 0.82,\n       legend = c(\"control\", \"treated\", \"flagged (trimmed)\", \"control mean\", \"treated mean\"),\n       pch = c(16, 17, 1, NA, NA), lty = c(NA, NA, NA, 1, 3),\n       col = c(rust, teal, \"grey15\", rust, teal))\n```\n\n::: {.cell-output-display}\n![Thin overlap on a convex baseline. The two curves are the true means — control (rust, solid) and treated (teal, dotted), a constant $1$ apart (arrow). Controls sit low on the curve and treated high; the groups share only the middle. Ringed points are wrong-sign units — $\\hat D_i \\notin [0, 1]$ — where the groups fail to overlap. The straight $y \\sim D + x$ reports $\\hat\\beta = 0.69$; dropping the flagged units, or reweighting to the overlap, restores $\\approx 1$.](outcome-weights_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nw_ato <- WeightIt::weightit(d ~ x, data = df, method = \"glm\", estimand = \"ATO\")\nvtab(c(`flagged units`      = sum(flag),\n        `beta (full)`        = coef(lm(y ~ d + x))[[\"d\"]],\n        `beta (trimmed)`     = coef(lm(y ~ d + x, data = df[!flag, ]))[[\"d\"]],\n        `beta (overlap-wtd)` = coef(lm(y ~ d + x, weights = w_ato$weights))[[\"d\"]]), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                   |  value|\n|:------------------|------:|\n|flagged units      | 37.000|\n|beta (full)        |  0.688|\n|beta (trimmed)     |  0.991|\n|beta (overlap-wtd) |  0.979|\n\n\n\nThin overlap on a convex baseline. The two curves are the true means — control (rust, solid) and treated (teal, dotted), a constant $1$ apart (arrow). Controls sit low on the curve and treated high; the groups share only the middle. Ringed points are wrong-sign units — $\\hat D_i \\notin [0, 1]$ — where the groups fail to overlap. The straight $y \\sim D + x$ reports $\\hat\\beta = 0.69$; dropping the flagged units, or reweighting to the overlap, restores $\\approx 1$.\n:::\n:::\n\n\nThirty-seven units carry the wrong sign, all in the non-overlapping tails. Trim them and $\\hat\\beta$ jumps from $0.69$ to $0.99$; the overlap weights (`\"ATO\"`, Li, Morgan, and Zaslavsky 2018) give $0.98$. Either fix confirms the estimate leaned on the extrapolation, read off the regression itself with no separate model. Had the outcome been linear, the same trim would barely move $\\hat\\beta$: the wrong-sign weights are still there, but they are harmless. The check tells you which case you are in.\n\nThis is the implied-weights diagnostic of Chattopadhyay and Zubizarreta (2023); their `lmw` package computes the weights and the balance, extrapolation, and influence diagnostics built on them, and `OutcomeWeights` (Knaus 2024) carries it to machine-learning estimators. The mainstream overlap check takes the other route, through the propensity score (`WeightIt` for estimation, `cobalt` for balance, and Crump et al. 2009 for trimming); both routes reach the same conclusion.\n\n## Out of OLS: the same weights beyond the linear model\n\nThe outcome reading has one advantage the effect reading lacks: it survives leaving OLS. Any estimator that can be written $\\hat\\tau = \\sum_i \\omega_i Y_i = \\boldsymbol\\omega' \\boldsymbol Y$ — a linear combination of the observed outcomes — *has* outcome weights, whatever machinery produced them.\n\nKnaus (2024) makes this the organising idea, and his `OutcomeWeights` package computes $\\boldsymbol\\omega$ for AIPW, double machine learning, and the causal forest.\n\n### The weights, derived\n\nThe OLS outcome weights (@eq-omega) followed from one fact: in the FWL numerator $\\sum_i \\tilde V_i y_i$, the outcome $y_i$ appears once, linearly, so $\\hat\\beta = \\sum_i \\omega_i y_i$ with $\\omega_i = \\tilde V_i / \\sum_j \\tilde V_j^2$. The same fact holds whenever the outcome model is a *smoother* — a map $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$ that is linear in the training outcomes. Substituting $\\boldsymbol S \\boldsymbol Y$ for $\\hat{\\boldsymbol m}$ keeps $\\boldsymbol Y$ linear in the numerator, and reading off its coefficient gives $\\boldsymbol\\omega$. We carry this out for PLR and AIPW.\n\n*PLR.* Take the partially-linear estimator (the R-learner behind the causal forest). It is FWL with the projections done by a flexible learner: residualise treatment and outcome on the covariates, then regress one residual on the other,\n\n$$ \\hat\\tau = \\frac{\\sum_i (D_i - \\hat e_i)(Y_i - \\hat m_i)}{\\sum_i (D_i - \\hat e_i)^2}, $$ {#eq-outcome-weights-6}\n\nwith $\\hat e = \\hat E[D \\mid X]$ and $\\hat m = \\hat E[Y \\mid X]$ the fitted nuisances.\n\nThe outcome nuisance is a *smoother*: its fitted values are a linear map of the training outcomes, $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$ — true for OLS, ridge, kernels, and honest forests alike. So the outcome residual is $\\boldsymbol Y - \\hat{\\boldsymbol m} = (\\mathbf I - \\boldsymbol S)\\boldsymbol Y$. Writing $\\tilde{\\boldsymbol D} = \\boldsymbol D - \\hat{\\boldsymbol e}$ for the treatment residual and substituting,\n\n$$ \\hat\\tau = \\frac{\\tilde{\\boldsymbol D}'(\\mathbf I - \\boldsymbol S)\\,\\boldsymbol Y}{\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}}. $$ {#eq-outcome-weights-7}\n\nNow $\\boldsymbol Y$ appears once, linearly, in the numerator. Read off its coefficient and the weights are done:\n\n$$ \\hat\\tau = \\boldsymbol\\omega'\\boldsymbol Y, \\qquad \\boldsymbol\\omega' = \\frac{\\tilde{\\boldsymbol D}'(\\mathbf I - \\boldsymbol S)}{\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}}. $$ {#eq-omega-ml}\n\nThat is @eq-omega — the OLS weights — with the projection annihilator $\\boldsymbol M_X$ replaced by the smoother annihilator $\\mathbf I - \\boldsymbol S$. OLS is the case of a linear learner, $\\boldsymbol S = \\boldsymbol P_X$: there $\\boldsymbol S$ is a projection, $\\mathbf I - \\boldsymbol S = \\boldsymbol M_X$, and @eq-omega-ml is @eq-omega exactly. Component by component, the weight on observation $i$ is\n\n$$ \\omega_i = \\frac{\\tilde D_i - \\sum_j S_{ji}\\,\\tilde D_j}{\\sum_k \\tilde D_k^2}: $$ {#eq-omega-plr-i}\n\nthe treatment residual of unit $i$, minus how much other units' treatment residuals leak to $i$ through the outcome smoother, normalised by the total treatment-residual variance.\n\nThe outcome weights tell which rows drive the estimate; the *effect* weights tell whose effect it estimates. Substitute $Y_i = \\tau_i D_i + m(X_i) + \\varepsilon_i$ into the PLR numerator. With consistent nuisances $\\hat m \\approx m$, the noise vanishes in expectation and the numerator reduces to $\\sum_i \\tilde D_i D_i \\tau_i$, so the effect weight on $\\tau_i$ is $\\tilde D_i D_i = (D_i - e_i) D_i$. Since $D$ is binary ($D_i^2 = D_i$),\n\n$$ E[\\tilde D_i D_i \\mid X_i] = E[D_i \\mid X_i] - e_i\\, E[D_i \\mid X_i] = e_i - e_i^2 = e_i(1 - e_i). $$ {#eq-outcome-weights-8}\n\nThe denominator $\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D} = \\sum_i \\tilde D_i^2$ has the same expectation, $\\sum_i e_i(1 - e_i)$, since $\\text{Var}(D_i \\mid X_i) = e_i(1 - e_i)$. Both numerator and denominator weight by propensity variance, and the ratio is the variance-weighted average treatment effect,\n\n$$ \\tau_{\\text{VWATE}} = \\frac{\\sum_i e(X_i)(1 - e(X_i))\\,\\tau(X_i)}{\\sum_i e(X_i)(1 - e(X_i))}, $$ {#eq-vwate}\n\nnot the plain ATE $\\bar\\tau = n^{-1}\\sum_i \\tau_i$. The two coincide only when effects are constant or treatment is randomly assigned. The weighting is the same $e(1-e)$ that appeared in the previous chapter's @eq-angrist, where Angrist (1998) showed OLS with saturated strata weights each stratum by $n_x \\hat D(x)(1 - \\hat D(x))$. That result required discrete strata and saturated controls; @eq-vwate is the same propensity-variance weighting with continuous covariates and a flexible learner. The individual $\\tau(X_i)$ are never observed or estimated — they are the structural unit-level effects in $Y_i = \\tau(X_i) D_i + m(X_i) + \\varepsilon_i$. PLR returns one number, $\\hat\\tau$, that converges to their $e(1-e)$-weighted average; to estimate $\\tau(X_i)$ itself one needs a CATE estimator (a causal forest, say).\n\nThree moves did it: write the estimator, substitute the smoother $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$, read off the coefficient on $\\boldsymbol Y$. They work for any estimator built from smoothers; only the operator on $\\boldsymbol Y$ changes. AIPW is worth carrying through, because its operator is more than $\\mathbf I - \\boldsymbol S$.\n\n*AIPW.* With outcome smoothers $\\hat{\\boldsymbol\\mu}_1 = \\boldsymbol S_1 \\boldsymbol Y$, $\\hat{\\boldsymbol\\mu}_0 = \\boldsymbol S_0 \\boldsymbol Y$ and propensity $\\hat{\\boldsymbol e}$, the score of unit $i$ is\n\n$$ \\psi_i = \\hat\\mu_{1i} - \\hat\\mu_{0i} + \\frac{D_i}{\\hat e_i}\\,(Y_i - \\hat\\mu_{1i}) - \\frac{1 - D_i}{1 - \\hat e_i}\\,(Y_i - \\hat\\mu_{0i}), \\qquad \\hat\\tau = \\frac1n \\sum_i \\psi_i. $$ {#eq-outcome-weights-9}\n\nEach $\\hat\\mu_{ji}$ is $(\\boldsymbol S_j \\boldsymbol Y)_i$, so $\\boldsymbol Y$ again enters only linearly; collecting its coefficient gives $\\hat\\tau = \\boldsymbol\\omega' \\boldsymbol Y$ with\n\n$$ \\boldsymbol T = \\boldsymbol S_1 - \\boldsymbol S_0 + \\operatorname{diag}\\!\\Big(\\tfrac{\\boldsymbol D}{\\hat{\\boldsymbol e}}\\Big)(\\mathbf I - \\boldsymbol S_1) - \\operatorname{diag}\\!\\Big(\\tfrac{1 - \\boldsymbol D}{1 - \\hat{\\boldsymbol e}}\\Big)(\\mathbf I - \\boldsymbol S_0), \\qquad \\boldsymbol\\omega' = \\frac{\\mathbf 1' \\boldsymbol T}{n}. $$ {#eq-outcome-weights-10}\n\nThat is, $\\omega_j$ is the $j$-th column-sum of $\\boldsymbol T$ divided by $n$: observation $j$'s outcome enters the ATE through its direct IPW term and through its indirect contribution via the two outcome smoothers $\\boldsymbol S_1$, $\\boldsymbol S_0$ to every other unit's augmentation correction.\n\nComparing the two:\n\n| | PLR (@eq-omega-ml) | AIPW |\n|---|---|---|\n| Matrix form | $\\boldsymbol\\omega' = \\tilde{\\boldsymbol D}'(\\mathbf I - \\boldsymbol S)\\,/\\,\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}$ | $\\boldsymbol\\omega' = \\mathbf 1'\\boldsymbol T\\,/\\,n$ |\n| Per unit | $\\omega_i = \\bigl(\\tilde D_i - \\sum_j S_{ji}\\tilde D_j\\bigr)\\,/\\,\\sum_k \\tilde D_k^2$ | $\\omega_j = \\frac{1}{n}\\sum_i T_{ij}$ |\n| Smoother | one $\\boldsymbol S$ (outcome on $X$) | two: $\\boldsymbol S_1$ (treated), $\\boldsymbol S_0$ (control) |\n| Normalisation | treatment-residual variance | sample size $n$ |\n\nBoth follow the same recipe — substitute the smoother $\\hat{\\boldsymbol m} = \\boldsymbol S \\boldsymbol Y$, read off $\\boldsymbol Y$'s coefficient — and differ only in the operator acting on $\\boldsymbol Y$.\n\n**Simulation — heterogeneous effects (DML).** Under a heterogeneous effect the two estimators diverge, and the weights show why. We simulate $n = 2000$ units: five standard-normal covariates $X$, selection $W_i \\sim \\text{Bernoulli}(\\Lambda(-1 + 1.2\\,X_{i1}))$ with $\\Lambda$ the logistic function (treatment is scarce and tied to $X_1$), and outcome $Y_i = \\tau_i W_i + X_{i1} + 0.5\\,X_{i2} + \\varepsilon_i$ with an effect $\\tau_i = 1 + X_{i1}$ that varies across units — a $W \\times X_1$ interaction. The average effect is $E[\\tau] = 1$, but units with larger $X_1$ have larger effects. `dml_with_smoother` returns a partially-linear (PLR) and an AIPW estimator; `get_outcome_weights` extracts the weight matrix $\\boldsymbol\\omega$, one row per estimator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(OutcomeWeights)\nset.seed(1)\nn <- 2000; p <- 5\nX <- matrix(rnorm(n * p), n, p)\netrue <- plogis(-1 + 1.2 * X[, 1])                       # asymmetric selection on X1\nW <- rbinom(n, 1, etrue)\ntau <- 1 + X[, 1]                                        # heterogeneous effect: W x X1\nY <- tau * W + X[, 1] + 0.5 * X[, 2] + rnorm(n)\ndml <- dml_with_smoother(Y, W, X, estimators = c(\"PLR\", \"AIPW_ATE\"))\nom  <- get_outcome_weights(dml)                          # om$omega: 2 x n, om$treat = W\ninvisible(capture.output(s <- summary(dml)))\nW1 <- om$treat == 1\ntab <- t(sapply(rownames(om$omega), function(nm) {\n  w <- om$omega[nm, ]\n  c(estimate = s[nm, 1], `omega %*% Y` = sum(w * Y),\n    treated = sum(w[W1]), control = sum(w[!W1]))\n}))\nov <- etrue * (1 - etrue)                                # e(1-e): PLR's per-unit weight\n# ATE = plain mean of tau; overlap-ATE = e(1-e)-weighted mean of tau (PLR's target)\ncat(sprintf(\"true ATE = %.2f   true overlap-ATE = %.2f\\n\", mean(tau), sum(ov * tau) / sum(ov)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntrue ATE = 0.99   true overlap-ATE = 1.31\n```\n\n\n:::\n\n```{.r .cell-code}\nmtab(tab, 3)\n```\n\n::: {.cell-output-display}\n\n\n|         | estimate| omega %*% Y| treated| control|\n|:--------|--------:|-----------:|-------:|-------:|\n|PLR      |    1.287|       1.287|   0.997|  -0.997|\n|AIPW-ATE |    1.074|       1.074|   1.000|  -1.000|\n\n\n:::\n:::\n\n\nTwo things stand out. First, the estimators now *disagree* — PLR reports $1.29$, AIPW $1.07$ — and neither is wrong; they target different populations. PLR targets the VWATE (@eq-vwate), not the ATE. Here treatment selection loads on $X_1$ through $e = \\Lambda(-1 + 1.2\\,X_1)$, and $\\tau = 1 + X_1$ also rises in $X_1$, so the units PLR overweights — those with $e$ near $\\tfrac12$, around $X_1 \\approx 0.8$ — carry above-average effects, pushing PLR's estimate above the true ATE. AIPW instead reweights by $1/e$ and $1/(1-e)$ to undo selection, returning the plain average, the ATE ($\\approx 1$). Same outcomes $\\boldsymbol Y$, weighted two ways, two population-averages of $\\tau$ — and the weights are what make the difference visible.\n\nSecond, the weights still reproduce each estimate exactly and sum to zero overall. They part on the other constraint from @eq-omega, $\\sum_i \\omega_i V_i = 1$: for a binary treatment that constraint is the treated weights summing to $+1$ (and, with the zero total, controls to $-1$). AIPW keeps it exactly; the partially-linear estimator sums to $\\pm 0.99$, quietly breaking the within-group budget that OLS and AIPW hold.\n\nThat divergence shows what the representation is for. In Knaus's (2024) framing $\\boldsymbol\\omega$ does three things: it puts OLS, IPW, AIPW, DML, and the causal forest on **one footing** ($\\boldsymbol\\omega' \\boldsymbol Y$); it **characterises the target population** each reports — the PLR-versus-AIPW gap above; and it **checks covariate balance** via `cobalt`, flagging when weights break a property usually assumed — the sum-to-$\\pm 1$ within treated and control groups that PLR violates here.\n\nThe formulas take a few lines to check against the package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn  <- length(Y)\nS  <- dml$NuPa.hat$smoothers$S[1, , ]\nS1 <- dml$NuPa.hat$smoothers$S.d1[1, , ]\nS0 <- dml$NuPa.hat$smoothers$S.d0[1, , ]\ne  <- dml$NuPa.hat$predictions$D.hat[, 1]\nWtil   <- W - e\nom_plr <- as.numeric((Wtil - crossprod(S, Wtil)) / sum(Wtil^2))\nImat    <- diag(n)\nTm      <- S1 - S0 + (W / e) * (Imat - S1) - ((1 - W) / (1 - e)) * (Imat - S0)\nom_aipw <- colSums(Tm) / n\nvtab(c(`PLR:  max |by hand - package|` = max(abs(om_plr  - om$omega[\"PLR\", ])),\n       `AIPW: max |by hand - package|` = max(abs(om_aipw - om$omega[\"AIPW-ATE\", ])),\n       `PLR:  omega' Y`                = sum(om_plr  * Y),\n       `AIPW: omega' Y`                = sum(om_aipw * Y)), 4)\n```\n\n::: {.cell-output-display}\n\n\n|                                        |  value|\n|:---------------------------------------|------:|\n|PLR:  max &#124;by hand - package&#124; | 0.0000|\n|AIPW: max &#124;by hand - package&#124; | 0.0000|\n|PLR:  omega' Y                          | 1.2873|\n|AIPW: omega' Y                          | 1.0738|\n\n\n:::\n:::\n\n\n### Two uses: balance and extrapolation\n\nHaving $\\boldsymbol\\omega$, two checks run directly on it. Does the estimator's implied weighting balance the covariates? Hand $\\boldsymbol\\omega$ to `cobalt` and read the largest standardised mean difference. And is it extrapolating? Count the wrong-sign weights — a control with $\\omega_i > 0$ or a treated unit with $\\omega_i < 0$, the signature of a comparison reaching off common support.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cobalt)\nuses <- t(sapply(rownames(om$omega), function(nm) {\n  w <- om$omega[nm, ]\n  c(`max |SMD|`        = max(abs(bal.tab(as.data.frame(X), treat = W, weights = w)$Balance$Diff.Adj)),\n    `wrong-sign units` = sum((om$treat == 1 & w < 0) | (om$treat == 0 & w > 0)))\n}))\nmtab(uses, 3)\n```\n\n::: {.cell-output-display}\n\n\n|         | max &#124;SMD&#124;| wrong-sign units|\n|:--------|-------------------:|----------------:|\n|PLR      |               0.025|               21|\n|AIPW-ATE |               0.091|                0|\n\n\n:::\n:::\n\n\nRaw, the groups are badly imbalanced — the largest covariate SMD is $1.11$, since treatment was tied to $X_1$. Both weightings pull it down to near zero ($0.03$ for PLR, $0.09$ for AIPW): each balances the covariates, which for a causal forest you could not otherwise check.\n\nThey differ on extrapolation. PLR carries 21 wrong-sign controls — it leans slightly off common support — while AIPW carries none. Neither is disqualifying here; the point is that balance and extrapolation are now *checkable*, on estimators that never exposed a weighting.\n\n## The DiD setting\n\nWhen the regressor is a treatment indicator, every unit in a group gets the same weight, so $\\hat\\beta$ reduces to a contrast of group means. Regressed on the treatment alone it is the difference in means between treated and control. Add a time period and its interaction with treatment and it becomes a difference-in-differences across four group-by-period cells. We take these in turn, then bring in covariates.\n\n**Simulation — treatment alone.** Regress $y$ on the treatment $D$ alone — here 30 treated drawn $y \\sim N(5, 1)$ and 50 controls $y \\sim N(2, 1)$. The residual $\\tilde V_i = D_i - \\bar D$ is constant within each group, so the weight is uniform within a group and $\\hat\\beta$ reduces to the two group means: $\\hat\\beta = \\bar y_1 - \\bar y_0$, the difference in means. Every treated unit then carries positive weight, every control negative — the structural pattern of the previous section, with the wrong-sign off-diagonal empty until covariates enter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nn1 <- 30; n0 <- 50\nd <- c(rep(1, n1), rep(0, n0)); y <- c(rnorm(n1, 5), rnorm(n0, 2))\ndev <- d - mean(d); om <- dev / sum(dev^2); col <- ifelse(om >= 0, teal, rust)\ny1 <- mean(y[d == 1]); y0 <- mean(y[d == 0])\nplot(jitter(d, 0.4), y, pch = 16, col = paste0(col, \"55\"), cex = 0.9,\n     xlim = c(-0.3, 1.3), xaxt = \"n\", xlab = \"\", ylab = \"y\", main = \"Regression on treatment\")\naxis(1, at = c(0, 1), labels = c(\"control\", \"treated\"))\nsegments(0, y0, 1, y1, lwd = 2.6, col = \"grey15\")\npoints(c(0, 1), c(y0, y1), pch = 21, bg = c(rust, teal), col = \"white\", cex = 2.5, lwd = 2)\n```\n\n::: {.cell-output-display}\n![Regression on the treatment alone. Points are the two groups (rust control, teal treated); the large dots are the group means, and the segment joining them has slope $\\hat\\beta = \\bar y_1 - \\bar y_0$, the difference in means.](outcome-weights_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nvtab(c(`beta (lm)` = coef(lm(y ~ d))[[\"d\"]], `y1 - y0` = y1 - y0,\n        `off-diagonal weights` = sum((d == 1 & om < 0) | (d == 0 & om > 0))), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                     | value|\n|:--------------------|-----:|\n|beta (lm)            | 3.318|\n|y1 - y0              | 3.318|\n|off-diagonal weights | 0.000|\n\n\n\nRegression on the treatment alone. Points are the two groups (rust control, teal treated); the large dots are the group means, and the segment joining them has slope $\\hat\\beta = \\bar y_1 - \\bar y_0$, the difference in means.\n:::\n:::\n\n\nThe estimate equals $\\bar y_1 - \\bar y_0$, and no weight carries the wrong sign — the off-diagonal count is zero.\n\n**Simulation — 2×2 difference-in-differences.** Add a period and interact it with the group, and the design has four cells. Each collapses to its mean, and the interaction coefficient is their double contrast,\n\n$$ \\widehat{\\text{DiD}} = (\\bar y_{T,\\text{post}} - \\bar y_{T,\\text{pre}}) - (\\bar y_{C,\\text{post}} - \\bar y_{C,\\text{pre}}). $$ {#eq-outcome-weights-11}\n\nNow there are four cell means, and with them four slopes — the two group trends over time and the two cross-sectional gaps. The DiD is the difference between either parallel pair, trend minus trend or gap minus gap. We simulate 200 units in each group×period cell from $y = 3 + 2g + p + 2\\,(g \\cdot p) + \\varepsilon$, so the true DiD (the interaction) is $2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\ng <- rep(c(1, 1, 0, 0), each = 200); p <- rep(c(0, 1, 0, 1), each = 200)\ny <- 3 + 2 * g + 1 * p + 2 * (g * p) + rnorm(800)\nm <- tapply(y, list(g, p), mean)\nTpre <- m[\"1\", \"0\"]; Tpost <- m[\"1\", \"1\"]; Cpre <- m[\"0\", \"0\"]; Cpost <- m[\"0\", \"1\"]\ncf <- Tpre + (Cpost - Cpre)\nplot(NA, xlim = c(-0.15, 1.25), ylim = range(y), xaxt = \"n\", xlab = \"\", ylab = \"y\",\n     main = \"Difference-in-differences\")\naxis(1, at = c(0, 1), labels = c(\"pre\", \"post\"))\nsegments(0, Tpre, 1, Tpost, lwd = 2.4, col = teal)\nsegments(0, Cpre, 1, Cpost, lwd = 2.4, col = rust)\nsegments(0, Tpre, 1, cf, lty = 2, lwd = 1.6, col = \"grey55\")\nsegments(1, cf, 1, Tpost, lwd = 4, col = \"grey15\")\npoints(c(0, 1, 0, 1), c(Tpre, Tpost, Cpre, Cpost),\n       pch = 21, bg = c(teal, teal, rust, rust), col = \"white\", cex = 2.3, lwd = 2)\ntext(1.02, (cf + Tpost) / 2, \"DiD\", pos = 4, cex = 0.9, col = \"grey15\")\n```\n\n::: {.cell-output-display}\n![The 2×2 difference-in-differences: four cell means (dots), the treated (teal) and control (rust) trends, the parallel-trends counterfactual (dashed), and the DiD (black bar) as the gap between the treated post-mean and that counterfactual.](outcome-weights_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nvtab(c(`treated trend` = Tpost - Tpre, `control trend` = Cpost - Cpre,\n        `pre gap` = Tpre - Cpre, `post gap` = Tpost - Cpost,\n        `DiD (interaction)` = coef(lm(y ~ g * p))[[\"g:p\"]]), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                  | value|\n|:-----------------|-----:|\n|treated trend     | 3.029|\n|control trend     | 0.897|\n|pre gap           | 2.019|\n|post gap          | 4.151|\n|DiD (interaction) | 2.132|\n\n\n\nThe 2×2 difference-in-differences: four cell means (dots), the treated (teal) and control (rust) trends, the parallel-trends counterfactual (dashed), and the DiD (black bar) as the gap between the treated post-mean and that counterfactual.\n:::\n:::\n\n\nThe estimated interaction recovers the true DiD of $2$, and the four cell-mean weights carry the structural signs $(+, -, -, +)$ as long as every cell is populated.\n\nThe clean $2 \\times 2$ has trivial weights — four cell means, each $\\pm 1$. Real difference-in-differences carries covariates: parallel trends holds only *conditional* on $X$, and the comparison has to be modelled. That model is a weighting of outcomes too.\n\nThe doubly-robust DiD of Sant'Anna and Zhao (2020) is AIPW read on the outcome *change* $\\Delta Y = Y_1 - Y_0$: a propensity for treatment, a control-group regression of $\\Delta Y$ on $X$, combined. By the recipe of the last section its estimate is $\\widehat{\\text{ATT}} = \\boldsymbol\\omega' \\Delta Y$, with $\\boldsymbol\\omega' = \\boldsymbol a'(\\mathbf I - \\boldsymbol S)$ — the control-trend smoother $\\boldsymbol S$ and the group weights $\\boldsymbol a = \\boldsymbol w_{\\text{treat}} - \\boldsymbol w_{\\text{cont}}$.\n\n**Simulation — doubly-robust DiD.** Two periods and $n = 2000$: treatment is selected on $x_1$ with thin overlap, $\\Pr(D = 1) = \\Lambda(-0.5 + 2 x_1)$; the control trend depends on $x_1$, so trends are parallel only given $X$; the true ATT is $1$. We fit DR-DiD with `DRDID`, rebuild its weights by hand, and check.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DRDID)\nset.seed(2)\nn  <- 2000\nx1 <- rnorm(n); x2 <- rnorm(n); Xcov <- cbind(1, x1, x2)\nD  <- rbinom(n, 1, plogis(-0.5 + 2 * x1))        # selection into treatment on x1 (thin overlap)\ny0 <- 1 + x1 + 0.5 * x2 + rnorm(n)               # pre-period outcome\ny1 <- y0 + (0.5 + 0.4 * x1) + 1 * D + rnorm(n)   # control trend depends on x1; true ATT = 1\ndY <- y1 - y0\natt <- drdid_panel(y1 = y1, y0 = y0, D = D, covariates = Xcov, boot = FALSE)$ATT\n\n# rebuild the DR-DiD weights: omega = (I - S)' a, acting on the outcome change dY\ne    <- pmin(as.vector(glm(D ~ x1 + x2, family = binomial)$fitted), 1 - 1e-6)\nkeep <- rep(TRUE, n); keep[D == 0] <- e[D == 0] < 0.995     # DRDID's control trimming\nXc   <- Xcov[D == 0, ]\nS    <- matrix(0, n, n); S[, D == 0] <- Xcov %*% solve(crossprod(Xc)) %*% t(Xc)\nw.t  <- keep * D\nw.c  <- keep * e * (1 - D) / (1 - e)\na    <- w.t / sum(w.t) - w.c / sum(w.c)          # group weights, treated minus reweighted control\nomega <- as.vector(a - crossprod(S, a))\n\nXk <- cbind(x1, x2); sds <- apply(Xk, 2, sd)\nvtab(c(`DRDID ATT`                = att,\n       `omega' dY`                = sum(omega * dY),\n       `wrong-sign weights`       = sum((D == 1 & omega < 0) | (D == 0 & omega > 0)),\n       `covariate imbalance, raw` = max(abs((colMeans(Xk[D == 1, ]) - colMeans(Xk[D == 0, ])) / sds)),\n       `covariate imbalance, wtd` = max(abs(as.vector(a %*% Xk) / sds))), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                         |   value|\n|:------------------------|-------:|\n|DRDID ATT                |   0.980|\n|omega' dY                |   0.980|\n|wrong-sign weights       | 151.000|\n|covariate imbalance, raw |   1.198|\n|covariate imbalance, wtd |   0.086|\n\n\n:::\n:::\n\n\n$\\boldsymbol\\omega' \\Delta Y$ reproduces the `DRDID` estimate exactly — the difference-in-differences is a signed weighting of observed outcome *changes*, and the diagnostics of this chapter apply to it. The weighting balances the covariate that drove selection (its standardised imbalance falls from $1.20$ to $0.09$). And $151$ units carry a wrong-sign weight — a treated unit subtracted, or a control added — the signature of a comparison reaching past common support.\n\n### Staggered designs: TWFE at the observation level\n\nNegative weights in staggered designs are usually described at the level of two-by-two comparisons: TWFE averages many such comparisons, and some enter with a negative weight — the forbidden comparisons that use already-treated units as controls (de Chaisemartin and D'Haultfœuille 2020; Goodman-Bacon 2021). That is the effect-weight reading. The outcome-weight reading goes one level down, to the individual $y_{it}$.\n\nTWFE is still FWL: residualise $D_{it}$ on unit and time fixed effects to get $\\tilde D_{it}$, and $\\hat\\beta = \\sum_{it} \\omega_{it} y_{it}$ with $\\omega_{it} = \\tilde D_{it} / \\sum_{jt} \\tilde D_{jt}^2$. A treated observation with $\\omega_{it} < 0$ is a cell whose outcome is subtracted from the estimated effect — used as a control even though it is treated. An untreated observation with $\\omega_{it} > 0$ enters as though it were treated. Both are the same sign flip seen earlier under thin overlap, caused here by the unit-and-time residualisation pushing $\\tilde D_{it}$ past zero: treated cells in late periods of early cohorts, where the fixed-effect prediction of $D_{it}$ exceeds $1$, and untreated cells in early periods of never-treated units, where it falls below $0$.\n\n**Simulation — staggered panel.** Three cohorts: never-treated ($20\\%$), early-treated at period $3$ with effect $\\tau = 3$ ($40\\%$), and late-treated at period $6$ with effect $\\tau = 1$ ($40\\%$), observed across $T = 8$ periods; $y_{it} = \\alpha_i + \\gamma_t + \\tau_g D_{it} + \\varepsilon_{it}$. The high treated share makes the forbidden comparison visible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fixest)\nset.seed(5)\nN <- 300; TT <- 8\ng <- sample(c(0, 3, 6), N, TRUE, prob = c(.2, .4, .4))\npanel <- data.frame(id = rep(1:N, each = TT), t = rep(1:TT, N))\npanel$g <- g[panel$id]\npanel$D <- as.integer(panel$g > 0 & panel$t >= panel$g)\ntau <- ifelse(panel$g == 3, 3, ifelse(panel$g == 6, 1, 0))\nalpha <- rnorm(N); gamma <- seq(0, 1.4, length.out = TT)\npanel$y <- alpha[panel$id] + gamma[panel$t] + tau * panel$D + rnorm(nrow(panel), 0, 0.5)\n\nDtil <- resid(feols(D ~ 1 | id + t, data = panel))\nomega_tw <- Dtil / sum(Dtil^2)\nn1 <- sum(panel$D)\nvtab(c(`true ATT`              = mean(tau[panel$D == 1]),\n       `TWFE`                  = coef(feols(y ~ D | id + t, panel))[[\"D\"]],\n       `omega' y`              = sum(omega_tw * panel$y),\n       `treated, omega < 0`    = sum(panel$D == 1 & omega_tw < 0),\n       `untreated, omega > 0`  = sum(panel$D == 0 & omega_tw > 0)), 3)\n```\n\n::: {.cell-output-display}\n\n\n|                     |   value|\n|:--------------------|-------:|\n|true ATT             |   2.426|\n|TWFE                 |   1.915|\n|omega' y             |   1.915|\n|treated, omega < 0   | 384.000|\n|untreated, omega > 0 | 551.000|\n\n\n:::\n:::\n\n\nThe TWFE coefficient sits well below the true ATT, and $\\sum \\omega_{it} y_{it}$ reproduces it exactly. Hundreds of treated cells carry a negative weight: these are the early cohort's cells in periods $6$–$8$, the ones where the unit-and-time prediction of $D$ exceeds $1$ and the residual $\\tilde D_{it}$ flips sign. Their outcomes are subtracted from $\\hat\\beta$ — the observation-level signature of the Bacon forbidden comparison.\n\nThe wrong-sign diagnostic in a panel is by observation $(i, t)$, not by unit. In the cross-sectional case earlier, the fix was to trim wrong-sign observations and refit. In a panel, trimming specific $(i, t)$ cells removes observations that anchor that unit's fixed effect and distorts the estimates for its remaining cells. The response in the staggered setting is to switch estimators — imputation (Borusyak, Jaravel, and Spiess 2024), Callaway and Sant'Anna, or Sun and Abraham — that avoid the forbidden comparison by construction. The imputation estimator, for example, fits unit and time fixed effects on untreated observations alone and imputes each treated cell's counterfactual; because its smoother draws only on untreated outcomes, the weight on every treated cell reduces to $1/n_1$ and no treated observation can count as a control.\n\n### Synthetic difference-in-differences: a rank-one weighting\n\nSynthetic difference-in-differences is a weighted two-way fixed effects regression, from Arkhangelsky, Athey, Hirshberg, Imbens, and Wager (2021). The estimators so far imply their weights. This one chooses them:\n\n$$ (\\hat\\tau, \\hat\\mu, \\hat\\alpha, \\hat\\beta) = \\arg\\min \\sum_{i}\\sum_{t} \\big(Y_{it} - \\mu - \\alpha_i - \\beta_t - W_{it}\\tau\\big)^2\\, \\omega_i \\lambda_t. $$ {#eq-outcome-weights-12}\n\nThe recipe: fit $\\omega_i$ on the control units so the reweighted control path tracks the treated path over the pre-period, and fit $\\lambda_t$ on the pre-periods so the reweighted pre-period resembles the post-period. Treated units enter at $1/N_1$, post-periods at $1/T_1$. Both fitted sets lie on the simplex, non-negative and summing to one.\n\n@eq-outcome-weights-12 is weighted least squares, so the FWL reading of @eq-omega goes through with the weights carried along. Then $\\hat\\tau$ is again a weighting of outcomes. Let $u_i$ be $1/N_1$ for a treated unit and $-\\omega_i$ for a control. Let $v_t$ be $1/T_1$ for a post-period and $-\\lambda_t$ for a pre-period. Then\n\n$$ \\hat\\tau = \\sum_i \\sum_t \\omega_{it}\\, Y_{it}, \\qquad \\omega_{it} = u_i \\, v_t. $$ {#eq-outcome-weights-13}\n\nIn words, the weight on a cell is a unit part times a time part. Collect the weights into an $N \\times T$ matrix $\\boldsymbol\\Omega$, one entry per cell. Then @eq-outcome-weights-13 reads $\\boldsymbol\\Omega = \\boldsymbol u \\boldsymbol v'$, an outer product, and a matrix of that form has **rank one**. Every row is a multiple of every other row. So each unit carries the same weight profile over time, scaled by its own $u_i$, and each period weights the units in the same pattern, scaled by its own $v_t$. There is no unit-by-period interaction in the weights.\n\nThat product structure is what makes this a difference-in-differences. A double difference contrasts units and contrasts periods, and multiplying the two contrasts gives a rank-one weighting. We come back to the rank below, where it separates the block designs from the staggered ones.\n\nMultiply @eq-outcome-weights-13 out and we get the $2 \\times 2$ of @eq-outcome-weights-11 with two of its four averages reweighted, the control average by $\\omega$ and the pre-period average by $\\lambda$:\n\n$$ \\hat\\tau = \\Big(\\bar Y_{T,\\text{post}} - \\sum_{t \\in \\text{pre}} \\lambda_t \\bar Y_{T,t}\\Big) - \\Big(\\sum_{i \\in C} \\omega_i \\bar Y_{i,\\text{post}} - \\sum_{i \\in C}\\sum_{t \\in \\text{pre}} \\omega_i \\lambda_t Y_{it}\\Big). $$ {#eq-outcome-weights-14}\n\nThe four blocks keep the signs $(+, -, -, +)$ of @eq-outcome-weights-11. Only the averages inside two of them change, and they are no longer uniform.\n\n**Simulation — the outcome weights of synthetic DiD.** A panel of $40$ control and $10$ treated units over $12$ pre- and $6$ post-periods. Untreated outcomes are\n\n$$ Y_{it}(0) = \\alpha_i + \\beta_t + \\boldsymbol f_i' \\boldsymbol g_t + \\varepsilon_{it}, $$ {#eq-factor-dgp}\n\nwith a unit effect $\\alpha_i$, a linear time effect $\\beta_t$, two factors in $\\boldsymbol g_t$ (one linear in $t$, one a sine), loadings $\\boldsymbol f_i \\sim N(\\boldsymbol 0, \\mathbf I)$ shifted by $0.8$ for the treated units, and $\\varepsilon_{it} \\sim N(0, 0.3^2)$. The spread in $\\boldsymbol f_i$ makes the control trends differ from each other, and the shift makes the treated trend differ from all of them. The true ATT is $2$. We fit with `synthdid`, then rebuild @eq-outcome-weights-13 by hand from the fitted $\\omega$ and $\\lambda$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(synthdid)\nset.seed(11)\nN0 <- 40; N1 <- 10; N <- N0 + N1; T0 <- 12; T1 <- 6; Tt <- T0 + T1\nf <- cbind(rnorm(N), rnorm(N)); f[(N0 + 1):N, ] <- f[(N0 + 1):N, ] + 0.8\ng <- cbind(seq(0, 2, length = Tt), sin(seq(0, 3, length = Tt)))\nY <- outer(rnorm(N, 0, .5), rep(1, Tt)) + outer(rep(1, N), seq(0, 1, length = Tt)) +\n     f %*% t(g) + matrix(rnorm(N * Tt, 0, .3), N, Tt)\nW <- matrix(0, N, Tt); W[(N0 + 1):N, (T0 + 1):Tt] <- 1\nY <- Y + 2 * W                                          # true ATT = 2\n\nest <- synthdid_estimate(Y, N0, T0)\nwt  <- attr(est, \"weights\")\nu <- c(-wt$omega,  rep(1 / N1, N1))                     # unit part\nv <- c(-wt$lambda, rep(1 / T1, T1))                     # time part\nOmega <- outer(u, v)                                    # outcome weight on cell (i, t)\n```\n:::\n\n\nThree routes should give the same number: what `synthdid` reports, the weighting @eq-outcome-weights-13 applies to the observed outcomes, and the weighted regression of @eq-outcome-weights-12.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncw <- outer(c(wt$omega, rep(1 / N1, N1)), c(wt$lambda, rep(1 / T1, T1)))\ndd <- data.frame(y = as.vector(Y), Wt = as.vector(W), i = factor(rep(1:N, Tt)),\n                 t = factor(rep(1:Tt, each = N)), cw = as.vector(cw))\ntau3 <- c(`synthdid_estimate()`              = as.numeric(est),\n          `sum of Omega * Y, Omega by hand` = sum(Omega * Y),\n          `weighted TWFE regression`        = coef(lm(y ~ Wt + i + t, dd,\n                                                      weights = dd$cw))[[\"Wt\"]])\nvtab(c(tau3, `largest gap between them` = max(abs(tau3 - tau3[1]))), 6)\n```\n\n::: {.cell-output-display}\n\n\n|                                |    value|\n|:-------------------------------|--------:|\n|synthdid_estimate()             | 2.205444|\n|sum of Omega * Y, Omega by hand | 2.205444|\n|weighted TWFE regression        | 2.205444|\n|largest gap between them        | 0.000000|\n\n\n:::\n:::\n\n\nThe gap between them is zero to machine precision. The outer-product form is what `synthdid` computes.\n\nWriting the weights this way puts three constraints on them. First, the rank is one, since a cell's weight is a unit part times a time part. Second, each margin sums to zero on its own: $\\omega$ and $\\lambda$ each sum to one, and the treated and post-period blocks each contribute an offsetting one. Third, no cell carries a wrong sign: no treated post-period cell is subtracted, and no control pre-period cell is added. We check all three.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchk <- rbind(`rank of the weight matrix`     = c(sum(svd(Omega)$d > 1e-12), 1),\n             `weights summed over units`     = c(sum(u), 0),\n             `weights summed over periods`   = c(sum(v), 0),\n             `treated post-cells, omega < 0` = c(sum(Omega[(N0+1):N, (T0+1):Tt] < 0), 0),\n             `control pre-cells, omega < 0`  = c(sum(Omega[1:N0, 1:T0] < 0), 0))\ncolnames(chk) <- c(\"found\", \"should be\")\nmtab(chk, 4)\n```\n\n::: {.cell-output-display}\n\n\n|                              | found| should be|\n|:-----------------------------|-----:|---------:|\n|rank of the weight matrix     |     1|         1|\n|weights summed over units     |     0|         0|\n|weights summed over periods   |     0|         0|\n|treated post-cells, omega < 0 |     0|         0|\n|control pre-cells, omega < 0  |     0|         0|\n\n\n:::\n:::\n\n\nAll three hold. Note that the double zero-sum is stronger than the single sum-to-zero of @eq-omega, which constrains the weights only in total. Here they vanish along each margin. The signs are fixed by construction too: a treated post-period cell gets $1/(N_1 T_1) > 0$, and a control pre-period cell gets $\\omega_i \\lambda_t > 0$, because the simplex rules out a negative $\\omega_i$. The doubly-robust fit above produced $151$ wrong-sign units. Synthetic DiD cannot produce any.\n\nThe remaining question is how much of the panel the comparison uses. Counting the non-zero weights is one answer, but it treats a weight of $0.4$ and a weight of $0.001$ alike. The standard summary that does not is the effective sample size, $1/\\sum_i \\omega_i^2$ for weights summing to one. It equals $N_0$ when every control is weighted equally, and $1$ when a single control carries everything. In between, a weighted average with an effective size of $m$ is about as precise as an unweighted average of $m$ observations. Both margins here are sparse, so both effective counts fall below the nominal $40$ controls and $12$ pre-periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndsg <- c(sum(wt$omega > 1e-8), 1 / sum(wt$omega^2),\n         sum(wt$lambda > 1e-8), 1 / sum(wt$lambda^2), wt$lambda[T0])\nnames(dsg) <- c(sprintf(\"controls with non-zero weight (of %d)\", N0),\n                sprintf(\"effective controls, 1/sum(omega^2) (of %d)\", N0),\n                sprintf(\"pre-periods with non-zero weight (of %d)\", T0),\n                sprintf(\"effective pre-periods (of %d)\", T0),\n                \"weight on the last pre-period\")\nvtab(dsg)\n```\n\n::: {.cell-output-display}\n\n\n|                                           |  value|\n|:------------------------------------------|------:|\n|controls with non-zero weight (of 40)      | 23.000|\n|effective controls, 1/sum(omega^2) (of 40) | 14.557|\n|pre-periods with non-zero weight (of 12)   |  2.000|\n|effective pre-periods (of 12)              |  1.091|\n|weight on the last pre-period              |  0.957|\n\n\n:::\n:::\n\n\nOnly $23$ of the $40$ controls get any weight, and the effective count $1/\\sum_i \\omega_i^2$ is $14.6$. The time margin is sparser: an effective $1.09$ pre-periods, with $0.957$ of the mass on the last one. The counterfactual level is anchored on the single period before treatment, so the estimate inherits that period's noise. We can read all of this off the weights. None of it is visible in $\\hat\\tau$.\n\nWe plot the two margins to see where the mass sits. The left panel sorts the fitted control weights $\\omega_i$ from largest to smallest, which shows how many controls the comparison uses. The right panel keeps the pre-period weights $\\lambda_t$ in time order, which shows which periods the counterfactual is built from.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4.2, 4.2, 2.6, 1))\nos <- sort(wt$omega, decreasing = TRUE)\nbarplot(os, col = ifelse(os > 1e-8, teal, \"grey85\"), border = NA,\n        xlab = \"control units, sorted\", ylab = expression(omega[i]),\n        main = \"Unit weights\")\nbarplot(wt$lambda, names.arg = 1:T0, border = NA,\n        col = ifelse(wt$lambda > 1e-8, rust, \"grey85\"),\n        xlab = \"pre-period\", ylab = expression(lambda[t]), main = \"Time weights\")\n```\n\n::: {.cell-output-display}\n![The two margins of the synthetic DiD weight matrix. Left: fitted control-unit weights $\\omega_i$, sorted. $23$ of $40$ are non-zero, and the $17$ the simplex sets to zero lie flat against the axis. Right: fitted pre-period weights $\\lambda_t$. Almost all the mass is on the last pre-period, so the counterfactual level is anchored just before treatment.](outcome-weights_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### The rank of the weight matrix\n\nSynthetic difference-in-differences has a rank-one $\\boldsymbol\\Omega$ by construction. So does the plain $2 \\times 2$: set $u_i$ and $v_t$ to the uniform $\\pm 1/N_g$ and $\\pm 1/T_g$ and @eq-outcome-weights-11 reappears. Staggered adoption gives a higher rank, and the rank counts the cohorts.\n\nWrite the staggered treatment matrix as a sum over adoption cohorts, $\\boldsymbol W = \\sum_{k=1}^{K} \\boldsymbol c_k \\boldsymbol s_k'$. Here $\\boldsymbol c_k$ indicates the units of cohort $k$, and $\\boldsymbol s_k$ the periods from its adoption date on. That is a sum of $K$ rank-one terms. Residualising on unit and time dummies is a double centring, $(\\mathbf I - \\boldsymbol P)\\, \\boldsymbol W \\,(\\mathbf I - \\boldsymbol Q)$, and double centring cannot raise a rank. So $\\operatorname{rank}(\\boldsymbol\\Omega) \\le K$, with equality generically.\n\nWe check the bound directly. Each panel has $60$ units over $20$ periods, with one to five adoption dates plus a never-treated group. For each we build the staggered TWFE weights, then count the non-zero singular values of $\\boldsymbol\\Omega$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4)\nNs <- 60; Ts <- 20\nrk <- sapply(list(10, c(8, 14), c(6, 10, 14), c(6, 9, 12, 15), c(5, 8, 11, 14, 17)),\n  function(dates) {\n    coh <- sample(c(dates, Inf), Ns, replace = TRUE)     # Inf = never treated\n    Ws  <- matrix(0, Ns, Ts)\n    for (i in 1:Ns) if (is.finite(coh[i])) Ws[i, coh[i]:Ts] <- 1\n    ds  <- data.frame(Wt = as.vector(Ws), i = factor(rep(1:Ns, Ts)),\n                      t = factor(rep(1:Ts, each = Ns)))\n    Wtil <- residuals(lm(Wt ~ i + t, ds))\n    Om   <- matrix(Wtil / sum(Wtil^2), Ns, Ts)\n    c(`treated cohorts` = length(dates),\n      `rank of Omega`   = sum(svd(Om)$d > 1e-9 * max(svd(Om)$d)))\n  })\ncolnames(rk) <- c(\"1 date\", \"2 dates\", \"3 dates\", \"4 dates\", \"5 dates\")\nmtab(rk)\n```\n\n::: {.cell-output-display}\n\n\n|                | 1 date| 2 dates| 3 dates| 4 dates| 5 dates|\n|:---------------|------:|-------:|-------:|-------:|-------:|\n|treated cohorts |      1|       2|       3|       4|       5|\n|rank of Omega   |      1|       2|       3|       4|       5|\n\n\n:::\n:::\n\n\nThe rank is the number of treated cohorts. This ties the chapter's difference-in-differences material together. A block design has one adoption date, so its weight matrix is rank one. The plain $2 \\times 2$ and synthetic difference-in-differences are the same object at two settings of the margins, uniform in the first and fitted in the second. Staggered adoption raises the rank. Once a cell's weight no longer factors into a unit part times a time part, a treated cell can enter negatively. In the block case it cannot, since every treated post-period cell gets $u_i v_t = 1/(N_1 T_1) > 0$. The forbidden comparisons need the extra rank.\n\n### Reweighting controls toward parallel trends\n\nSynthetic difference-in-differences chooses weights so the control path tracks the treated path. A natural next step is to weight observations by whether parallel trends holds for them, up where it holds and down where it fails. Can we do that?\n\nNot as stated. Parallel trends is a statement about two group means, $E[\\Delta Y(0) \\mid D = 1] = E[\\Delta Y(0) \\mid D = 0]$. No single observation either has it or lacks it. So in the model behind @eq-outcome-weights-11 there is nothing at the unit level for a weight to act on.\n\nThe question means something only under a model where trends vary across units: unit-specific slopes, or a factor structure $Y_{it}(0) = \\alpha_i + \\beta_t + \\boldsymbol f_i' \\boldsymbol g_t + \\varepsilon_{it}$. Then each unit has its own trend, \"parallel to the treated group\" becomes a per-unit property, and we can reweight controls toward those whose $\\boldsymbol f_i$ resembles the treated group's. That is what synthetic difference-in-differences already does. So the proposal asks us to change the identifying model, and estimators for the changed model exist. Hazlett and Xu (2018) balance pre-treatment trajectories by mean or kernel balancing. Imai, Kim, and Wang (2023) match on treatment and outcome history. Doudchenko and Imbens (2016) set out the family in which difference-in-differences and synthetic control are two corners of one weighting problem.\n\nWe can measure what the reweighting gains. @eq-outcome-weights-13 has two margins, so we can separate them.\n\n**Simulation — which margin does the work.** Two panels of $40$ controls and $10$ treated over $12$ pre- and $6$ post-periods, with a true ATT of $2$. Both carry a unit effect $\\alpha_i$, a linear time effect $\\beta_t$, and an AR(1) shock $\\varepsilon_{it}$ with $\\rho = 0.5$. These three are common to almost any panel, and none of them breaks parallel trends: $\\alpha_i$ differences away and $\\beta_t$ is shared by both groups, so a difference-in-differences removes them whatever the weights are.\n\nParallel trends fails only when the treated and control groups have *different* untreated trends, so a term that varies by unit and moves with $t$ is what we have to put in. Without one there is nothing for the weights to fix. The two panels are two forms of it. The `factor` panel uses the $\\boldsymbol f_i' \\boldsymbol g_t$ of @eq-factor-dgp. The `slopes` panel replaces it with a unit-specific linear trend,\n\n$$ Y_{it}(0) = \\alpha_i + \\beta_t + s_i \\, t + \\varepsilon_{it}, \\qquad s_i \\sim N(0,\\, 0.08^2), $$ {#eq-slopes-dgp}\n\nwith $s_i$ shifted up by $0.12$ for the treated units. So each unit has its own growth rate, and the treated units grow faster on average, by about one and a half standard deviations of the control slopes. Note that $s_i t$ is itself a one-factor model, with loading $s_i$ and factor $g_t = t$. It is the simplest member of the class @eq-factor-dgp describes, which is the class synthetic difference-in-differences is built for, so this is a leading case and not a special one. We run synthetic DiD four ways: both margins uniform, which is plain difference-in-differences; unit weights fitted with time weights uniform; time weights fitted with unit weights uniform; and both fitted. $400$ replications.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(parallel)\npanel <- function(kind, N0 = 40, N1 = 10, T0 = 12, T1 = 6, sig = .4, rho = .5) {\n  N <- N0 + N1; Tt <- T0 + T1\n  a <- rnorm(N, 0, 1); a[(N0 + 1):N] <- a[(N0 + 1):N] + 1\n  e <- matrix(0, N, Tt); e[, 1] <- rnorm(N, 0, sig / sqrt(1 - rho^2))\n  for (t in 2:Tt) e[, t] <- rho * e[, t - 1] + rnorm(N, 0, sig)\n  Y0 <- outer(a, rep(1, Tt)) + outer(rep(1, N), seq(0, 1.5, length = Tt)) + e\n  if (kind == \"factor\") {\n    f <- cbind(rnorm(N), rnorm(N)); f[(N0 + 1):N, ] <- f[(N0 + 1):N, ] + 0.8\n    g <- cbind(seq(0, 2, length = Tt), sin(seq(0, 3, length = Tt)))\n    Y0 <- Y0 + f %*% t(g)\n  } else {\n    s <- rnorm(N, 0, .08); s[(N0 + 1):N] <- s[(N0 + 1):N] + .12   # unit slopes\n    Y0 <- Y0 + outer(s, 1:Tt)\n  }\n  W <- matrix(0, N, Tt); W[(N0 + 1):N, (T0 + 1):Tt] <- 1\n  list(Y = Y0 + 2 * W, N0 = N0, N1 = N1, T0 = T0, T1 = T1)\n}\nmargins <- function(r, kind) {\n  set.seed(5000 + r); p <- panel(kind); N0 <- p$N0; T0 <- p$T0\n  fx <- function(om, lam) as.numeric(synthdid_estimate(p$Y, N0, T0,\n          weights = list(omega = om, lambda = lam)))     # NULL = fit this margin\n  unif.o <- rep(1 / N0, N0); unif.l <- rep(1 / T0, T0)\n  c(`both uniform (DiD)` = fx(unif.o, unif.l), `unit weights only` = fx(NULL, unif.l),\n    `time weights only`  = fx(unif.o, NULL),   `both fitted (SDID)` = fx(NULL, NULL))\n}\nres <- lapply(c(\"factor\", \"slopes\"), function(kind) {\n  M <- simplify2array(mclapply(1:400, margins, kind = kind, mc.cores = 6))\n  cbind(bias = rowMeans(M) - 2, sd = apply(M, 1, sd), rmse = sqrt(rowMeans((M - 2)^2)))\n})\nout <- cbind(res[[1]], res[[2]])\ncolnames(out) <- paste(rep(c(\"factor\", \"slopes\"), each = 3), colnames(res[[1]]))\nmtab(out)\n```\n\n::: {.cell-output-display}\n\n\n|                   | factor bias| factor sd| factor rmse| slopes bias| slopes sd| slopes rmse|\n|:------------------|-----------:|---------:|-----------:|-----------:|---------:|-----------:|\n|both uniform (DiD) |       0.729|     0.403|       0.833|       1.083|     0.284|       1.120|\n|unit weights only  |       0.173|     0.337|       0.379|       0.603|     0.231|       0.645|\n|time weights only  |       0.082|     0.285|       0.296|       0.536|     0.203|       0.573|\n|both fitted (SDID) |       0.044|     0.299|       0.302|       0.403|     0.208|       0.453|\n\n\n:::\n:::\n\n\nReweighting helps, and by a lot. Under the factor structure the bias falls from $0.73$ to $0.04$ with both margins fitted. Each margin helps alone: $0.17$ from the unit weights, $0.08$ from the time weights. Which margin matters is not fixed in advance. Here the time weights do slightly more, because the factor paths are smooth, so anchoring on the periods just before treatment removes most of the divergence. The fitted $\\lambda$ above showed the same thing when it put $0.957$ on the last pre-period.\n\nThe `slopes` panel is harder. The bias falls from $1.08$ only to $0.40$, and no setting of the margins does better. Before the algebra, it is worth being clear about what is being estimated, because the treatment effect here is a constant $2$ and nothing about it depends on $s_i$. The estimand is the ATT, $E[Y_{it}(1) - Y_{it}(0) \\mid \\text{treated}, \\text{post}]$. We observe $Y_{it}(1)$ for those cells. We never observe $Y_{it}(0)$ for them, and building that counterfactual is the whole of the estimation problem. So the weights are not there to learn anything about the effect. They are there to impute one unobserved quantity, and any bias is an error in that imputation.\n\nThat is why the trend matters even though the effect does not involve it. The treated group's own untreated path contains $s_i t$. Get the growth rate of the counterfactual wrong and it sits at the wrong level by the post-period, and the gap is charged to the treatment. Two parts of that path cost nothing: a unit level differences away inside each bracket, and a time path shared by both groups appears in both brackets and cancels. So only a leftover trend and the noise carried by the weights can bias this estimator.\n\nThe weights never see $s_i$, and nothing in the estimator estimates it. What `synthdid` matches is the pre-period outcome *path*: it picks $\\omega$ so the weighted control path tracks the treated path across the twelve pre-periods. If it matched the systematic part of that path, the trends would agree as a by-product and the bias would vanish. Two things stop it. The observed paths carry noise, so $\\omega$ is fitted to $\\alpha_i + \\beta_t + s_i t + \\varepsilon_{it}$ and answers to $\\varepsilon$ as much as to $s$. And `synthdid` shrinks $\\omega$ toward uniform, which limits how far it will concentrate on the steep controls. We vary both and read the bias: the AR(1) innovation standard deviation at its default $0.4$ and at $0.05$, and the shrinkage on and off. $300$ replications per cell.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmismatch <- function(r, sig, off) {\n  set.seed(5000 + r); p <- panel(\"slopes\", sig = sig)\n  est <- if (off) synthdid_estimate(p$Y, p$N0, p$T0, zeta.omega = 1e-8) else\n                  synthdid_estimate(p$Y, p$N0, p$T0)   # default: omit zeta.omega, never pass NULL\n  as.numeric(est) - 2\n}\ncells <- expand.grid(sig = c(.4, .05), off = c(FALSE, TRUE))\nbias4 <- mapply(function(sig, off)\n           mean(unlist(mclapply(1:300, mismatch, sig = sig, off = off, mc.cores = 6))),\n           cells$sig, cells$off)\nnames(bias4) <- sprintf(\"shock sd %.2f, shrinkage %s\", cells$sig,\n                        ifelse(cells$off, \"off\", \"on\"))\nvtab(bias4, 4)\n```\n\n::: {.cell-output-display}\n\n\n|                             |  value|\n|:----------------------------|------:|\n|shock sd 0.40, shrinkage on  | 0.4000|\n|shock sd 0.05, shrinkage on  | 0.0480|\n|shock sd 0.40, shrinkage off | 0.3269|\n|shock sd 0.05, shrinkage off | 0.0183|\n\n\n:::\n:::\n\n\nCut the noise by a factor of eight and the bias falls from $0.40$ to $0.05$. Switch the shrinkage off as well and it falls to $0.02$. So the residual trend is not something the design cannot reach. It is what fitting weights on a short and noisy pre-period leaves behind, with a little added by the shrinkage. Given a clean pre-period the weights match the trend on their own, still without estimating any slope.\n\nA harder limit sits behind all of this. Reweighting controls can only produce a weighted average of the control trends, so when the treated group's trend is steeper than every control's, no weighting reaches it. That is the same overlap problem, now in the design: thin overlap showed up earlier as wrong-sign weights because OLS extrapolates, whereas a simplex weight cannot extrapolate at all. In this panel the treated trend usually does sit inside the range the controls span, so that limit is not what the $0.40$ is made of.\n\nOne practical note before leaving the `slopes` panel. If we are confident the trends really are unit-specific and linear, the direct response is to put unit-specific linear trends in the regression, not to reweight. Reweighting is the tool for when we do not want to commit to a functional form for the trend heterogeneity, which is the case @eq-factor-dgp stands in for. The linear panel is used here because it is the sharpest test of that tool: a single trend the weights either match or do not.\n\n### What reweighting costs\n\nWeights fitted on pre-period outcomes are functions of $\\boldsymbol Y$. Two consequences follow. First, $\\hat\\tau$ is no longer linear in $\\boldsymbol Y$. So @eq-outcome-weights-13 describes the estimate at the fitted weights, and it is no longer the decomposition @eq-omega gives for OLS. Inference has to account for the weights being estimated, and `synthdid` does that by jackknife or bootstrap. Second, selecting on a noisy pre-period statistic is a pretest. Roth (2022) shows that conditioning the analysis on passing a parallel-trends test distorts the point estimate and undercovers. A hard rule keeps or drops a control. A kernel gives it a weight between zero and one instead. Both tie the weight to a noisy pre-period statistic, so switching from the hard rule to the kernel does not avoid the problem.\n\nThe specific problem is regression to the mean. Let $w$ be the fitted control weights, and $\\bar\\varepsilon_{\\text{pre}}$, $\\bar\\varepsilon_{\\text{post}}$ the weighted pre- and post-period shocks. Since $w$ is built from pre-period outcomes, it correlates with $\\bar\\varepsilon_{\\text{pre}}$ and not with the fresh post-period noise. The bias is then\n\n$$ \\operatorname{Cov}(w, \\bar\\varepsilon_{\\text{pre}})\\,(1 - \\beta), \\qquad \\beta = \\frac{\\operatorname{Cov}(\\bar\\varepsilon_{\\text{pre}}, \\bar\\varepsilon_{\\text{post}})}{\\operatorname{Var}(\\bar\\varepsilon_{\\text{pre}})}. $$ {#eq-outcome-weights-15}\n\nIn words, the bias is how hard we selected on pre-period noise, times the share of that noise which does not persist. Both factors move with the serial correlation $\\rho$, in opposite directions. So the shape depends on how we build the matching variable.\n\n**Simulation — matching on pre-period outcomes.** Here parallel trends holds: no group differs in trend at any date. The two groups differ by a persistent level gap of $1.5$. We scale the AR(1) shock to hold its marginal standard deviation at $0.5$ for every $\\rho$, so $\\rho$ changes persistence alone and not the amount of noise. We keep the $10$ controls closest to the treated group on a pre-period level, measured two ways: the last pre-period alone, and the mean of all eight. We sweep $\\rho$ over $2000$ replications.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrtm.panel <- function(rho, T0 = 8, T1 = 6, N0 = 40, N1 = 10, sig = .5, delta = 1.5) {\n  N <- N0 + N1; Tt <- T0 + T1\n  a <- rnorm(N, 0, 1); a[(N0 + 1):N] <- a[(N0 + 1):N] + delta   # persistent level gap\n  e <- matrix(0, N, Tt); e[, 1] <- rnorm(N, 0, sig)             # marginal sd fixed at sig\n  for (t in 2:Tt) e[, t] <- rho * e[, t - 1] + rnorm(N, 0, sig * sqrt(1 - rho^2))\n  Y <- outer(a, rep(1, Tt)) + outer(rep(1, N), seq(0, 1.5, length = Tt)) + e\n  Y[(N0 + 1):N, (T0 + 1):Tt] <- Y[(N0 + 1):N, (T0 + 1):Tt] + 2  # true ATT = 2\n  list(Y = Y, N0 = N0, N1 = N1, T0 = T0, T1 = T1)\n}\nrtm.est <- function(p, with.sdid = FALSE) {\n  N0 <- p$N0; N1 <- p$N1; T0 <- p$T0; T1 <- p$T1; Y <- p$Y; trt <- (N0 + 1):(N0 + N1)\n  dd   <- function(w) sum(outer(c(-w, rep(1 / N1, N1)),\n                                c(rep(-1 / T0, T0), rep(1 / T1, T1))) * Y)\n  near <- function(mc, mt) { w <- rep(0, N0); w[order(abs(mc - mt))[1:10]] <- 1 / 10; w }\n  out <- c(DiD                    = dd(rep(1 / N0, N0)),\n           `match, 1 pre-period`  = dd(near(Y[1:N0, T0], mean(Y[trt, T0]))),\n           `match, 8-period mean` = dd(near(rowMeans(Y[1:N0, 1:T0]), mean(Y[trt, 1:T0]))))\n  if (with.sdid) out <- c(out, SDID = as.numeric(synthdid_estimate(Y, N0, T0)))\n  out\n}\nrhos <- c(0, .2, .4, .6, .8, .95)\nB <- sapply(rhos, function(rho) {\n  M <- simplify2array(mclapply(1:2000,\n         function(r) { set.seed(r); rtm.est(rtm.panel(rho)) }, mc.cores = 6))\n  rowMeans(M) - 2\n})\ncolnames(B) <- paste0(\"rho=\", rhos)\nmtab(B, 4)\n```\n\n::: {.cell-output-display}\n\n\n|                     |   rho=0| rho=0.2| rho=0.4| rho=0.6| rho=0.8| rho=0.95|\n|:--------------------|-------:|-------:|-------:|-------:|-------:|--------:|\n|DiD                  | -0.0017| -0.0023| -0.0030| -0.0039| -0.0051|  -0.0047|\n|match, 1 pre-period  |  0.0271|  0.0240|  0.0192|  0.0129|  0.0031|  -0.0067|\n|match, 8-period mean |  0.0336|  0.0455|  0.0617|  0.0792|  0.0810|   0.0336|\n\n\n:::\n:::\n\n\nPlain difference-in-differences is unbiased throughout, since parallel trends holds. Matching is not. Matched on the last pre-period alone, the bias is $0.027$ at $\\rho = 0$ and falls to nothing as $\\rho$ approaches one. That is the pattern Daw and Hatfield (2018) report: the bias rises as serial correlation weakens. Matched on the eight-period mean the shape changes. The bias is $0.034$ at $\\rho = 0$, rises to $0.081$ at $\\rho = 0.8$, then falls away.\n\n@eq-outcome-weights-15 explains both. With one pre-period, $\\operatorname{Var}(\\varepsilon_{\\text{pre}})$ is the same for every $\\rho$. The covariance factor is then flat, and the bias tracks $1 - \\beta$, which falls. With an eight-period average, that variance climbs from $\\sigma^2/8$ toward $\\sigma^2$ as shocks persist. The two factors move against each other, and the product peaks in the middle. So averaging more pre-periods moves the worst case to higher persistence. At moderate persistence it makes the bias larger.\n\nThe sign is always the same. The treated group sits above the controls in level, so matching picks controls with a high transitory shock. That shock reverts. The control group's measured change is then too small, and $\\hat\\tau$ too large. This is a bias, not a variance, so it does not shrink with the sample. Coverage gets worse as $n$ grows.\n\nSynthetic difference-in-differences fits its weights on the same pre-period outcomes, so it is open to the same problem. We add it to the comparison at $\\rho = 0.8$, where the eight-period matcher is at its worst, over $600$ replications.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nM4 <- simplify2array(mclapply(1:600,\n        function(r) { set.seed(r); rtm.est(rtm.panel(.8), with.sdid = TRUE) }, mc.cores = 6))\nmtab(cbind(bias = rowMeans(M4) - 2, sd = apply(M4, 1, sd),\n           rmse = sqrt(rowMeans((M4 - 2)^2))), 4)\n```\n\n::: {.cell-output-display}\n\n\n|                     |    bias|     sd|   rmse|\n|:--------------------|-------:|------:|------:|\n|DiD                  | -0.0121| 0.1487| 0.1491|\n|match, 1 pre-period  | -0.0050| 0.1894| 0.1893|\n|match, 8-period mean |  0.0731| 0.1844| 0.1982|\n|SDID                 | -0.0102| 0.1360| 0.1362|\n\n\n:::\n:::\n\n\nAt $\\rho = 0.8$ the eight-period matching estimator has a bias of $0.073$. Synthetic difference-in-differences has $-0.010$, and a smaller standard deviation than either alternative. The reason is that `synthdid` fits $\\omega$ with an intercept. It never has to match pre-period levels, only trajectories up to a constant. Matching on levels is what produces regression to the mean, and the intercept removes the need for it. Chabé-Ferret (2015, 2017) gets the same result from theory: combining difference-in-differences with conditioning on pre-treatment outcomes does not add the strengths of both, and it can raise the bias.\n\nOne asymmetry to close. Everything above reweights controls. That leaves the estimand alone and costs variance. Downweighting treated units is different. The estimand is then no longer the ATT. It becomes the average effect for the treated units that happened to look well matched. Report the change when it happens.\n\n### Implied versus chosen\n\nOne distinction cuts across everything above. OLS, AIPW, DML, TWFE, and the imputation estimator all *imply* weights — they fall out of the estimation and are diagnosed afterward. Synthetic controls and synthetic difference-in-differences *choose* weights as part of the design, selecting $\\boldsymbol\\omega$ to balance pre-treatment outcomes or covariates. For those estimators $\\hat\\tau = \\boldsymbol\\omega'\\boldsymbol Y$ is the definition, not a decomposition; the balance and extrapolation checks of this chapter still apply, but what they diagnose is the designer's choice rather than a side effect of the estimator.\n\nA closing caution, with the qualification the last two sections add. These weights diagnose estimation. They show which comparisons a difference-in-differences rests on, and whether it uses non-overlapping or forbidden ones. They do not test identification. Parallel trends is an assumption about the treated group's unobserved untreated path, and a negative weight and a failure of parallel trends stay independent: either can occur without the other.\n\nChosen weights do give robustness to one class of violations, those the design's trend model can express. The simulations above price it. The gain is real when the control pool contains trends like the treated group's. It is partial, because the weights are fitted on a noisy pre-period path and shrunk toward uniform. And it costs the pretest and regression-to-the-mean terms of the last section. No weighting of observed outcomes tests the assumption. To do that we bound the violation instead of reweighting, using the observed pre-period differences to limit how large the post-period departure can be (Rambachan and Roth 2023).\n\n## Summary\n\n1. **A signed weighting of the outcomes.** FWL writes $\\hat\\beta = \\sum_i \\omega_i y_i$ with $\\omega_i = \\tilde V_i / \\sum_j \\tilde V_j^2$ (@eq-omega): a signed, computable weighting of the observed outcomes, different from the effect weights $w_i = \\tilde V_i V_i$.\n2. **Two constraints.** The weights sum to zero and the weighted regressor sums to one: $\\sum_i \\omega_i = 0$ and $\\sum_i \\omega_i V_i = 1$.\n3. **The sign shows direction.** Because $\\omega_i$ is proportional to $\\tilde V_i$, not to $\\tilde V_i^2$, it carries a sign: it shows which rows push $\\hat\\beta$ up and which pull it down, and, under controls with thin overlap, which enter with the sign their raw position would not predict.\n4. **The same weights beyond OLS.** Any estimator that can be written $\\hat\\tau = \\boldsymbol\\omega' \\boldsymbol Y$ has outcome weights, so the same object and its checks reach AIPW, double machine learning, and causal forests (Knaus 2024). PLR's denominator $\\tilde{\\boldsymbol D}'\\tilde{\\boldsymbol D}$ reveals its estimand as the VWATE (@eq-vwate), not the ATE; and the sum-to-zero of OLS need not become a sum to $\\pm 1$ within the treated and control groups.\n5. **From difference in means to difference-in-differences.** Regressed on the treatment alone, $\\hat\\beta$ is the difference in group means; a $2 \\times 2$ difference-in-differences is a signed contrast of four cell means. With covariates, a doubly-robust DiD weights the outcome changes, $\\widehat{\\text{ATT}} = \\boldsymbol\\omega' \\Delta Y$ (Sant'Anna and Zhao 2020), open to the same checks.\n6. **Staggered designs.** In staggered TWFE the outcome weights flag both treated cells used as controls and untreated cells used as treated — the observation-level version of the Bacon (2021) forbidden comparisons. Estimators that fit counterfactuals on untreated observations alone (Borusyak, Jaravel, and Spiess 2024; Callaway and Sant'Anna 2021) cannot assign negative weight to any treated cell, so the forbidden-comparison diagnostic is clean by construction.\n7. **Rank counts the cohorts.** As an $N \\times T$ matrix, the outcome weights of a block design have rank one and factor into a unit part times a time part (@eq-outcome-weights-13). The plain $2 \\times 2$ and synthetic difference-in-differences differ only in whether those margins are uniform or fitted. Staggered adoption raises the rank to the number of treated cohorts, and only above rank one can a treated cell enter negatively.\n8. **Reweighting controls toward parallel trends works, but not completely.** The question needs a model in which trends vary by unit before it means anything. Under such a model, fitting both margins cuts bias sharply. What survives is the part of the trend gap the weights leave unmatched, because they are fitted on a noisy pre-period path and shrunk toward uniform. A simplex weight also cannot reach a treated trend outside the range the control trends span, though that limit is usually not the binding one.\n9. **Fitted weights carry a cost.** Weights fitted on pre-period outcomes make $\\hat\\tau$ non-linear in $\\boldsymbol Y$, so inference must account for their estimation. Selecting on a noisy pre-period statistic is a pretest (Roth 2022). Matching on pre-period levels produces regression to the mean (Daw and Hatfield 2018), with the size given by @eq-outcome-weights-15. Fitting the weights with an intercept, so only trajectories need to match and never levels, avoids it.\n",
    "supporting": [
      "outcome-weights_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}